<?php

/**
 * ApFormThemes filter form base class.
 *
 * @package    permitflow
 * @subpackage filter
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseApFormThemesFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'status'                    => new sfWidgetFormFilterInput(),
      'theme_has_css'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'theme_name'                => new sfWidgetFormFilterInput(),
      'theme_built_in'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'logo_type'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'logo_custom_image'         => new sfWidgetFormFilterInput(),
      'logo_custom_height'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'logo_default_image'        => new sfWidgetFormFilterInput(),
      'logo_default_repeat'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'wallpaper_bg_type'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'wallpaper_bg_color'        => new sfWidgetFormFilterInput(),
      'wallpaper_bg_pattern'      => new sfWidgetFormFilterInput(),
      'wallpaper_bg_custom'       => new sfWidgetFormFilterInput(),
      'header_bg_type'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'header_bg_color'           => new sfWidgetFormFilterInput(),
      'header_bg_pattern'         => new sfWidgetFormFilterInput(),
      'header_bg_custom'          => new sfWidgetFormFilterInput(),
      'form_bg_type'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_bg_color'             => new sfWidgetFormFilterInput(),
      'form_bg_pattern'           => new sfWidgetFormFilterInput(),
      'form_bg_custom'            => new sfWidgetFormFilterInput(),
      'highlight_bg_type'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'highlight_bg_color'        => new sfWidgetFormFilterInput(),
      'highlight_bg_pattern'      => new sfWidgetFormFilterInput(),
      'highlight_bg_custom'       => new sfWidgetFormFilterInput(),
      'guidelines_bg_type'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'guidelines_bg_color'       => new sfWidgetFormFilterInput(),
      'guidelines_bg_pattern'     => new sfWidgetFormFilterInput(),
      'guidelines_bg_custom'      => new sfWidgetFormFilterInput(),
      'field_bg_type'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_bg_color'            => new sfWidgetFormFilterInput(),
      'field_bg_pattern'          => new sfWidgetFormFilterInput(),
      'field_bg_custom'           => new sfWidgetFormFilterInput(),
      'form_title_font_type'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_title_font_weight'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_title_font_style'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_title_font_size'      => new sfWidgetFormFilterInput(),
      'form_title_font_color'     => new sfWidgetFormFilterInput(),
      'form_desc_font_type'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_desc_font_weight'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_desc_font_style'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_desc_font_size'       => new sfWidgetFormFilterInput(),
      'form_desc_font_color'      => new sfWidgetFormFilterInput(),
      'field_title_font_type'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_title_font_weight'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_title_font_style'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_title_font_size'     => new sfWidgetFormFilterInput(),
      'field_title_font_color'    => new sfWidgetFormFilterInput(),
      'guidelines_font_type'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'guidelines_font_weight'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'guidelines_font_style'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'guidelines_font_size'      => new sfWidgetFormFilterInput(),
      'guidelines_font_color'     => new sfWidgetFormFilterInput(),
      'section_title_font_type'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'section_title_font_weight' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'section_title_font_style'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'section_title_font_size'   => new sfWidgetFormFilterInput(),
      'section_title_font_color'  => new sfWidgetFormFilterInput(),
      'section_desc_font_type'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'section_desc_font_weight'  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'section_desc_font_style'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'section_desc_font_size'    => new sfWidgetFormFilterInput(),
      'section_desc_font_color'   => new sfWidgetFormFilterInput(),
      'field_text_font_type'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_text_font_weight'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_text_font_style'     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'field_text_font_size'      => new sfWidgetFormFilterInput(),
      'field_text_font_color'     => new sfWidgetFormFilterInput(),
      'border_form_width'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'border_form_style'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'border_form_color'         => new sfWidgetFormFilterInput(),
      'border_guidelines_width'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'border_guidelines_style'   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'border_guidelines_color'   => new sfWidgetFormFilterInput(),
      'border_section_width'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'border_section_style'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'border_section_color'      => new sfWidgetFormFilterInput(),
      'form_shadow_style'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_shadow_size'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_shadow_brightness'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_button_type'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_button_text'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_button_image'         => new sfWidgetFormFilterInput(),
      'advanced_css'              => new sfWidgetFormFilterInput(),
      'user_id'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'theme_is_private'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
    ));

    $this->setValidators(array(
      'status'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'theme_has_css'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'theme_name'                => new sfValidatorPass(array('required' => false)),
      'theme_built_in'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logo_type'                 => new sfValidatorPass(array('required' => false)),
      'logo_custom_image'         => new sfValidatorPass(array('required' => false)),
      'logo_custom_height'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logo_default_image'        => new sfValidatorPass(array('required' => false)),
      'logo_default_repeat'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'wallpaper_bg_type'         => new sfValidatorPass(array('required' => false)),
      'wallpaper_bg_color'        => new sfValidatorPass(array('required' => false)),
      'wallpaper_bg_pattern'      => new sfValidatorPass(array('required' => false)),
      'wallpaper_bg_custom'       => new sfValidatorPass(array('required' => false)),
      'header_bg_type'            => new sfValidatorPass(array('required' => false)),
      'header_bg_color'           => new sfValidatorPass(array('required' => false)),
      'header_bg_pattern'         => new sfValidatorPass(array('required' => false)),
      'header_bg_custom'          => new sfValidatorPass(array('required' => false)),
      'form_bg_type'              => new sfValidatorPass(array('required' => false)),
      'form_bg_color'             => new sfValidatorPass(array('required' => false)),
      'form_bg_pattern'           => new sfValidatorPass(array('required' => false)),
      'form_bg_custom'            => new sfValidatorPass(array('required' => false)),
      'highlight_bg_type'         => new sfValidatorPass(array('required' => false)),
      'highlight_bg_color'        => new sfValidatorPass(array('required' => false)),
      'highlight_bg_pattern'      => new sfValidatorPass(array('required' => false)),
      'highlight_bg_custom'       => new sfValidatorPass(array('required' => false)),
      'guidelines_bg_type'        => new sfValidatorPass(array('required' => false)),
      'guidelines_bg_color'       => new sfValidatorPass(array('required' => false)),
      'guidelines_bg_pattern'     => new sfValidatorPass(array('required' => false)),
      'guidelines_bg_custom'      => new sfValidatorPass(array('required' => false)),
      'field_bg_type'             => new sfValidatorPass(array('required' => false)),
      'field_bg_color'            => new sfValidatorPass(array('required' => false)),
      'field_bg_pattern'          => new sfValidatorPass(array('required' => false)),
      'field_bg_custom'           => new sfValidatorPass(array('required' => false)),
      'form_title_font_type'      => new sfValidatorPass(array('required' => false)),
      'form_title_font_weight'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_title_font_style'     => new sfValidatorPass(array('required' => false)),
      'form_title_font_size'      => new sfValidatorPass(array('required' => false)),
      'form_title_font_color'     => new sfValidatorPass(array('required' => false)),
      'form_desc_font_type'       => new sfValidatorPass(array('required' => false)),
      'form_desc_font_weight'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_desc_font_style'      => new sfValidatorPass(array('required' => false)),
      'form_desc_font_size'       => new sfValidatorPass(array('required' => false)),
      'form_desc_font_color'      => new sfValidatorPass(array('required' => false)),
      'field_title_font_type'     => new sfValidatorPass(array('required' => false)),
      'field_title_font_weight'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'field_title_font_style'    => new sfValidatorPass(array('required' => false)),
      'field_title_font_size'     => new sfValidatorPass(array('required' => false)),
      'field_title_font_color'    => new sfValidatorPass(array('required' => false)),
      'guidelines_font_type'      => new sfValidatorPass(array('required' => false)),
      'guidelines_font_weight'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'guidelines_font_style'     => new sfValidatorPass(array('required' => false)),
      'guidelines_font_size'      => new sfValidatorPass(array('required' => false)),
      'guidelines_font_color'     => new sfValidatorPass(array('required' => false)),
      'section_title_font_type'   => new sfValidatorPass(array('required' => false)),
      'section_title_font_weight' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'section_title_font_style'  => new sfValidatorPass(array('required' => false)),
      'section_title_font_size'   => new sfValidatorPass(array('required' => false)),
      'section_title_font_color'  => new sfValidatorPass(array('required' => false)),
      'section_desc_font_type'    => new sfValidatorPass(array('required' => false)),
      'section_desc_font_weight'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'section_desc_font_style'   => new sfValidatorPass(array('required' => false)),
      'section_desc_font_size'    => new sfValidatorPass(array('required' => false)),
      'section_desc_font_color'   => new sfValidatorPass(array('required' => false)),
      'field_text_font_type'      => new sfValidatorPass(array('required' => false)),
      'field_text_font_weight'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'field_text_font_style'     => new sfValidatorPass(array('required' => false)),
      'field_text_font_size'      => new sfValidatorPass(array('required' => false)),
      'field_text_font_color'     => new sfValidatorPass(array('required' => false)),
      'border_form_width'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'border_form_style'         => new sfValidatorPass(array('required' => false)),
      'border_form_color'         => new sfValidatorPass(array('required' => false)),
      'border_guidelines_width'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'border_guidelines_style'   => new sfValidatorPass(array('required' => false)),
      'border_guidelines_color'   => new sfValidatorPass(array('required' => false)),
      'border_section_width'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'border_section_style'      => new sfValidatorPass(array('required' => false)),
      'border_section_color'      => new sfValidatorPass(array('required' => false)),
      'form_shadow_style'         => new sfValidatorPass(array('required' => false)),
      'form_shadow_size'          => new sfValidatorPass(array('required' => false)),
      'form_shadow_brightness'    => new sfValidatorPass(array('required' => false)),
      'form_button_type'          => new sfValidatorPass(array('required' => false)),
      'form_button_text'          => new sfValidatorPass(array('required' => false)),
      'form_button_image'         => new sfValidatorPass(array('required' => false)),
      'advanced_css'              => new sfValidatorPass(array('required' => false)),
      'user_id'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'theme_is_private'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('ap_form_themes_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ApFormThemes';
  }

  public function getFields()
  {
    return array(
      'theme_id'                  => 'Number',
      'status'                    => 'Number',
      'theme_has_css'             => 'Number',
      'theme_name'                => 'Text',
      'theme_built_in'            => 'Number',
      'logo_type'                 => 'Text',
      'logo_custom_image'         => 'Text',
      'logo_custom_height'        => 'Number',
      'logo_default_image'        => 'Text',
      'logo_default_repeat'       => 'Number',
      'wallpaper_bg_type'         => 'Text',
      'wallpaper_bg_color'        => 'Text',
      'wallpaper_bg_pattern'      => 'Text',
      'wallpaper_bg_custom'       => 'Text',
      'header_bg_type'            => 'Text',
      'header_bg_color'           => 'Text',
      'header_bg_pattern'         => 'Text',
      'header_bg_custom'          => 'Text',
      'form_bg_type'              => 'Text',
      'form_bg_color'             => 'Text',
      'form_bg_pattern'           => 'Text',
      'form_bg_custom'            => 'Text',
      'highlight_bg_type'         => 'Text',
      'highlight_bg_color'        => 'Text',
      'highlight_bg_pattern'      => 'Text',
      'highlight_bg_custom'       => 'Text',
      'guidelines_bg_type'        => 'Text',
      'guidelines_bg_color'       => 'Text',
      'guidelines_bg_pattern'     => 'Text',
      'guidelines_bg_custom'      => 'Text',
      'field_bg_type'             => 'Text',
      'field_bg_color'            => 'Text',
      'field_bg_pattern'          => 'Text',
      'field_bg_custom'           => 'Text',
      'form_title_font_type'      => 'Text',
      'form_title_font_weight'    => 'Number',
      'form_title_font_style'     => 'Text',
      'form_title_font_size'      => 'Text',
      'form_title_font_color'     => 'Text',
      'form_desc_font_type'       => 'Text',
      'form_desc_font_weight'     => 'Number',
      'form_desc_font_style'      => 'Text',
      'form_desc_font_size'       => 'Text',
      'form_desc_font_color'      => 'Text',
      'field_title_font_type'     => 'Text',
      'field_title_font_weight'   => 'Number',
      'field_title_font_style'    => 'Text',
      'field_title_font_size'     => 'Text',
      'field_title_font_color'    => 'Text',
      'guidelines_font_type'      => 'Text',
      'guidelines_font_weight'    => 'Number',
      'guidelines_font_style'     => 'Text',
      'guidelines_font_size'      => 'Text',
      'guidelines_font_color'     => 'Text',
      'section_title_font_type'   => 'Text',
      'section_title_font_weight' => 'Number',
      'section_title_font_style'  => 'Text',
      'section_title_font_size'   => 'Text',
      'section_title_font_color'  => 'Text',
      'section_desc_font_type'    => 'Text',
      'section_desc_font_weight'  => 'Number',
      'section_desc_font_style'   => 'Text',
      'section_desc_font_size'    => 'Text',
      'section_desc_font_color'   => 'Text',
      'field_text_font_type'      => 'Text',
      'field_text_font_weight'    => 'Number',
      'field_text_font_style'     => 'Text',
      'field_text_font_size'      => 'Text',
      'field_text_font_color'     => 'Text',
      'border_form_width'         => 'Number',
      'border_form_style'         => 'Text',
      'border_form_color'         => 'Text',
      'border_guidelines_width'   => 'Number',
      'border_guidelines_style'   => 'Text',
      'border_guidelines_color'   => 'Text',
      'border_section_width'      => 'Number',
      'border_section_style'      => 'Text',
      'border_section_color'      => 'Text',
      'form_shadow_style'         => 'Text',
      'form_shadow_size'          => 'Text',
      'form_shadow_brightness'    => 'Text',
      'form_button_type'          => 'Text',
      'form_button_text'          => 'Text',
      'form_button_image'         => 'Text',
      'advanced_css'              => 'Text',
      'user_id'                   => 'Number',
      'theme_is_private'          => 'Number',
    );
  }
}
