<?php

/**
 * ApFormElements filter form base class.
 *
 * @package    permitflow
 * @subpackage filter
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseApFormElementsFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'element_title'                       => new sfWidgetFormFilterInput(),
      'element_guidelines'                  => new sfWidgetFormFilterInput(),
      'element_size'                        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_is_required'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_is_unique'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_is_readonly'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_is_private'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_enable_placeholder'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_text_default_type'           => new sfWidgetFormFilterInput(),
      'element_text_default_length'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_text_default_random_type'    => new sfWidgetFormFilterInput(),
      'element_text_default_prefix'         => new sfWidgetFormFilterInput(),
      'element_text_default_case'           => new sfWidgetFormFilterInput(),
      'element_type'                        => new sfWidgetFormFilterInput(),
      'element_position'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_default_value'               => new sfWidgetFormFilterInput(),
      'element_constraint'                  => new sfWidgetFormFilterInput(),
      'element_total_child'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_css_class'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_range_min'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_range_max'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_range_limit_by'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_status'                      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_choice_columns'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_choice_has_other'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_choice_other_label'          => new sfWidgetFormFilterInput(),
      'element_choice_limit_rule'           => new sfWidgetFormFilterInput(),
      'element_choice_limit_qty'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_choice_limit_range_min'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_choice_limit_range_max'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_choice_max_entry'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_time_showsecond'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_time_24hour'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_address_hideline2'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_address_us_only'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_enable_range'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_range_min'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'element_date_range_max'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'element_date_enable_selection_limit' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_selection_max'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_past_future'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_disable_past_future'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_disable_weekend'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_disable_specific'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_date_disabled_list'          => new sfWidgetFormFilterInput(),
      'element_file_enable_type_limit'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_block_or_allow'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_type_list'              => new sfWidgetFormFilterInput(),
      'element_file_as_attachment'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_enable_advance'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_auto_upload'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_enable_multi_upload'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_max_selection'          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_enable_size_limit'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_file_size_max'               => new sfWidgetFormFilterInput(),
      'element_matrix_allow_multiselect'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_matrix_parent_id'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_submit_use_image'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_submit_primary_text'         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_submit_secondary_text'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_submit_primary_img'          => new sfWidgetFormFilterInput(),
      'element_submit_secondary_img'        => new sfWidgetFormFilterInput(),
      'element_page_title'                  => new sfWidgetFormFilterInput(),
      'element_page_number'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_section_display_in_email'    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_section_enable_scroll'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_number_enable_quantity'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'element_number_quantity_link'        => new sfWidgetFormFilterInput(),
      'element_table_name'                  => new sfWidgetFormFilterInput(),
      'element_field_value'                 => new sfWidgetFormFilterInput(),
      'element_field_name'                  => new sfWidgetFormFilterInput(),
      'element_option_query'                => new sfWidgetFormFilterInput(),
      'element_existing_form'               => new sfWidgetFormFilterInput(),
      'element_existing_stage'              => new sfWidgetFormFilterInput(),
      'element_remote_username'             => new sfWidgetFormFilterInput(),
      'element_remote_password'             => new sfWidgetFormFilterInput(),
      'element_remote_value'                => new sfWidgetFormFilterInput(),
      'element_price_class'                 => new sfWidgetFormFilterInput(),
      'element_remote_server_field'         => new sfWidgetFormFilterInput(),
      'element_jsondef'                     => new sfWidgetFormFilterInput(),
      'element_remote_post'                 => new sfWidgetFormFilterInput(),
      'element_validator_class'             => new sfWidgetFormFilterInput(),
      'element_field_error_message'         => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'element_title'                       => new sfValidatorPass(array('required' => false)),
      'element_guidelines'                  => new sfValidatorPass(array('required' => false)),
      'element_size'                        => new sfValidatorPass(array('required' => false)),
      'element_is_required'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_is_unique'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_is_readonly'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_is_private'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_enable_placeholder'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_text_default_type'           => new sfValidatorPass(array('required' => false)),
      'element_text_default_length'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_text_default_random_type'    => new sfValidatorPass(array('required' => false)),
      'element_text_default_prefix'         => new sfValidatorPass(array('required' => false)),
      'element_text_default_case'           => new sfValidatorPass(array('required' => false)),
      'element_type'                        => new sfValidatorPass(array('required' => false)),
      'element_position'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_default_value'               => new sfValidatorPass(array('required' => false)),
      'element_constraint'                  => new sfValidatorPass(array('required' => false)),
      'element_total_child'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_css_class'                   => new sfValidatorPass(array('required' => false)),
      'element_range_min'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_range_max'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_range_limit_by'              => new sfValidatorPass(array('required' => false)),
      'element_status'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_choice_columns'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_choice_has_other'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_choice_other_label'          => new sfValidatorPass(array('required' => false)),
      'element_choice_limit_rule'           => new sfValidatorPass(array('required' => false)),
      'element_choice_limit_qty'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_choice_limit_range_min'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_choice_limit_range_max'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_choice_max_entry'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_time_showsecond'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_time_24hour'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_address_hideline2'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_address_us_only'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_enable_range'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_range_min'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'element_date_range_max'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'element_date_enable_selection_limit' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_selection_max'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_past_future'            => new sfValidatorPass(array('required' => false)),
      'element_date_disable_past_future'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_disable_weekend'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_disable_specific'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_date_disabled_list'          => new sfValidatorPass(array('required' => false)),
      'element_file_enable_type_limit'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_block_or_allow'         => new sfValidatorPass(array('required' => false)),
      'element_file_type_list'              => new sfValidatorPass(array('required' => false)),
      'element_file_as_attachment'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_enable_advance'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_auto_upload'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_enable_multi_upload'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_max_selection'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_enable_size_limit'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_file_size_max'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_matrix_allow_multiselect'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_matrix_parent_id'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_submit_use_image'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_submit_primary_text'         => new sfValidatorPass(array('required' => false)),
      'element_submit_secondary_text'       => new sfValidatorPass(array('required' => false)),
      'element_submit_primary_img'          => new sfValidatorPass(array('required' => false)),
      'element_submit_secondary_img'        => new sfValidatorPass(array('required' => false)),
      'element_page_title'                  => new sfValidatorPass(array('required' => false)),
      'element_page_number'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_section_display_in_email'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_section_enable_scroll'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_number_enable_quantity'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_number_quantity_link'        => new sfValidatorPass(array('required' => false)),
      'element_table_name'                  => new sfValidatorPass(array('required' => false)),
      'element_field_value'                 => new sfValidatorPass(array('required' => false)),
      'element_field_name'                  => new sfValidatorPass(array('required' => false)),
      'element_option_query'                => new sfValidatorPass(array('required' => false)),
      'element_existing_form'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_existing_stage'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'element_remote_username'             => new sfValidatorPass(array('required' => false)),
      'element_remote_password'             => new sfValidatorPass(array('required' => false)),
      'element_remote_value'                => new sfValidatorPass(array('required' => false)),
      'element_price_class'                 => new sfValidatorPass(array('required' => false)),
      'element_remote_server_field'         => new sfValidatorPass(array('required' => false)),
      'element_jsondef'                     => new sfValidatorPass(array('required' => false)),
      'element_remote_post'                 => new sfValidatorPass(array('required' => false)),
      'element_validator_class'             => new sfValidatorPass(array('required' => false)),
      'element_field_error_message'         => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ap_form_elements_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ApFormElements';
  }

  public function getFields()
  {
    return array(
      'form_id'                             => 'Number',
      'element_id'                          => 'Number',
      'element_title'                       => 'Text',
      'element_guidelines'                  => 'Text',
      'element_size'                        => 'Text',
      'element_is_required'                 => 'Number',
      'element_is_unique'                   => 'Number',
      'element_is_readonly'                 => 'Number',
      'element_is_private'                  => 'Number',
      'element_enable_placeholder'          => 'Number',
      'element_text_default_type'           => 'Text',
      'element_text_default_length'         => 'Number',
      'element_text_default_random_type'    => 'Text',
      'element_text_default_prefix'         => 'Text',
      'element_text_default_case'           => 'Text',
      'element_type'                        => 'Text',
      'element_position'                    => 'Number',
      'element_default_value'               => 'Text',
      'element_constraint'                  => 'Text',
      'element_total_child'                 => 'Number',
      'element_css_class'                   => 'Text',
      'element_range_min'                   => 'Number',
      'element_range_max'                   => 'Number',
      'element_range_limit_by'              => 'Text',
      'element_status'                      => 'Number',
      'element_choice_columns'              => 'Number',
      'element_choice_has_other'            => 'Number',
      'element_choice_other_label'          => 'Text',
      'element_choice_limit_rule'           => 'Text',
      'element_choice_limit_qty'            => 'Number',
      'element_choice_limit_range_min'      => 'Number',
      'element_choice_limit_range_max'      => 'Number',
      'element_choice_max_entry'            => 'Number',
      'element_time_showsecond'             => 'Number',
      'element_time_24hour'                 => 'Number',
      'element_address_hideline2'           => 'Number',
      'element_address_us_only'             => 'Number',
      'element_date_enable_range'           => 'Number',
      'element_date_range_min'              => 'Date',
      'element_date_range_max'              => 'Date',
      'element_date_enable_selection_limit' => 'Number',
      'element_date_selection_max'          => 'Number',
      'element_date_past_future'            => 'Text',
      'element_date_disable_past_future'    => 'Number',
      'element_date_disable_weekend'        => 'Number',
      'element_date_disable_specific'       => 'Number',
      'element_date_disabled_list'          => 'Text',
      'element_file_enable_type_limit'      => 'Number',
      'element_file_block_or_allow'         => 'Text',
      'element_file_type_list'              => 'Text',
      'element_file_as_attachment'          => 'Number',
      'element_file_enable_advance'         => 'Number',
      'element_file_auto_upload'            => 'Number',
      'element_file_enable_multi_upload'    => 'Number',
      'element_file_max_selection'          => 'Number',
      'element_file_enable_size_limit'      => 'Number',
      'element_file_size_max'               => 'Number',
      'element_matrix_allow_multiselect'    => 'Number',
      'element_matrix_parent_id'            => 'Number',
      'element_submit_use_image'            => 'Number',
      'element_submit_primary_text'         => 'Text',
      'element_submit_secondary_text'       => 'Text',
      'element_submit_primary_img'          => 'Text',
      'element_submit_secondary_img'        => 'Text',
      'element_page_title'                  => 'Text',
      'element_page_number'                 => 'Number',
      'element_section_display_in_email'    => 'Number',
      'element_section_enable_scroll'       => 'Number',
      'element_number_enable_quantity'      => 'Number',
      'element_number_quantity_link'        => 'Text',
      'element_table_name'                  => 'Text',
      'element_field_value'                 => 'Text',
      'element_field_name'                  => 'Text',
      'element_option_query'                => 'Text',
      'element_existing_form'               => 'Number',
      'element_existing_stage'              => 'Number',
      'element_remote_username'             => 'Text',
      'element_remote_password'             => 'Text',
      'element_remote_value'                => 'Text',
      'element_price_class'                 => 'Text',
      'element_remote_server_field'         => 'Text',
      'element_jsondef'                     => 'Text',
      'element_remote_post'                 => 'Text',
      'element_validator_class'             => 'Text',
      'element_field_error_message'         => 'Text',
    );
  }
}
