<?php

/**
 * ApForms filter form base class.
 *
 * @package    permitflow
 * @subpackage filter
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseApFormsFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'logic_permission_enable'               => new sfWidgetFormFilterInput(),
      'logic_workflow_enable'                 => new sfWidgetFormFilterInput(),
      'form_name'                             => new sfWidgetFormFilterInput(),
      'form_description'                      => new sfWidgetFormFilterInput(),
      'form_name_hide'                        => new sfWidgetFormFilterInput(),
      'form_email'                            => new sfWidgetFormFilterInput(),
      'form_redirect'                         => new sfWidgetFormFilterInput(),
      'form_success_message'                  => new sfWidgetFormFilterInput(),
      'form_password'                         => new sfWidgetFormFilterInput(),
      'form_unique_ip'                        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_frame_height'                     => new sfWidgetFormFilterInput(),
      'form_has_css'                          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_captcha'                          => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_active'                           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_review'                           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_default_application'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'esl_from_name'                         => new sfWidgetFormFilterInput(),
      'esl_from_email_address'                => new sfWidgetFormFilterInput(),
      'esl_subject'                           => new sfWidgetFormFilterInput(),
      'esl_content'                           => new sfWidgetFormFilterInput(),
      'esl_plain_text'                        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'esr_email_address'                     => new sfWidgetFormFilterInput(),
      'esr_from_name'                         => new sfWidgetFormFilterInput(),
      'esr_from_email_address'                => new sfWidgetFormFilterInput(),
      'esr_subject'                           => new sfWidgetFormFilterInput(),
      'esr_content'                           => new sfWidgetFormFilterInput(),
      'esr_plain_text'                        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_tags'                             => new sfWidgetFormFilterInput(),
      'form_redirect_enable'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_unique_ip_maxcount'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_unique_ip_period'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_captcha_type'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_theme_id'                         => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_resume_enable'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_resume_subject'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_resume_content'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_resume_from_name'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_resume_from_email_address'        => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_custom_script_enable'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_custom_script_url'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_limit_enable'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_limit'                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_label_alignment'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_language'                         => new sfWidgetFormFilterInput(),
      'form_page_total'                       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_lastpage_title'                   => new sfWidgetFormFilterInput(),
      'form_submit_primary_text'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_submit_secondary_text'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_submit_primary_img'               => new sfWidgetFormFilterInput(),
      'form_submit_secondary_img'             => new sfWidgetFormFilterInput(),
      'form_submit_use_image'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_review_primary_text'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_review_secondary_text'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_review_primary_img'               => new sfWidgetFormFilterInput(),
      'form_review_secondary_img'             => new sfWidgetFormFilterInput(),
      'form_review_use_image'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_review_title'                     => new sfWidgetFormFilterInput(),
      'form_review_description'               => new sfWidgetFormFilterInput(),
      'form_pagination_type'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_schedule_enable'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_schedule_start_date'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'form_schedule_end_date'                => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'form_schedule_start_hour'              => new sfWidgetFormFilterInput(),
      'form_schedule_end_hour'                => new sfWidgetFormFilterInput(),
      'esl_enable'                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'esr_enable'                            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_enable_merchant'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_merchant_type'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_paypal_email'                  => new sfWidgetFormFilterInput(),
      'payment_paypal_language'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_currency'                      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_show_total'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_total_location'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_enable_recurring'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_recurring_cycle'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_recurring_unit'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_price_type'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_price_amount'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_price_name'                    => new sfWidgetFormFilterInput(),
      'payment_enable_discount'               => new sfWidgetFormFilterInput(),
      'logic_field_enable'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'logic_page_enable'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_enable_trial'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_trial_period'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_trial_unit'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_trial_amount'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_pesapal_live_secret_key'       => new sfWidgetFormFilterInput(),
      'payment_pesapal_live_public_key'       => new sfWidgetFormFilterInput(),
      'payment_pesapal_test_secret_key'       => new sfWidgetFormFilterInput(),
      'payment_pesapal_test_public_key'       => new sfWidgetFormFilterInput(),
      'payment_pesapal_enable_test_mode'      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_paypal_enable_test_mode'       => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_enable_invoice'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_invoice_email'                 => new sfWidgetFormFilterInput(),
      'payment_delay_notifications'           => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_ask_billing'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_ask_shipping'                  => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_discount_element_id'           => new sfWidgetFormFilterInput(),
      'form_disabled_message'                 => new sfWidgetFormFilterInput(),
      'payment_enable_tax'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_tax_rate'                      => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_tax_amount'                    => new sfWidgetFormFilterInput(),
      'payment_discount_code'                 => new sfWidgetFormFilterInput(),
      'webhook_enable'                        => new sfWidgetFormFilterInput(),
      'payment_discount_type'                 => new sfWidgetFormFilterInput(),
      'payment_discount_amount'               => new sfWidgetFormFilterInput(),
      'logic_email_enable'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'form_stage'                            => new sfWidgetFormFilterInput(),
      'form_group'                            => new sfWidgetFormFilterInput(),
      'form_department'                       => new sfWidgetFormFilterInput(),
      'form_department_stage'                 => new sfWidgetFormFilterInput(),
      'form_idn'                              => new sfWidgetFormFilterInput(),
      'form_type'                             => new sfWidgetFormFilterInput(),
      'form_code'                             => new sfWidgetFormFilterInput(),
      'payment_cellulant_checkout_url'        => new sfWidgetFormFilterInput(),
      'payment_cellulant_merchant_username'   => new sfWidgetFormFilterInput(),
      'payment_cellulant_merchant_password'   => new sfWidgetFormFilterInput(),
      'payment_cellulant_service_id'          => new sfWidgetFormFilterInput(),
      'payment_jambopay_business'             => new sfWidgetFormFilterInput(),
      'payment_jambopay_shared_key'           => new sfWidgetFormFilterInput(),
      'logic_webhook_enable'                  => new sfWidgetFormFilterInput(),
      'logic_success_enable'                  => new sfWidgetFormFilterInput(),
      'esl_bcc_email_address'                 => new sfWidgetFormFilterInput(),
      'esl_replyto_email_address'             => new sfWidgetFormFilterInput(),
      'esl_pdf_enable'                        => new sfWidgetFormFilterInput(),
      'esl_pdf_content'                       => new sfWidgetFormFilterInput(),
      'esr_bcc_email_address'                 => new sfWidgetFormFilterInput(),
      'esr_replyto_email_address'             => new sfWidgetFormFilterInput(),
      'esr_pdf_enable'                        => new sfWidgetFormFilterInput(),
      'esr_pdf_content'                       => new sfWidgetFormFilterInput(),
      'payment_enable_setupfee'               => new sfWidgetFormFilterInput(),
      'payment_setupfee_amount'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'payment_stripe_live_secret_key'        => new sfWidgetFormFilterInput(),
      'payment_stripe_live_public_key'        => new sfWidgetFormFilterInput(),
      'payment_stripe_test_secret_key'        => new sfWidgetFormFilterInput(),
      'payment_stripe_test_public_key'        => new sfWidgetFormFilterInput(),
      'payment_stripe_enable_test_mode'       => new sfWidgetFormFilterInput(),
      'payment_stripe_enable_receipt'         => new sfWidgetFormFilterInput(),
      'payment_stripe_receipt_element_id'     => new sfWidgetFormFilterInput(),
      'payment_authorizenet_live_apiloginid'  => new sfWidgetFormFilterInput(),
      'payment_authorizenet_live_transkey'    => new sfWidgetFormFilterInput(),
      'payment_authorizenet_test_apiloginid'  => new sfWidgetFormFilterInput(),
      'payment_authorizenet_test_transkey'    => new sfWidgetFormFilterInput(),
      'payment_authorizenet_enable_test_mode' => new sfWidgetFormFilterInput(),
      'payment_authorizenet_save_cc_data'     => new sfWidgetFormFilterInput(),
      'payment_braintree_live_merchant_id'    => new sfWidgetFormFilterInput(),
      'payment_braintree_live_public_key'     => new sfWidgetFormFilterInput(),
      'payment_braintree_live_private_key'    => new sfWidgetFormFilterInput(),
      'payment_braintree_live_encryption_key' => new sfWidgetFormFilterInput(),
      'payment_braintree_test_merchant_id'    => new sfWidgetFormFilterInput(),
      'payment_braintree_test_public_key'     => new sfWidgetFormFilterInput(),
      'payment_braintree_test_private_key'    => new sfWidgetFormFilterInput(),
      'payment_braintree_test_encryption_key' => new sfWidgetFormFilterInput(),
      'payment_braintree_enable_test_mode'    => new sfWidgetFormFilterInput(),
      'payment_paypal_rest_live_clientid'     => new sfWidgetFormFilterInput(),
      'payment_paypal_rest_live_secret_key'   => new sfWidgetFormFilterInput(),
      'payment_paypal_rest_test_clientid'     => new sfWidgetFormFilterInput(),
      'payment_paypal_rest_test_secret_key'   => new sfWidgetFormFilterInput(),
      'payment_paypal_rest_enable_test_mode'  => new sfWidgetFormFilterInput(),
      'payment_discount_max_usage'            => new sfWidgetFormFilterInput(),
      'payment_discount_expiry_date'          => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'logic_permission_enable'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logic_workflow_enable'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_name'                             => new sfValidatorPass(array('required' => false)),
      'form_description'                      => new sfValidatorPass(array('required' => false)),
      'form_name_hide'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_email'                            => new sfValidatorPass(array('required' => false)),
      'form_redirect'                         => new sfValidatorPass(array('required' => false)),
      'form_success_message'                  => new sfValidatorPass(array('required' => false)),
      'form_password'                         => new sfValidatorPass(array('required' => false)),
      'form_unique_ip'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_frame_height'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_has_css'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_captcha'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_active'                           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_review'                           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_default_application'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esl_from_name'                         => new sfValidatorPass(array('required' => false)),
      'esl_from_email_address'                => new sfValidatorPass(array('required' => false)),
      'esl_subject'                           => new sfValidatorPass(array('required' => false)),
      'esl_content'                           => new sfValidatorPass(array('required' => false)),
      'esl_plain_text'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esr_email_address'                     => new sfValidatorPass(array('required' => false)),
      'esr_from_name'                         => new sfValidatorPass(array('required' => false)),
      'esr_from_email_address'                => new sfValidatorPass(array('required' => false)),
      'esr_subject'                           => new sfValidatorPass(array('required' => false)),
      'esr_content'                           => new sfValidatorPass(array('required' => false)),
      'esr_plain_text'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_tags'                             => new sfValidatorPass(array('required' => false)),
      'form_redirect_enable'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_unique_ip_maxcount'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_unique_ip_period'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_captcha_type'                     => new sfValidatorPass(array('required' => false)),
      'form_theme_id'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_resume_enable'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_resume_subject'                   => new sfValidatorPass(array('required' => false)),
      'form_resume_content'                   => new sfValidatorPass(array('required' => false)),
      'form_resume_from_name'                 => new sfValidatorPass(array('required' => false)),
      'form_resume_from_email_address'        => new sfValidatorPass(array('required' => false)),
      'form_custom_script_enable'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_custom_script_url'                => new sfValidatorPass(array('required' => false)),
      'form_limit_enable'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_limit'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_label_alignment'                  => new sfValidatorPass(array('required' => false)),
      'form_language'                         => new sfValidatorPass(array('required' => false)),
      'form_page_total'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_lastpage_title'                   => new sfValidatorPass(array('required' => false)),
      'form_submit_primary_text'              => new sfValidatorPass(array('required' => false)),
      'form_submit_secondary_text'            => new sfValidatorPass(array('required' => false)),
      'form_submit_primary_img'               => new sfValidatorPass(array('required' => false)),
      'form_submit_secondary_img'             => new sfValidatorPass(array('required' => false)),
      'form_submit_use_image'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_review_primary_text'              => new sfValidatorPass(array('required' => false)),
      'form_review_secondary_text'            => new sfValidatorPass(array('required' => false)),
      'form_review_primary_img'               => new sfValidatorPass(array('required' => false)),
      'form_review_secondary_img'             => new sfValidatorPass(array('required' => false)),
      'form_review_use_image'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_review_title'                     => new sfValidatorPass(array('required' => false)),
      'form_review_description'               => new sfValidatorPass(array('required' => false)),
      'form_pagination_type'                  => new sfValidatorPass(array('required' => false)),
      'form_schedule_enable'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_schedule_start_date'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'form_schedule_end_date'                => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'form_schedule_start_hour'              => new sfValidatorPass(array('required' => false)),
      'form_schedule_end_hour'                => new sfValidatorPass(array('required' => false)),
      'esl_enable'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esr_enable'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_enable_merchant'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_merchant_type'                 => new sfValidatorPass(array('required' => false)),
      'payment_paypal_email'                  => new sfValidatorPass(array('required' => false)),
      'payment_paypal_language'               => new sfValidatorPass(array('required' => false)),
      'payment_currency'                      => new sfValidatorPass(array('required' => false)),
      'payment_show_total'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_total_location'                => new sfValidatorPass(array('required' => false)),
      'payment_enable_recurring'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_recurring_cycle'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_recurring_unit'                => new sfValidatorPass(array('required' => false)),
      'payment_price_type'                    => new sfValidatorPass(array('required' => false)),
      'payment_price_amount'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'payment_price_name'                    => new sfValidatorPass(array('required' => false)),
      'payment_enable_discount'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logic_field_enable'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logic_page_enable'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_enable_trial'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_trial_period'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_trial_unit'                    => new sfValidatorPass(array('required' => false)),
      'payment_trial_amount'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'payment_pesapal_live_secret_key'       => new sfValidatorPass(array('required' => false)),
      'payment_pesapal_live_public_key'       => new sfValidatorPass(array('required' => false)),
      'payment_pesapal_test_secret_key'       => new sfValidatorPass(array('required' => false)),
      'payment_pesapal_test_public_key'       => new sfValidatorPass(array('required' => false)),
      'payment_pesapal_enable_test_mode'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_paypal_enable_test_mode'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_enable_invoice'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_invoice_email'                 => new sfValidatorPass(array('required' => false)),
      'payment_delay_notifications'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_ask_billing'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_ask_shipping'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_discount_element_id'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_disabled_message'                 => new sfValidatorPass(array('required' => false)),
      'payment_enable_tax'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_tax_rate'                      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'payment_tax_amount'                    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'payment_discount_code'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'webhook_enable'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_discount_type'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_discount_amount'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logic_email_enable'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_stage'                            => new sfValidatorPass(array('required' => false)),
      'form_group'                            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_department'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_department_stage'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_idn'                              => new sfValidatorPass(array('required' => false)),
      'form_type'                             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'form_code'                             => new sfValidatorPass(array('required' => false)),
      'payment_cellulant_checkout_url'        => new sfValidatorPass(array('required' => false)),
      'payment_cellulant_merchant_username'   => new sfValidatorPass(array('required' => false)),
      'payment_cellulant_merchant_password'   => new sfValidatorPass(array('required' => false)),
      'payment_cellulant_service_id'          => new sfValidatorPass(array('required' => false)),
      'payment_jambopay_business'             => new sfValidatorPass(array('required' => false)),
      'payment_jambopay_shared_key'           => new sfValidatorPass(array('required' => false)),
      'logic_webhook_enable'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'logic_success_enable'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esl_bcc_email_address'                 => new sfValidatorPass(array('required' => false)),
      'esl_replyto_email_address'             => new sfValidatorPass(array('required' => false)),
      'esl_pdf_enable'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esl_pdf_content'                       => new sfValidatorPass(array('required' => false)),
      'esr_bcc_email_address'                 => new sfValidatorPass(array('required' => false)),
      'esr_replyto_email_address'             => new sfValidatorPass(array('required' => false)),
      'esr_pdf_enable'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esr_pdf_content'                       => new sfValidatorPass(array('required' => false)),
      'payment_enable_setupfee'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_setupfee_amount'               => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'payment_stripe_live_secret_key'        => new sfValidatorPass(array('required' => false)),
      'payment_stripe_live_public_key'        => new sfValidatorPass(array('required' => false)),
      'payment_stripe_test_secret_key'        => new sfValidatorPass(array('required' => false)),
      'payment_stripe_test_public_key'        => new sfValidatorPass(array('required' => false)),
      'payment_stripe_enable_test_mode'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_stripe_enable_receipt'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_stripe_receipt_element_id'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_authorizenet_live_apiloginid'  => new sfValidatorPass(array('required' => false)),
      'payment_authorizenet_live_transkey'    => new sfValidatorPass(array('required' => false)),
      'payment_authorizenet_test_apiloginid'  => new sfValidatorPass(array('required' => false)),
      'payment_authorizenet_test_transkey'    => new sfValidatorPass(array('required' => false)),
      'payment_authorizenet_enable_test_mode' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_authorizenet_save_cc_data'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_braintree_live_merchant_id'    => new sfValidatorPass(array('required' => false)),
      'payment_braintree_live_public_key'     => new sfValidatorPass(array('required' => false)),
      'payment_braintree_live_private_key'    => new sfValidatorPass(array('required' => false)),
      'payment_braintree_live_encryption_key' => new sfValidatorPass(array('required' => false)),
      'payment_braintree_test_merchant_id'    => new sfValidatorPass(array('required' => false)),
      'payment_braintree_test_public_key'     => new sfValidatorPass(array('required' => false)),
      'payment_braintree_test_private_key'    => new sfValidatorPass(array('required' => false)),
      'payment_braintree_test_encryption_key' => new sfValidatorPass(array('required' => false)),
      'payment_braintree_enable_test_mode'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_paypal_rest_live_clientid'     => new sfValidatorPass(array('required' => false)),
      'payment_paypal_rest_live_secret_key'   => new sfValidatorPass(array('required' => false)),
      'payment_paypal_rest_test_clientid'     => new sfValidatorPass(array('required' => false)),
      'payment_paypal_rest_test_secret_key'   => new sfValidatorPass(array('required' => false)),
      'payment_paypal_rest_enable_test_mode'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_discount_max_usage'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_discount_expiry_date'          => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ap_forms_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ApForms';
  }

  public function getFields()
  {
    return array(
      'form_id'                               => 'Number',
      'logic_permission_enable'               => 'Number',
      'logic_workflow_enable'                 => 'Number',
      'form_name'                             => 'Text',
      'form_description'                      => 'Text',
      'form_name_hide'                        => 'Number',
      'form_email'                            => 'Text',
      'form_redirect'                         => 'Text',
      'form_success_message'                  => 'Text',
      'form_password'                         => 'Text',
      'form_unique_ip'                        => 'Number',
      'form_frame_height'                     => 'Number',
      'form_has_css'                          => 'Number',
      'form_captcha'                          => 'Number',
      'form_active'                           => 'Number',
      'form_review'                           => 'Number',
      'form_default_application'              => 'Number',
      'esl_from_name'                         => 'Text',
      'esl_from_email_address'                => 'Text',
      'esl_subject'                           => 'Text',
      'esl_content'                           => 'Text',
      'esl_plain_text'                        => 'Number',
      'esr_email_address'                     => 'Text',
      'esr_from_name'                         => 'Text',
      'esr_from_email_address'                => 'Text',
      'esr_subject'                           => 'Text',
      'esr_content'                           => 'Text',
      'esr_plain_text'                        => 'Number',
      'form_tags'                             => 'Text',
      'form_redirect_enable'                  => 'Number',
      'form_unique_ip_maxcount'               => 'Number',
      'form_unique_ip_period'                 => 'Number',
      'form_captcha_type'                     => 'Text',
      'form_theme_id'                         => 'Number',
      'form_resume_enable'                    => 'Number',
      'form_resume_subject'                   => 'Text',
      'form_resume_content'                   => 'Text',
      'form_resume_from_name'                 => 'Text',
      'form_resume_from_email_address'        => 'Text',
      'form_custom_script_enable'             => 'Number',
      'form_custom_script_url'                => 'Text',
      'form_limit_enable'                     => 'Number',
      'form_limit'                            => 'Number',
      'form_label_alignment'                  => 'Text',
      'form_language'                         => 'Text',
      'form_page_total'                       => 'Number',
      'form_lastpage_title'                   => 'Text',
      'form_submit_primary_text'              => 'Text',
      'form_submit_secondary_text'            => 'Text',
      'form_submit_primary_img'               => 'Text',
      'form_submit_secondary_img'             => 'Text',
      'form_submit_use_image'                 => 'Number',
      'form_review_primary_text'              => 'Text',
      'form_review_secondary_text'            => 'Text',
      'form_review_primary_img'               => 'Text',
      'form_review_secondary_img'             => 'Text',
      'form_review_use_image'                 => 'Number',
      'form_review_title'                     => 'Text',
      'form_review_description'               => 'Text',
      'form_pagination_type'                  => 'Text',
      'form_schedule_enable'                  => 'Number',
      'form_schedule_start_date'              => 'Date',
      'form_schedule_end_date'                => 'Date',
      'form_schedule_start_hour'              => 'Text',
      'form_schedule_end_hour'                => 'Text',
      'esl_enable'                            => 'Number',
      'esr_enable'                            => 'Number',
      'payment_enable_merchant'               => 'Number',
      'payment_merchant_type'                 => 'Text',
      'payment_paypal_email'                  => 'Text',
      'payment_paypal_language'               => 'Text',
      'payment_currency'                      => 'Text',
      'payment_show_total'                    => 'Number',
      'payment_total_location'                => 'Text',
      'payment_enable_recurring'              => 'Number',
      'payment_recurring_cycle'               => 'Number',
      'payment_recurring_unit'                => 'Text',
      'payment_price_type'                    => 'Text',
      'payment_price_amount'                  => 'Number',
      'payment_price_name'                    => 'Text',
      'payment_enable_discount'               => 'Number',
      'logic_field_enable'                    => 'Number',
      'logic_page_enable'                     => 'Number',
      'payment_enable_trial'                  => 'Number',
      'payment_trial_period'                  => 'Number',
      'payment_trial_unit'                    => 'Text',
      'payment_trial_amount'                  => 'Number',
      'payment_pesapal_live_secret_key'       => 'Text',
      'payment_pesapal_live_public_key'       => 'Text',
      'payment_pesapal_test_secret_key'       => 'Text',
      'payment_pesapal_test_public_key'       => 'Text',
      'payment_pesapal_enable_test_mode'      => 'Number',
      'payment_paypal_enable_test_mode'       => 'Number',
      'payment_enable_invoice'                => 'Number',
      'payment_invoice_email'                 => 'Text',
      'payment_delay_notifications'           => 'Number',
      'payment_ask_billing'                   => 'Number',
      'payment_ask_shipping'                  => 'Number',
      'payment_discount_element_id'           => 'Number',
      'form_disabled_message'                 => 'Text',
      'payment_enable_tax'                    => 'Number',
      'payment_tax_rate'                      => 'Number',
      'payment_tax_amount'                    => 'Number',
      'payment_discount_code'                 => 'Number',
      'webhook_enable'                        => 'Number',
      'payment_discount_type'                 => 'Number',
      'payment_discount_amount'               => 'Number',
      'logic_email_enable'                    => 'Number',
      'form_stage'                            => 'Text',
      'form_group'                            => 'Number',
      'form_department'                       => 'Number',
      'form_department_stage'                 => 'Number',
      'form_idn'                              => 'Text',
      'form_type'                             => 'Number',
      'form_code'                             => 'Text',
      'payment_cellulant_checkout_url'        => 'Text',
      'payment_cellulant_merchant_username'   => 'Text',
      'payment_cellulant_merchant_password'   => 'Text',
      'payment_cellulant_service_id'          => 'Text',
      'payment_jambopay_business'             => 'Text',
      'payment_jambopay_shared_key'           => 'Text',
      'logic_webhook_enable'                  => 'Number',
      'logic_success_enable'                  => 'Number',
      'esl_bcc_email_address'                 => 'Text',
      'esl_replyto_email_address'             => 'Text',
      'esl_pdf_enable'                        => 'Number',
      'esl_pdf_content'                       => 'Text',
      'esr_bcc_email_address'                 => 'Text',
      'esr_replyto_email_address'             => 'Text',
      'esr_pdf_enable'                        => 'Number',
      'esr_pdf_content'                       => 'Text',
      'payment_enable_setupfee'               => 'Number',
      'payment_setupfee_amount'               => 'Number',
      'payment_stripe_live_secret_key'        => 'Text',
      'payment_stripe_live_public_key'        => 'Text',
      'payment_stripe_test_secret_key'        => 'Text',
      'payment_stripe_test_public_key'        => 'Text',
      'payment_stripe_enable_test_mode'       => 'Number',
      'payment_stripe_enable_receipt'         => 'Number',
      'payment_stripe_receipt_element_id'     => 'Number',
      'payment_authorizenet_live_apiloginid'  => 'Text',
      'payment_authorizenet_live_transkey'    => 'Text',
      'payment_authorizenet_test_apiloginid'  => 'Text',
      'payment_authorizenet_test_transkey'    => 'Text',
      'payment_authorizenet_enable_test_mode' => 'Number',
      'payment_authorizenet_save_cc_data'     => 'Number',
      'payment_braintree_live_merchant_id'    => 'Text',
      'payment_braintree_live_public_key'     => 'Text',
      'payment_braintree_live_private_key'    => 'Text',
      'payment_braintree_live_encryption_key' => 'Text',
      'payment_braintree_test_merchant_id'    => 'Text',
      'payment_braintree_test_public_key'     => 'Text',
      'payment_braintree_test_private_key'    => 'Text',
      'payment_braintree_test_encryption_key' => 'Text',
      'payment_braintree_enable_test_mode'    => 'Number',
      'payment_paypal_rest_live_clientid'     => 'Text',
      'payment_paypal_rest_live_secret_key'   => 'Text',
      'payment_paypal_rest_test_clientid'     => 'Text',
      'payment_paypal_rest_test_secret_key'   => 'Text',
      'payment_paypal_rest_enable_test_mode'  => 'Number',
      'payment_discount_max_usage'            => 'Number',
      'payment_discount_expiry_date'          => 'Text',
    );
  }
}
