<?php

/**
 * ApElementOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApElementOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApElementOptionsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApElementOptions');
    }
	public function getElementOptions($form_id,$element_id)
	{
		$q=$this->createQuery('e')
		->select('e.*')
		->where('e.form_id =? AND e.element_id = ?',array($form_id,$element_id));
		$elements=$q->fetchArray();
		$element_array=array(0 => '');
		foreach($elements as $e){
			$element_array[$e['option_id']]=$e['option_text'];
		}
		return $element_array;		
	}
	public function getElementOptionsValue($form_id,$element_id,$option_id)
	{
		error_log('------Form id------'.$form_id.'--------ELEMENT ID-----'.$element_id.'-------Option id----'.$option_id);
		$q=$this->createQuery('e')
		->where('e.form_id =? AND e.element_id = ? AND option_id = ?',array($form_id,$element_id,$option_id));
		$element=$q->fetchOne();
		//OTB FIX return if element exist
		if($element){
			if(strlen($element->getOptionText())){
				return $element->getOptionText();
			}else{
				return $element->getOption();
			}
		}
	}
}