<?php

/**
 * ApElementPricesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApElementPricesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApElementPricesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApElementPrices');
    }
}