<?php

/**
 * ApFieldLogicConditionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApFieldLogicConditionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApFieldLogicConditionsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApFieldLogicConditions');
    }
}