<?php

/**
 * ApFormSortsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApFormSortsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApFormSortsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApFormSorts');
    }
}