<?php

/**
 * ApFormPayments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ApFormPayments extends BaseApFormPayments
{
	public function paymentstatus()
	{
		switch($this->getStatus()){
			case 15:
				return "pending";
				break;
			case 2:
				return "paid";
				break;
			case 1:
				return "failed";
				break;
			case 3:
				return "part";
				break;
		}
	}
}
