<?php

/**
 * ApFormPaymentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApFormPaymentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApFormPaymentsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApFormPayments');
    }
}