<?php

/**
 * ApiContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ApiContent extends BaseApiContent
{
	public function getApiusedesc()
	{
		$api_uses=Doctrine_Core::getTable('ApiContent')->getApiuses();
		return $api_uses[$this->getApiUse()];
	}
}
