<?php

/**
 * ApplicationNumberHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationNumberHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApplicationNumberHistoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicationNumberHistory');
    }
}