<?php

/**
 * ApSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApSettingsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApSettings');
    }
}