<?php

/**
 * ApSuccessLogicConditionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApSuccessLogicConditionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApSuccessLogicConditionsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApSuccessLogicConditions');
    }
}