<?php

/**
 * ApSuccessLogicOptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApSuccessLogicOptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApSuccessLogicOptionsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApSuccessLogicOptions');
    }
}