<?php

/**
 * ApUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApUsersTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApUsers');
    }
}