<?php

/**
 * ApWorkflowLogicElementsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApWorkflowLogicElementsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApWorkflowLogicElementsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApWorkflowLogicElements');
    }
}