<?php

/**
 * AuditTrailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuditTrailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return AuditTrailTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuditTrail');
    }
}