<?php

/**
 * CartItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CartItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return CartItemTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CartItem');
    }
}