<?php

/**
 * CfUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CfUser extends BaseCfUser
{
	public function __toString()
	{
		return $this->getStrfirstname()." ".$this->getStrlastname(). " (".$this->getStruserid().")";
	}

	public function getDepartment()
	{
		$q = Doctrine_Query::create()
			->from("Department a")
			->where("a.id = ?", $this->getStrdepartment());
		$department = $q->fetchOne();

		if($department)
		{
			return $department->getDepartmentName();
		}
		else
		{
			return "";
		}
	}

	public function confirmCredential($credential)
	{
		$q = Doctrine_Query::create()
			->from('mfGuardUserGroup a')
			->leftJoin('a.MfGuardGroup b')
			->leftJoin('b.MfGuardGroupPermission c') //Left Join group permissions
			->leftJoin('c.MfGuardPermission d') //Left Join permissions
			->where('a.user_id = ?', parent::_get("nid"))
			->andWhere('d.name = ?', $credential);
		$usergroups = $q->execute();
		if(sizeof($usergroups) > 0)
		{
			return TRUE;
		}
		else
		{
			return FALSE;
		}
	}
}
