<?php

/**
 * ChecksumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChecksumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ChecksumTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Checksum');
    }
}