<?php

/**
 * Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Content extends BaseContent
{
    public function save(Doctrine_Connection $conn = null)
    {
		if(!$this->getMenuIndex()){
			$this->setMenuIndex($this->getId());
		}
		if($this->getPublished()){
			$this->setVisibility($this->getPublished());
		}
        parent::save($conn);

        $translation = new Translation();
        $translation->setTranslation('content','menu_title',parent::_get("id"), parent::_get("menu_title"));

        $translation = new Translation();
        $translation->setTranslation('content','top_article',parent::_get("id"), parent::_get("top_article"));
    }

    public function getMenuTitle()
	{
		$translation = new Translation();
		if($translation->getTranslation('content','menu_title',$this->getId()))
        {
          	return $translation->getTranslation('content','menu_title',$this->getId());
        }
        else
        {
        	return parent::_get("menu_title");
        }
	}

	public function getTopArticle()
	{
		$translation = new Translation();
		if($translation->getTranslation('content','top_article',$this->getId()))
        {
          	return $translation->getTranslation('content','top_article',$this->getId());
        }
        else
        {
        	return parent::_get("top_article");
        }
	}
}
