<?php

/**
 * ContentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ContentTypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentType');
    }
}