<?php

/**
 * ExtLocalesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtLocalesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ExtLocalesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtLocales');
    }
}