<?php

/**
 * Fee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fee extends BaseFee
{
    public function save(Doctrine_Connection $conn = null)
    {
		if(!$this->getMinimumFee()){
			$this->setMinimumFee(0);
		}
        parent::save($conn);

        $translation = new Translation();
        $translation->setTranslation('fee','description',parent::_get("id"), parent::_get("description"));
    }
	public function getTitle()
	{
		$translation = new Translation();
		if($translation->getTranslation('fee','description',$this->getId()) && $translation->getTranslation('fee','description',$this->getId()) != "")
        {
          	return $translation->getTranslation('fee','description',$this->getId());
        }
        else
        {
        	return parent::_get("description");
        }
	}
}
