<?php

/**
 * FeeCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeeCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FeeCategoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeeCategory');
    }

    public static function getCategories()
    {
        $categories = array();

        $categories[] = "";

        $q = Doctrine_Query::create()
           ->from("FeeCategory a")
           ->orderBy("a.title ASC");
        $fee_categories = $q->execute();

        foreach($fee_categories as $fee_category)
        {
            $categories[$fee_category->getId()] =  $fee_category->getTitle();
        }

        return $categories;
    }
}