<?php

/**
 * FeeRangeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeeRangeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeeRangeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeeRange');
    }
}