<?php

/**
 * MenusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MenusTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menus');
    }
	public function getAllAgendastages()
	{
		$q=$this->createQuery('m')
			->select('m.title,s.title')
			->leftJoin('m.SubMenus s')
			->where('s.deleted = ? AND s.stage_type= ?',array(0,11));
		$stages=$q->fetchArray();
		$menu_stage_array=array(0 => ' ');
		foreach($stages as $s){
			$submenus=array();
			foreach($s['SubMenus'] as $d){
				$submenus[$d['id']]=$d['title'];
			}
			$menu_stage_array[$s['title']]=$submenus;
		}
		return $menu_stage_array;
	}
	//OTB ADD
	public function getStages()
	{
		$menus=$this->createQuery('m')->innerJoin('m.SubMenus s')->where('s.deleted = 0')->fetchArray();
		$sub_menu_array=array(0 => '');
		foreach($menus as $menu){
			$sub_menus=array();
			foreach($menu['SubMenus'] as $submenu){
				$sub_menus[$submenu['id']]=$submenu['title'];
			}
			$sub_menu_array[$menu['title']]=$sub_menus;
		}
		return $sub_menu_array;
	}
}