<?php

/**
 * Currencies 
 * //OTB patch - For Currency Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    permit
 * @subpackage model
 * @author     boniface@otbafrica.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z Boniface Irungu $
 */
class Merchant extends BaseMerchant
{
 //to string method return name of merchant
   public function __toString()
   {
	   //parent::toString();
	   return $this->getName();
   }
}
