<?php

/**
 * MfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MfGuardGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MfGuardGroupTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MfGuardGroup');
    }
}