<?php

/**
 * MfInvoiceArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MfInvoiceArchiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MfInvoiceArchiveTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MfInvoiceArchive');
    }
}