<?php

/**
 * MfUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MfUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MfUserProfileTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MfUserProfile');
    }
}