<?php

/**
 * MfUserProfileInspectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MfUserProfileInspectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MfUserProfileInspectionTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MfUserProfileInspection');
    }
}