<?php

/**
 * MfUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MfUserProfileShareTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MfUserProfileShareTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MfUserProfileShare');
    }
}