<?php

/**
 * MfUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MfUserProfile extends BaseMfUserProfile
{
    /**
	* Get title of the application
	*
	* Get either the application number or a field from the form if configured
	*
	* @return String
	*/
	public function getTitle()
	{
		$q = Doctrine_Query::create()
		   ->from("ApColumnPreferences a")
		   ->where("a.form_id = ?", $this->getFormId());
		
		if($q->count() == 0)
		{
			return $this->getCreatedAt()." - Please select a preffered column";
		}
		else 
		{
			$prefix_folder = dirname(__FILE__)."/../../vendor/form_builder/";
			require_once($prefix_folder.'includes/init.php');

			require_once($prefix_folder.'../../../config/form_builder_config.php');
			require_once($prefix_folder.'includes/db-core.php');
			require_once($prefix_folder.'includes/helper-functions.php');

			$dbh = mf_connect_db();
			$mf_settings = mf_get_settings($dbh);
			
			$column_settings = $q->execute();

			$name = "";
			
			foreach($column_settings as $column_setting)
			{
				$element_name = $column_setting->getElementName();

				$sql = "SELECT * FROM ap_form_".$this->getFormId()." WHERE id = ?";
				$params = array($this->getEntryId());
				$sth = mf_do_query($sql,$params,$dbh);

				while($form_data = mf_do_fetch_result($sth))
				{
					$name .= strtoupper($form_data[$element_name])." ";
				}
			}

			if($name)
			{
				return $name;
			}
			else 
			{
				return $this->getApplicationId();
			}
		}
	}

	/**
	*
	* Execute Triggers on Updating a Business
	*
	**/
	public function save(Doctrine_Connection $conn = null)
	{
		if($this->getDeleted() == 0)
		{
			//Delete any unpaid invoices and run the cyclic billing service again
			$q = Doctrine_Query::create()
			   ->from("MfInvoice a")
			   ->leftJoin("a.FormEntry b")
			   ->where("b.business_id = ?", $this->getId())
			   ->andWhere("a.paid = 1");
			$invoices = $q->execute();

			foreach($invoices as $invoice)
			{
				$invoice->delete();
			}

			$profile = parent::save($conn);

			$business_manager = new BusinessManager();

			try
			{
				$business_manager->generate_cyclic_bills($this->getId());
			}catch(Exception $ex)
			{
				error_log("Permitflow: ".$ex->getMessage());
			}

			return $profile;
		}
		else
		{
			return parent::save($conn);
		}
	}
}
