<?php

/**
 * PenaltyTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PenaltyTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PenaltyTemplateTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PenaltyTemplate');
    }
}