<?php

/**
 * PermitCheckerConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermitCheckerConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PermitCheckerConfigTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PermitCheckerConfig');
    }
}