<?php

/**
 * PlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plot');
    }
}