<?php

/**
 * SavedPermit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SavedPermit extends BaseSavedPermit
{
    public function save(Doctrine_Connection $conn = null)
	{
        $permit_manager = new PermitManager();

        //Retrieve permit template
        $q = Doctrine_Query::create()
                ->from("Permits a")
                ->where("a.id = ?", $this->getTypeId());
        $template = $q->fetchOne();
        // permits that do not require signing should stay activated
        if(!$template->getAllowsSigning()){
            $this->setIsActivated(1);
        }
        //Set created_by to 0 coz some mysql databases give a null error despite null being set in the database
        //FYI created_by can be null because permits can be auto generated without human intervention
        $this->setCreatedBy(0);
		//OTB ADD - Check invoices to know issue year
		$issue_year=date('Y');
		if($template->getAllowIssueLastPaid()){
			$issue_year=$permit_manager->get_year_of_issue($this->getApplicationId());
			error_log('---------Year----'.$issue_year);
		}
        //Possible Scenarios
        //1. Update expiry date of the permit if set in template and not set in permit
        if($template && (($template->getMaxDuration() && $template->getExpirationType() == 1) || $template->getExpirationType() != 1) && empty($this->getDateOfExpiry()))
        {
            $max_duration = $template->getMaxDuration();

            if($max_duration > 0 && $template->getExpirationType() == 1)
            {
                    //If permit expires after a specified number of days then update the expiry of the permit
                    $date = strtotime("+".$max_duration." day");
                    $expiry_date = date($issue_year.'-m-d', $date);

                    $this->setDateOfExpiry($expiry_date);
            }
            else if($template->getExpirationType() == 2)
            {
                $expiry_date = date($issue_year.'-m-t');

                $this->setDateOfExpiry($expiry_date);
            }
            else if($template->getExpirationType() == 3)
            {
                $expiry_date = date($issue_year.'-12-31');

                $this->setDateOfExpiry($expiry_date);
            }
            elseif($template->getMaxDuration() == 0) //Let the permit expire today :Testing scenario
            {
                $this->setDateOfExpiry(date($issue_year."-m-d 00:00:00"));
            }
            else {
                    //If the date of expiry is less than the max duration from the day the permit was created then update the expiry date of the permit
                    $date_created = $this->getDateOfIssue();
                    $date_of_expiry = $this->getDateOfExpiry();

                    //Get number of days between expiry and the date the permit was generated
                    $days_to_expiry = floor((strtotime($date_of_expiry) - strtotime($date_created))/(60*60*24));

                    //If not equal then update the expiry date
                    if(($days_to_expiry+5) < $max_duration)
                    {
                        $new_expiry = date('Y-m-d', strtotime("+".$max_duration." day"));
                        $this->setDateOfExpiry($new_expiry);

                        //Update UUID since data change is needed
                        $uuid = $permit_manager->generate_uuid();
                        $this->setRemoteUpdateUuid($uuid);
                    }
            }
        }

        //2. Set UUID for permit
        if(empty($this->getRemoteUpdateUuid()))
        {
            $uuid = $permit_manager->generate_uuid();
            $this->setRemoteUpdateUuid($uuid);
        }

        //3. Push remote data to remote server if configured in template
        // Note: You must save the permit first so that the actual record exists in the database e.g. an actual permit number is generated and sent remotely
        $result = parent::save($conn);

        //The update manager class will check if there is a need to push data.
        $updates_manager = new UpdatesManager();

        if($this->getExpiryTrigger() != 1)
        {
            //Push info to a remote server if configured
            if($updates_manager->needs_push($this->getId()))
            {
                $updates_manager->push_update($this->getId());
            }
        }
        Functions::create_signing_task_if_needed($this);
		return $result;
    }
    
    public function getPermitStatusDesc()
    {
        if($this->getPermitStatus()){
            return 'Valid';
        }else{
            return 'Invalid';
        }
    }
    public function getFileName()
    {
        $file_name = str_replace('/', '-', $this->getFormEntry()->getApplicationId()) . '-' . $this->getId();
        return "$file_name.pdf";
    }
    public function isSigned()
    {
        $file_path = $this->getSignedFilePath();
        $file_exists = file_exists($file_path);

        # let know who signed it
        if (!$file_exists and $this->getSignedBy()) {
            $this->setSignedBy(null);
            $this->save();
            return false;
        }

        return $file_exists;
    }

    public function getSignedFilePath()
    {
        $signed_files_store = sfConfig::get('app_docusign_signed_files_store', 'app/permits/signed/');
        return $signed_files_store . $this->getFileName();
    }

    public function getUnSignedFilePath()
    {
        $unsined_file_path = sfConfig::get('app_docusign_un_signed_files_store', 'app/permits/unsigned/') . $this->getFileName();
        if (!file_exists($unsined_file_path)) {
            # save the pdf first
            $permit_manager = new PermitManager();
            $output = $permit_manager->get_pdf_output($this->getId());
            $file = fopen($unsined_file_path, 'w');
            fwrite($file, $output);
            fclose($file);
        }
        return $unsined_file_path;
    }
    public function getApplication()
    {
        if ($app = Doctrine_Query::create()
            ->from('FormEntry a ')
            ->where('id = ?', $this->getApplicationId())
            ->fetchOne()) {
            return $app;
        }

        return null;
    }

    public function getTaskSlug()
    {
        return 'sign-permit-' . $this->getId();
    }

    public function isSignable()
    {
        return Doctrine_Query::create()
            ->from('Permits a')
            ->where('a.id = ? and allows_signing = 1', $this->getTypeId())
            ->fetchOne();
    }

    public function getTemplate(){
        return Doctrine_Core::getTable('Permits')->find($this->getTypeId());
    }
}
