<?php

/**
 * ServiceFeesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceFeesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ServiceFeesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceFees');
    }
}