<?php

/**
 * SfGuardUserCategoriesFormsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserCategoriesFormsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return SfGuardUserCategoriesFormsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserCategoriesForms');
    }
}