<?php

/**
 * SfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return SfGuardUserTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUser');
    }
}