<?php

/**
 * SubMenuButtonsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubMenuButtonsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return SubMenuButtonsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubMenuButtons');
    }
}