<?php

/**
 * WorkflowReviewersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowReviewersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return WorkflowReviewersTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkflowReviewers');
    }
}