<?php

/**
 * ApFieldRelationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApFieldRelationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApFieldRelationsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApFieldRelations');
    }
}