<?php

/**
 * ApFormGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApFormGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApFormGroupsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApFormGroups');
    }
}