<?php

/**
 * ApReportElementsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApReportElementsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ApReportElementsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApReportElements');
    }
}