<?php

/**
 * ConditionsOfApprovalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConditionsOfApprovalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ConditionsOfApprovalTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConditionsOfApproval');
    }
}