<?php

/**
 * FavoritesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FavoritesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FavoritesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Favorites');
    }
}