<?php

/**
 * FormEntryArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormEntryArchiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FormEntryArchiveTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormEntryArchive');
    }
}