<?php

/**
 * FormEntrySharesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormEntrySharesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FormEntrySharesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormEntryShares');
    }
}