<?php

/**
 * MfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MfGuardGroup extends BaseMfGuardGroup
{
    public function save(Doctrine_Connection $conn = null)
	{
		parent::save($conn);

		$translation = new Translation();
		$translation->setTranslation('mf_guard_group','name',parent::_get("id"), parent::_get("name"));

		$translation = new Translation();
		$translation->setTranslation('mf_guard_group','description',parent::_get("id"), parent::_get("description"));
	}

	public function getName()
	{
		$translation = new Translation();
		if($translation->getTranslation('mf_guard_group','name',$this->getId()))
        {
          	return $translation->getTranslation('mf_guard_group','name',$this->getId());
        }
        else
        {
        	return parent::_get("name");
        }
	}

	public function getDescription()
	{
		$translation = new Translation();
		if($translation->getTranslation('mf_guard_group','description',$this->getId()))
        {
          	return $translation->getTranslation('mf_guard_group','description',$this->getId());
        }
        else
        {
        	return parent::_get("description");
        }
	}
}
