<?php

/**
 * MfGuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MfGuardUserGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MfGuardUserGroupTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MfGuardUserGroup');
    }
}