<?php

/**
 * Permits
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Permits extends BasePermits
{
    public function save(Doctrine_Connection $conn = null)
    {
        parent::save($conn);

        $translation = new Translation();
        $translation->setTranslation('permits','title',parent::_get("id"), parent::_get("title"));
        $translation->setTranslation('permits','content',parent::_get("id"), parent::_get("content"));
    }
	public function getTitle()
	{
		$translation = new Translation();
		if($translation->getTranslation('permits','title',$this->getId()) && $translation->getTranslation('permits','title',$this->getId()) != "")
        {
          	return $translation->getTranslation('permits','title',$this->getId());
        }
        else
        {
        	return parent::_get("title");
        }
	}
	public function getContent()
	{
		$translation = new Translation();
		if($translation->getTranslation('permits','content',$this->getId()) && $translation->getTranslation('permits','content',$this->getId()) != "")
        {
          	return $translation->getTranslation('permits','content',$this->getId());
        }
        else
        {
        	return parent::_get("content");
        }
	}
}
