<?php

/**
 * SavedPermitArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SavedPermitArchiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return SavedPermitArchiveTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SavedPermitArchive');
    }
}