<?php

/**
 * TaskCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return TaskCommentsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskComments');
    }
}