<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SavedPermit', 'doctrine');

/**
 * BaseSavedPermit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                              Type: integer(4), primary key
 * @property int          $type_id                         Type: integer(4)
 * @property int          $application_id                  Type: integer(4)
 * @property string       $date_of_issue                   Type: string(250)
 * @property string       $date_of_expiry                  Type: string(250)
 * @property int          $created_by                      Type: integer(4)
 * @property string       $last_updated                    Type: string(250)
 * @property string       $permit_id                       Type: string(250)
 * @property string       $document_key                    Type: string(250)
 * @property string       $remote_result                   Type: string
 * @property int          $permit_status                   Type: integer(4), default "1"
 * @property string       $remote_update_uuid              Type: string
 * @property string       $pdf_path                        Type: string(255)
 * @property int          $sent                            Type: integer(4), default "0"
 * @property int          $expiry_trigger                  Type: integer(4), default "0"
 * @property FormEntry    $FormEntry                       
 *  
 * @method int            getId()                          Type: integer(4), primary key
 * @method int            getTypeId()                      Type: integer(4)
 * @method int            getApplicationId()               Type: integer(4)
 * @method string         getDateOfIssue()                 Type: string(250)
 * @method string         getDateOfExpiry()                Type: string(250)
 * @method int            getCreatedBy()                   Type: integer(4)
 * @method string         getLastUpdated()                 Type: string(250)
 * @method string         getPermitId()                    Type: string(250)
 * @method string         getDocumentKey()                 Type: string(250)
 * @method string         getRemoteResult()                Type: string
 * @method int            getPermitStatus()                Type: integer(4), default "1"
 * @method string         getRemoteUpdateUuid()            Type: string
 * @method string         getPdfPath()                     Type: string(255)
 * @method int            getSent()                        Type: integer(4), default "0"
 * @method int            getExpiryTrigger()               Type: integer(4), default "0"
 * @method FormEntry      getFormEntry()                   
 *  
 * @method SavedPermit    setId(int $val)                  Type: integer(4), primary key
 * @method SavedPermit    setTypeId(int $val)              Type: integer(4)
 * @method SavedPermit    setApplicationId(int $val)       Type: integer(4)
 * @method SavedPermit    setDateOfIssue(string $val)      Type: string(250)
 * @method SavedPermit    setDateOfExpiry(string $val)     Type: string(250)
 * @method SavedPermit    setCreatedBy(int $val)           Type: integer(4)
 * @method SavedPermit    setLastUpdated(string $val)      Type: string(250)
 * @method SavedPermit    setPermitId(string $val)         Type: string(250)
 * @method SavedPermit    setDocumentKey(string $val)      Type: string(250)
 * @method SavedPermit    setRemoteResult(string $val)     Type: string
 * @method SavedPermit    setPermitStatus(int $val)        Type: integer(4), default "1"
 * @method SavedPermit    setRemoteUpdateUuid(string $val) Type: string
 * @method SavedPermit    setPdfPath(string $val)          Type: string(255)
 * @method SavedPermit    setSent(int $val)                Type: integer(4), default "0"
 * @method SavedPermit    setExpiryTrigger(int $val)       Type: integer(4), default "0"
 * @method SavedPermit    setFormEntry(FormEntry $val)     
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSavedPermit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('saved_permit');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_of_issue', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('date_of_expiry', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('last_updated', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('permit_id', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('document_key', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('remote_result', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('permit_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('remote_update_uuid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pdf_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('expiry_trigger', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
          $this->hasColumn('is_activated', 'string', 255, array(
          'type' => 'string',
          'fixed' => 0,
          'unsigned' => false,
          'primary' => false,
          'notnull' => false,
          'autoincrement' => false,
          'length' => 255,
          ));
          $this->hasColumn('signed_by', 'integer', 4, array(
               'type' => 'integer',
               'unsigned' => false,
               'primary' => false,
               'default' => null,
               'autoincrement' => false,
               'length' => 4,
           ));
     }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FormEntry', array(
             'local' => 'application_id',
             'foreign' => 'id'));

        $this->hasOne('Permits as Template', array(
             'local' => 'type_id',
             'foreign' => 'id'));
    }
}