<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Department', 'doctrine');

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int         $id                            Type: integer(4), primary key
 * @property string      $department_name               Type: string(255)
 * @property int         $department_head               Type: integer(8)
 *  
 * @method int           getId()                        Type: integer(4), primary key
 * @method string        getDepartmentName()            Type: string(255)
 * @method int           getDepartmentHead()            Type: integer(8)
 *  
 * @method Department    setId(int $val)                Type: integer(4), primary key
 * @method Department    setDepartmentName(string $val) Type: string(255)
 * @method Department    setDepartmentHead(int $val)    Type: integer(8)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('department_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('department_head', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();

        $this->hasMany('CfUser as Users', array(
             'local' => 'id',
             'foreign' => 'strdepartment'));
 		//OTB Start - Multi Agency Implementation
        $this->hasMany('AgencyDepartment', array(
             'local' => 'id',
             'foreign' => 'department_id'));
		//OTB End - Multi Agency Implementation       
        
    }
}