<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormEntryShares', 'doctrine');

/**
 * BaseFormEntryShares
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int              $id                      Type: integer(4), primary key
 * @property int              $senderid                Type: integer(4)
 * @property int              $receiverid              Type: integer(4)
 * @property int              $formentryid             Type: integer(4)
 *  
 * @method int                getId()                  Type: integer(4), primary key
 * @method int                getSenderid()            Type: integer(4)
 * @method int                getReceiverid()          Type: integer(4)
 * @method int                getFormentryid()         Type: integer(4)
 *  
 * @method FormEntryShares    setId(int $val)          Type: integer(4), primary key
 * @method FormEntryShares    setSenderid(int $val)    Type: integer(4)
 * @method FormEntryShares    setReceiverid(int $val)  Type: integer(4)
 * @method FormEntryShares    setFormentryid(int $val) Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormEntryShares extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('form_entry_shares');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('senderid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('receiverid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('formentryid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        /** form entry shared by */
        $this->hasColumn('shared_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 256,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
         $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}