<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApUsers', 'doctrine');

/**
 * BaseApUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int      $user_id                      Type: integer(4), primary key
 * @property string   $user_email                   Type: string(255)
 * @property string   $user_password                Type: string(255)
 * @property string   $user_fullname                Type: string(255)
 * @property int      $priv_administer              Type: integer(1), default "0"
 * @property int      $priv_new_forms               Type: integer(1), default "0"
 * @property int      $priv_new_themes              Type: integer(1), default "0"
 * @property string   $last_login_date              Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string   $last_ip_address              Type: string(15)
 * @property string   $cookie_hash                  Type: string(255)
 * @property int      $status                       Type: integer(1), default "1"
 *  
 * @method int        getUserId()                   Type: integer(4), primary key
 * @method string     getUserEmail()                Type: string(255)
 * @method string     getUserPassword()             Type: string(255)
 * @method string     getUserFullname()             Type: string(255)
 * @method int        getPrivAdminister()           Type: integer(1), default "0"
 * @method int        getPrivNewForms()             Type: integer(1), default "0"
 * @method int        getPrivNewThemes()            Type: integer(1), default "0"
 * @method string     getLastLoginDate()            Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string     getLastIpAddress()            Type: string(15)
 * @method string     getCookieHash()               Type: string(255)
 * @method int        getStatus()                   Type: integer(1), default "1"
 *  
 * @method ApUsers    setUserId(int $val)           Type: integer(4), primary key
 * @method ApUsers    setUserEmail(string $val)     Type: string(255)
 * @method ApUsers    setUserPassword(string $val)  Type: string(255)
 * @method ApUsers    setUserFullname(string $val)  Type: string(255)
 * @method ApUsers    setPrivAdminister(int $val)   Type: integer(1), default "0"
 * @method ApUsers    setPrivNewForms(int $val)     Type: integer(1), default "0"
 * @method ApUsers    setPrivNewThemes(int $val)    Type: integer(1), default "0"
 * @method ApUsers    setLastLoginDate(string $val) Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method ApUsers    setLastIpAddress(string $val) Type: string(15)
 * @method ApUsers    setCookieHash(string $val)    Type: string(255)
 * @method ApUsers    setStatus(int $val)           Type: integer(1), default "1"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_users');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_fullname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('priv_administer', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('priv_new_forms', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('priv_new_themes', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('last_login_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('last_ip_address', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('cookie_hash', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}