<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NotificationHistory', 'doctrine');

/**
 * BaseNotificationHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                  $id                              Type: integer(8), primary key
 * @property int                  $user_id                         Type: integer(4)
 * @property string               $notification                    Type: string
 * @property string               $notification_type               Type: string(250)
 * @property string               $sent_on                         Type: string(250)
 * @property int                  $confirmed_receipt               Type: integer(4), default "0"
 * @property int                  $application_id                  Type: integer(4)
 *  
 * @method int                    getId()                          Type: integer(8), primary key
 * @method int                    getUserId()                      Type: integer(4)
 * @method string                 getNotification()                Type: string
 * @method string                 getNotificationType()            Type: string(250)
 * @method string                 getSentOn()                      Type: string(250)
 * @method int                    getConfirmedReceipt()            Type: integer(4), default "0"
 * @method int                    getApplicationId()               Type: integer(4)
 *  
 * @method NotificationHistory    setId(int $val)                  Type: integer(8), primary key
 * @method NotificationHistory    setUserId(int $val)              Type: integer(4)
 * @method NotificationHistory    setNotification(string $val)     Type: string
 * @method NotificationHistory    setNotificationType(string $val) Type: string(250)
 * @method NotificationHistory    setSentOn(string $val)           Type: string(250)
 * @method NotificationHistory    setConfirmedReceipt(int $val)    Type: integer(4), default "0"
 * @method NotificationHistory    setApplicationId(int $val)       Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotificationHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification_history');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('notification', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('notification_type', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('sent_on', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('confirmed_receipt', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}