<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MfGuardGroup', 'doctrine');

/**
 * BaseMfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                           $id                                                 Type: integer(8), primary key
 * @property string                                        $name                                               Type: string(255)
 * @property string                                        $description                                        Type: string
 * @property Doctrine_Collection|MfGuardGroupPermission[]  $MfGuardGroupPermission                             
 * @property Doctrine_Collection|CfUser[]                  $Users                                              
 * @property Doctrine_Collection|CfUser[]                  $Group                                              
 * @property Doctrine_Collection|MfGuardUserGroup[]        $MfGuardUserGroup                                   
 *  
 * @method int                                             getId()                                             Type: integer(8), primary key
 * @method string                                          getName()                                           Type: string(255)
 * @method string                                          getDescription()                                    Type: string
 * @method Doctrine_Collection|MfGuardGroupPermission[]    getMfGuardGroupPermission()                         
 * @method Doctrine_Collection|CfUser[]                    getUsers()                                          
 * @method Doctrine_Collection|CfUser[]                    getGroup()                                          
 * @method Doctrine_Collection|MfGuardUserGroup[]          getMfGuardUserGroup()                               
 *  
 * @method MfGuardGroup                                    setId(int $val)                                     Type: integer(8), primary key
 * @method MfGuardGroup                                    setName(string $val)                                Type: string(255)
 * @method MfGuardGroup                                    setDescription(string $val)                         Type: string
 * @method MfGuardGroup                                    setMfGuardGroupPermission(Doctrine_Collection $val) 
 * @method MfGuardGroup                                    setUsers(Doctrine_Collection $val)                  
 * @method MfGuardGroup                                    setGroup(Doctrine_Collection $val)                  
 * @method MfGuardGroup                                    setMfGuardUserGroup(Doctrine_Collection $val)       
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMfGuardGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_guard_group');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MfGuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('MfGuardPermission as Permissions', array(
             'refClass' => 'MfGuardGroupPermission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('CfUser as Users', array(
             'refClass' => 'mfGuardUserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('CfUser as Group', array(
             'refClass' => 'mfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('MfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
}