<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfInputfield', 'doctrine');

/**
 * BaseCfInputfield
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nid
 * @property string $strname
 * @property integer $ntype
 * @property string $strstandardvalue
 * @property integer $breadonly
 * @property string $strbgcolor
 * @property string $commenttype
 * @property string $commentrelation
 * 
 * @method integer      getNid()              Returns the current record's "nid" value
 * @method string       getStrname()          Returns the current record's "strname" value
 * @method integer      getNtype()            Returns the current record's "ntype" value
 * @method string       getStrstandardvalue() Returns the current record's "strstandardvalue" value
 * @method integer      getBreadonly()        Returns the current record's "breadonly" value
 * @method string       getStrbgcolor()       Returns the current record's "strbgcolor" value
 * @method string       getCommenttype()      Returns the current record's "commenttype" value
 * @method string       getCommentrelation()  Returns the current record's "commentrelation" value
 * @method CfInputfield setNid()              Sets the current record's "nid" value
 * @method CfInputfield setStrname()          Sets the current record's "strname" value
 * @method CfInputfield setNtype()            Sets the current record's "ntype" value
 * @method CfInputfield setStrstandardvalue() Sets the current record's "strstandardvalue" value
 * @method CfInputfield setBreadonly()        Sets the current record's "breadonly" value
 * @method CfInputfield setStrbgcolor()       Sets the current record's "strbgcolor" value
 * @method CfInputfield setCommenttype()      Sets the current record's "commenttype" value
 * @method CfInputfield setCommentrelation()  Sets the current record's "commentrelation" value
 * 
 * @package    permit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfInputfield extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_inputfield');
        $this->hasColumn('nid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('strname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ntype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('strstandardvalue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('breadonly', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('strbgcolor', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('commenttype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('commentrelation', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}