<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGuardUser', 'doctrine');

/**
 * BaseSfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int                                          $id                                                Type: integer(8), primary key
 * @property string                                       $first_name                                        Type: string(255)
 * @property string                                       $last_name                                         Type: string(255)
 * @property string                                       $email_address                                     Type: string(255)
 * @property string                                       $username                                          Type: string(128)
 * @property string                                       $algorithm                                         Type: string(128), default "sha1"
 * @property string                                       $salt                                              Type: string(128)
 * @property string                                       $password                                          Type: string(128)
 * @property int                                          $is_active                                         Type: integer(1), default "1"
 * @property int                                          $is_super_admin                                    Type: integer(1), default "0"
 * @property string                                       $last_login                                        Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                                       $created_at                                        Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                                       $updated_at                                        Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property Doctrine_Collection|SfGuardForgotPassword[]  $SfGuardForgotPassword
 * @property Doctrine_Collection|SfGuardRememberKey[]     $SfGuardRememberKey
 * @property Doctrine_Collection|SfGuardUserGroup[]       $SfGuardUserGroup
 * @property Doctrine_Collection|SfGuardUserPermission[]  $SfGuardUserPermission
 *
 * @method int                                            getId()                                            Type: integer(8), primary key
 * @method string                                         getFirstName()                                     Type: string(255)
 * @method string                                         getLastName()                                      Type: string(255)
 * @method string                                         getEmailAddress()                                  Type: string(255)
 * @method string                                         getUsername()                                      Type: string(128)
 * @method string                                         getAlgorithm()                                     Type: string(128), default "sha1"
 * @method string                                         getSalt()                                          Type: string(128)
 * @method string                                         getPassword()                                      Type: string(128)
 * @method int                                            getIsActive()                                      Type: integer(1), default "1"
 * @method int                                            getIsSuperAdmin()                                  Type: integer(1), default "0"
 * @method string                                         getLastLogin()                                     Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                         getCreatedAt()                                     Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                         getUpdatedAt()                                     Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Doctrine_Collection|SfGuardForgotPassword[]    getSfGuardForgotPassword()
 * @method Doctrine_Collection|SfGuardRememberKey[]       getSfGuardRememberKey()
 * @method Doctrine_Collection|SfGuardUserGroup[]         getSfGuardUserGroup()
 * @method Doctrine_Collection|SfGuardUserPermission[]    getSfGuardUserPermission()
 *
 * @method SfGuardUser                                    setId(int $val)                                    Type: integer(8), primary key
 * @method SfGuardUser                                    setFirstName(string $val)                          Type: string(255)
 * @method SfGuardUser                                    setLastName(string $val)                           Type: string(255)
 * @method SfGuardUser                                    setEmailAddress(string $val)                       Type: string(255)
 * @method SfGuardUser                                    setUsername(string $val)                           Type: string(128)
 * @method SfGuardUser                                    setAlgorithm(string $val)                          Type: string(128), default "sha1"
 * @method SfGuardUser                                    setSalt(string $val)                               Type: string(128)
 * @method SfGuardUser                                    setPassword(string $val)                           Type: string(128)
 * @method SfGuardUser                                    setIsActive(int $val)                              Type: integer(1), default "1"
 * @method SfGuardUser                                    setIsSuperAdmin(int $val)                          Type: integer(1), default "0"
 * @method SfGuardUser                                    setLastLogin(string $val)                          Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUser                                    setCreatedAt(string $val)                          Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUser                                    setUpdatedAt(string $val)                          Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUser                                    setSfGuardForgotPassword(Doctrine_Collection $val)
 * @method SfGuardUser                                    setSfGuardRememberKey(Doctrine_Collection $val)
 * @method SfGuardUser                                    setSfGuardUserGroup(Doctrine_Collection $val)
 * @method SfGuardUser                                    setSfGuardUserPermission(Doctrine_Collection $val)
 *
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'sha1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => true,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_super_admin', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('last_login', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => date('Y-m-d'),
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => date('Y-m-d'),
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SfGuardForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardRememberKey', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardUserGroup as groups', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SfGuardUserPermission as permissions', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('SfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('SfGuardUserProfile as Profile', array(
             'local' => 'id',
             'foreign' => 'user_id'));
		$this->hasMany('Communications', array(
			'local' => 'id',
			'foreign' => 'architect_id'
		));
    }
}
