<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApElementPrices', 'doctrine');

/**
 * BaseApElementPrices
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int              $aep_id                Type: integer(4), primary key
 * @property int              $form_id               Type: integer(4)
 * @property int              $element_id            Type: integer(4)
 * @property int              $option_id             Type: integer(4), default "0"
 * @property float            $price                 Type: decimal(62), default "0.00"
 *  
 * @method int                getAepId()             Type: integer(4), primary key
 * @method int                getFormId()            Type: integer(4)
 * @method int                getElementId()         Type: integer(4)
 * @method int                getOptionId()          Type: integer(4), default "0"
 * @method float              getPrice()             Type: decimal(62), default "0.00"
 *  
 * @method ApElementPrices    setAepId(int $val)     Type: integer(4), primary key
 * @method ApElementPrices    setFormId(int $val)    Type: integer(4)
 * @method ApElementPrices    setElementId(int $val) Type: integer(4)
 * @method ApElementPrices    setOptionId(int $val)  Type: integer(4), default "0"
 * @method ApElementPrices    setPrice(float $val)   Type: decimal(62), default "0.00"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApElementPrices extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_element_prices');
        $this->hasColumn('aep_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price', 'decimal', 62, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 62,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}