<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MfGuardGroupPermission', 'doctrine');

/**
 * BaseMfGuardGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                     $group_id                                    Type: integer(8), primary key
 * @property int                     $permission_id                               Type: integer(8), primary key
 * @property MfGuardGroup            $MfGuardGroup                                
 * @property MfGuardPermission       $MfGuardPermission                           
 *  
 * @method int                       getGroupId()                                 Type: integer(8), primary key
 * @method int                       getPermissionId()                            Type: integer(8), primary key
 * @method MfGuardGroup              getMfGuardGroup()                            
 * @method MfGuardPermission         getMfGuardPermission()                       
 *  
 * @method MfGuardGroupPermission    setGroupId(int $val)                         Type: integer(8), primary key
 * @method MfGuardGroupPermission    setPermissionId(int $val)                    Type: integer(8), primary key
 * @method MfGuardGroupPermission    setMfGuardGroup(MfGuardGroup $val)           
 * @method MfGuardGroupPermission    setMfGuardPermission(MfGuardPermission $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMfGuardGroupPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_guard_group_permission');
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('permission_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MfGuardGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('MfGuardPermission', array(
             'local' => 'permission_id',
             'foreign' => 'id'));
    }
}