<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MfInvoiceDetail', 'doctrine');

/**
 * BaseMfInvoiceDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int              $id                          Type: integer(8), primary key
 * @property int              $invoice_id                  Type: integer(8)
 * @property string           $description                 Type: string
 * @property string           $amount                      Type: string(255)
 * @property string           $created_at                  Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string           $updated_at                  Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property MfInvoice        $MfInvoice                   
 *  
 * @method int                getId()                      Type: integer(8), primary key
 * @method int                getInvoiceId()               Type: integer(8)
 * @method string             getDescription()             Type: string
 * @method string             getAmount()                  Type: string(255)
 * @method string             getCreatedAt()               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string             getUpdatedAt()               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method MfInvoice          getMfInvoice()               
 *  
 * @method MfInvoiceDetail    setId(int $val)              Type: integer(8), primary key
 * @method MfInvoiceDetail    setInvoiceId(int $val)       Type: integer(8)
 * @method MfInvoiceDetail    setDescription(string $val)  Type: string
 * @method MfInvoiceDetail    setAmount(string $val)       Type: string(255)
 * @method MfInvoiceDetail    setCreatedAt(string $val)    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method MfInvoiceDetail    setUpdatedAt(string $val)    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method MfInvoiceDetail    setMfInvoice(MfInvoice $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMfInvoiceDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_invoice_detail');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('invoice_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('amount', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => date('Y-m-d'),
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => date('Y-m-d'),
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MfInvoice', array(
             'local' => 'invoice_id',
             'foreign' => 'id'));
    }
}