<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AuditTrail', 'doctrine');

/**
 * BaseAuditTrail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int         $id                             Type: integer(4), primary key
 * @property int         $user_id                        Type: integer(4)
 * @property int         $form_entry_id                  Type: integer(4)
 * @property string      $action                         Type: string
 * @property string      $action_timestamp               Type: string(255)
 * @property int         $object_id                      Type: integer(4)
 * @property string      $object_name                    Type: string(250)
 * @property string      $before_values                  Type: string
 * @property string      $after_values                   Type: string
 * @property string      $ipaddress                      Type: string(250)
 * @property string      $http_agent                     Type: string(250)
 * @property string      $user_location                  Type: string(250)
 *  
 * @method int           getId()                         Type: integer(4), primary key
 * @method int           getUserId()                     Type: integer(4)
 * @method int           getFormEntryId()                Type: integer(4)
 * @method string        getAction()                     Type: string
 * @method string        getActionTimestamp()            Type: string(255)
 * @method int           getObjectId()                   Type: integer(4)
 * @method string        getObjectName()                 Type: string(250)
 * @method string        getBeforeValues()               Type: string
 * @method string        getAfterValues()                Type: string
 * @method string        getIpaddress()                  Type: string(250)
 * @method string        getHttpAgent()                  Type: string(250)
 * @method string        getUserLocation()               Type: string(250)
 *  
 * @method AuditTrail    setId(int $val)                 Type: integer(4), primary key
 * @method AuditTrail    setUserId(int $val)             Type: integer(4)
 * @method AuditTrail    setFormEntryId(int $val)        Type: integer(4)
 * @method AuditTrail    setAction(string $val)          Type: string
 * @method AuditTrail    setActionTimestamp(string $val) Type: string(255)
 * @method AuditTrail    setObjectId(int $val)           Type: integer(4)
 * @method AuditTrail    setObjectName(string $val)      Type: string(250)
 * @method AuditTrail    setBeforeValues(string $val)    Type: string
 * @method AuditTrail    setAfterValues(string $val)     Type: string
 * @method AuditTrail    setIpaddress(string $val)       Type: string(250)
 * @method AuditTrail    setHttpAgent(string $val)       Type: string(250)
 * @method AuditTrail    setUserLocation(string $val)    Type: string(250)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuditTrail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('audit_trail');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_entry_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('action', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('action_timestamp', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('object_name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => 250,
             ));
        $this->hasColumn('before_values', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => '',
             ));
        $this->hasColumn('after_values', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => '',
             ));
        $this->hasColumn('ipaddress', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => 250,
             ));
        $this->hasColumn('http_agent', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => 250,
             ));
        $this->hasColumn('user_location', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}