<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApFormThemes', 'doctrine');

/**
 * BaseApFormThemes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int           $theme_id                             Type: integer(4), primary key
 * @property int           $status                               Type: integer(4), default "1"
 * @property int           $theme_has_css                        Type: integer(4), default "0"
 * @property string        $theme_name                           Type: string(255)
 * @property int           $theme_built_in                       Type: integer(4), default "0"
 * @property string        $logo_type                            Type: string(11), default "default"
 * @property string        $logo_custom_image                    Type: string
 * @property int           $logo_custom_height                   Type: integer(4), default "40"
 * @property string        $logo_default_image                   Type: string(50)
 * @property int           $logo_default_repeat                  Type: integer(4), default "0"
 * @property string        $wallpaper_bg_type                    Type: string(11), default "color"
 * @property string        $wallpaper_bg_color                   Type: string(11)
 * @property string        $wallpaper_bg_pattern                 Type: string(50)
 * @property string        $wallpaper_bg_custom                  Type: string
 * @property string        $header_bg_type                       Type: string(11), default "color"
 * @property string        $header_bg_color                      Type: string(11)
 * @property string        $header_bg_pattern                    Type: string(50)
 * @property string        $header_bg_custom                     Type: string
 * @property string        $form_bg_type                         Type: string(11), default "color"
 * @property string        $form_bg_color                        Type: string(11)
 * @property string        $form_bg_pattern                      Type: string(50)
 * @property string        $form_bg_custom                       Type: string
 * @property string        $highlight_bg_type                    Type: string(11), default "color"
 * @property string        $highlight_bg_color                   Type: string(11)
 * @property string        $highlight_bg_pattern                 Type: string(50)
 * @property string        $highlight_bg_custom                  Type: string
 * @property string        $guidelines_bg_type                   Type: string(11), default "color"
 * @property string        $guidelines_bg_color                  Type: string(11)
 * @property string        $guidelines_bg_pattern                Type: string(50)
 * @property string        $guidelines_bg_custom                 Type: string
 * @property string        $field_bg_type                        Type: string(11), default "color"
 * @property string        $field_bg_color                       Type: string(11)
 * @property string        $field_bg_pattern                     Type: string(50)
 * @property string        $field_bg_custom                      Type: string
 * @property string        $form_title_font_type                 Type: string(50), default "Lucida Grande"
 * @property int           $form_title_font_weight               Type: integer(4), default "400"
 * @property string        $form_title_font_style                Type: string(25), default "normal"
 * @property string        $form_title_font_size                 Type: string(11)
 * @property string        $form_title_font_color                Type: string(11)
 * @property string        $form_desc_font_type                  Type: string(50), default "Lucida Grande"
 * @property int           $form_desc_font_weight                Type: integer(4), default "400"
 * @property string        $form_desc_font_style                 Type: string(25), default "normal"
 * @property string        $form_desc_font_size                  Type: string(11)
 * @property string        $form_desc_font_color                 Type: string(11)
 * @property string        $field_title_font_type                Type: string(50), default "Lucida Grande"
 * @property int           $field_title_font_weight              Type: integer(4), default "400"
 * @property string        $field_title_font_style               Type: string(25), default "normal"
 * @property string        $field_title_font_size                Type: string(11)
 * @property string        $field_title_font_color               Type: string(11)
 * @property string        $guidelines_font_type                 Type: string(50), default "Lucida Grande"
 * @property int           $guidelines_font_weight               Type: integer(4), default "400"
 * @property string        $guidelines_font_style                Type: string(25), default "normal"
 * @property string        $guidelines_font_size                 Type: string(11)
 * @property string        $guidelines_font_color                Type: string(11)
 * @property string        $section_title_font_type              Type: string(50), default "Lucida Grande"
 * @property int           $section_title_font_weight            Type: integer(4), default "400"
 * @property string        $section_title_font_style             Type: string(25), default "normal"
 * @property string        $section_title_font_size              Type: string(11)
 * @property string        $section_title_font_color             Type: string(11)
 * @property string        $section_desc_font_type               Type: string(50), default "Lucida Grande"
 * @property int           $section_desc_font_weight             Type: integer(4), default "400"
 * @property string        $section_desc_font_style              Type: string(25), default "normal"
 * @property string        $section_desc_font_size               Type: string(11)
 * @property string        $section_desc_font_color              Type: string(11)
 * @property string        $field_text_font_type                 Type: string(50), default "Lucida Grande"
 * @property int           $field_text_font_weight               Type: integer(4), default "400"
 * @property string        $field_text_font_style                Type: string(25), default "normal"
 * @property string        $field_text_font_size                 Type: string(11)
 * @property string        $field_text_font_color                Type: string(11)
 * @property int           $border_form_width                    Type: integer(4), default "1"
 * @property string        $border_form_style                    Type: string(11), default "solid"
 * @property string        $border_form_color                    Type: string(11)
 * @property int           $border_guidelines_width              Type: integer(4), default "1"
 * @property string        $border_guidelines_style              Type: string(11), default "solid"
 * @property string        $border_guidelines_color              Type: string(11)
 * @property int           $border_section_width                 Type: integer(4), default "1"
 * @property string        $border_section_style                 Type: string(11), default "solid"
 * @property string        $border_section_color                 Type: string(11)
 * @property string        $form_shadow_style                    Type: string(25), default "WarpShadow"
 * @property string        $form_shadow_size                     Type: string(11), default "large"
 * @property string        $form_shadow_brightness               Type: string(11), default "normal"
 * @property string        $form_button_type                     Type: string(11), default "text"
 * @property string        $form_button_text                     Type: string(100), default "Submit"
 * @property string        $form_button_image                    Type: string
 * @property string        $advanced_css                         Type: string
 * @property int           $user_id                              Type: integer(4), default "1"
 * @property int           $theme_is_private                     Type: integer(4), default "1"
 *  
 * @method int             getThemeId()                          Type: integer(4), primary key
 * @method int             getStatus()                           Type: integer(4), default "1"
 * @method int             getThemeHasCss()                      Type: integer(4), default "0"
 * @method string          getThemeName()                        Type: string(255)
 * @method int             getThemeBuiltIn()                     Type: integer(4), default "0"
 * @method string          getLogoType()                         Type: string(11), default "default"
 * @method string          getLogoCustomImage()                  Type: string
 * @method int             getLogoCustomHeight()                 Type: integer(4), default "40"
 * @method string          getLogoDefaultImage()                 Type: string(50)
 * @method int             getLogoDefaultRepeat()                Type: integer(4), default "0"
 * @method string          getWallpaperBgType()                  Type: string(11), default "color"
 * @method string          getWallpaperBgColor()                 Type: string(11)
 * @method string          getWallpaperBgPattern()               Type: string(50)
 * @method string          getWallpaperBgCustom()                Type: string
 * @method string          getHeaderBgType()                     Type: string(11), default "color"
 * @method string          getHeaderBgColor()                    Type: string(11)
 * @method string          getHeaderBgPattern()                  Type: string(50)
 * @method string          getHeaderBgCustom()                   Type: string
 * @method string          getFormBgType()                       Type: string(11), default "color"
 * @method string          getFormBgColor()                      Type: string(11)
 * @method string          getFormBgPattern()                    Type: string(50)
 * @method string          getFormBgCustom()                     Type: string
 * @method string          getHighlightBgType()                  Type: string(11), default "color"
 * @method string          getHighlightBgColor()                 Type: string(11)
 * @method string          getHighlightBgPattern()               Type: string(50)
 * @method string          getHighlightBgCustom()                Type: string
 * @method string          getGuidelinesBgType()                 Type: string(11), default "color"
 * @method string          getGuidelinesBgColor()                Type: string(11)
 * @method string          getGuidelinesBgPattern()              Type: string(50)
 * @method string          getGuidelinesBgCustom()               Type: string
 * @method string          getFieldBgType()                      Type: string(11), default "color"
 * @method string          getFieldBgColor()                     Type: string(11)
 * @method string          getFieldBgPattern()                   Type: string(50)
 * @method string          getFieldBgCustom()                    Type: string
 * @method string          getFormTitleFontType()                Type: string(50), default "Lucida Grande"
 * @method int             getFormTitleFontWeight()              Type: integer(4), default "400"
 * @method string          getFormTitleFontStyle()               Type: string(25), default "normal"
 * @method string          getFormTitleFontSize()                Type: string(11)
 * @method string          getFormTitleFontColor()               Type: string(11)
 * @method string          getFormDescFontType()                 Type: string(50), default "Lucida Grande"
 * @method int             getFormDescFontWeight()               Type: integer(4), default "400"
 * @method string          getFormDescFontStyle()                Type: string(25), default "normal"
 * @method string          getFormDescFontSize()                 Type: string(11)
 * @method string          getFormDescFontColor()                Type: string(11)
 * @method string          getFieldTitleFontType()               Type: string(50), default "Lucida Grande"
 * @method int             getFieldTitleFontWeight()             Type: integer(4), default "400"
 * @method string          getFieldTitleFontStyle()              Type: string(25), default "normal"
 * @method string          getFieldTitleFontSize()               Type: string(11)
 * @method string          getFieldTitleFontColor()              Type: string(11)
 * @method string          getGuidelinesFontType()               Type: string(50), default "Lucida Grande"
 * @method int             getGuidelinesFontWeight()             Type: integer(4), default "400"
 * @method string          getGuidelinesFontStyle()              Type: string(25), default "normal"
 * @method string          getGuidelinesFontSize()               Type: string(11)
 * @method string          getGuidelinesFontColor()              Type: string(11)
 * @method string          getSectionTitleFontType()             Type: string(50), default "Lucida Grande"
 * @method int             getSectionTitleFontWeight()           Type: integer(4), default "400"
 * @method string          getSectionTitleFontStyle()            Type: string(25), default "normal"
 * @method string          getSectionTitleFontSize()             Type: string(11)
 * @method string          getSectionTitleFontColor()            Type: string(11)
 * @method string          getSectionDescFontType()              Type: string(50), default "Lucida Grande"
 * @method int             getSectionDescFontWeight()            Type: integer(4), default "400"
 * @method string          getSectionDescFontStyle()             Type: string(25), default "normal"
 * @method string          getSectionDescFontSize()              Type: string(11)
 * @method string          getSectionDescFontColor()             Type: string(11)
 * @method string          getFieldTextFontType()                Type: string(50), default "Lucida Grande"
 * @method int             getFieldTextFontWeight()              Type: integer(4), default "400"
 * @method string          getFieldTextFontStyle()               Type: string(25), default "normal"
 * @method string          getFieldTextFontSize()                Type: string(11)
 * @method string          getFieldTextFontColor()               Type: string(11)
 * @method int             getBorderFormWidth()                  Type: integer(4), default "1"
 * @method string          getBorderFormStyle()                  Type: string(11), default "solid"
 * @method string          getBorderFormColor()                  Type: string(11)
 * @method int             getBorderGuidelinesWidth()            Type: integer(4), default "1"
 * @method string          getBorderGuidelinesStyle()            Type: string(11), default "solid"
 * @method string          getBorderGuidelinesColor()            Type: string(11)
 * @method int             getBorderSectionWidth()               Type: integer(4), default "1"
 * @method string          getBorderSectionStyle()               Type: string(11), default "solid"
 * @method string          getBorderSectionColor()               Type: string(11)
 * @method string          getFormShadowStyle()                  Type: string(25), default "WarpShadow"
 * @method string          getFormShadowSize()                   Type: string(11), default "large"
 * @method string          getFormShadowBrightness()             Type: string(11), default "normal"
 * @method string          getFormButtonType()                   Type: string(11), default "text"
 * @method string          getFormButtonText()                   Type: string(100), default "Submit"
 * @method string          getFormButtonImage()                  Type: string
 * @method string          getAdvancedCss()                      Type: string
 * @method int             getUserId()                           Type: integer(4), default "1"
 * @method int             getThemeIsPrivate()                   Type: integer(4), default "1"
 *  
 * @method ApFormThemes    setThemeId(int $val)                  Type: integer(4), primary key
 * @method ApFormThemes    setStatus(int $val)                   Type: integer(4), default "1"
 * @method ApFormThemes    setThemeHasCss(int $val)              Type: integer(4), default "0"
 * @method ApFormThemes    setThemeName(string $val)             Type: string(255)
 * @method ApFormThemes    setThemeBuiltIn(int $val)             Type: integer(4), default "0"
 * @method ApFormThemes    setLogoType(string $val)              Type: string(11), default "default"
 * @method ApFormThemes    setLogoCustomImage(string $val)       Type: string
 * @method ApFormThemes    setLogoCustomHeight(int $val)         Type: integer(4), default "40"
 * @method ApFormThemes    setLogoDefaultImage(string $val)      Type: string(50)
 * @method ApFormThemes    setLogoDefaultRepeat(int $val)        Type: integer(4), default "0"
 * @method ApFormThemes    setWallpaperBgType(string $val)       Type: string(11), default "color"
 * @method ApFormThemes    setWallpaperBgColor(string $val)      Type: string(11)
 * @method ApFormThemes    setWallpaperBgPattern(string $val)    Type: string(50)
 * @method ApFormThemes    setWallpaperBgCustom(string $val)     Type: string
 * @method ApFormThemes    setHeaderBgType(string $val)          Type: string(11), default "color"
 * @method ApFormThemes    setHeaderBgColor(string $val)         Type: string(11)
 * @method ApFormThemes    setHeaderBgPattern(string $val)       Type: string(50)
 * @method ApFormThemes    setHeaderBgCustom(string $val)        Type: string
 * @method ApFormThemes    setFormBgType(string $val)            Type: string(11), default "color"
 * @method ApFormThemes    setFormBgColor(string $val)           Type: string(11)
 * @method ApFormThemes    setFormBgPattern(string $val)         Type: string(50)
 * @method ApFormThemes    setFormBgCustom(string $val)          Type: string
 * @method ApFormThemes    setHighlightBgType(string $val)       Type: string(11), default "color"
 * @method ApFormThemes    setHighlightBgColor(string $val)      Type: string(11)
 * @method ApFormThemes    setHighlightBgPattern(string $val)    Type: string(50)
 * @method ApFormThemes    setHighlightBgCustom(string $val)     Type: string
 * @method ApFormThemes    setGuidelinesBgType(string $val)      Type: string(11), default "color"
 * @method ApFormThemes    setGuidelinesBgColor(string $val)     Type: string(11)
 * @method ApFormThemes    setGuidelinesBgPattern(string $val)   Type: string(50)
 * @method ApFormThemes    setGuidelinesBgCustom(string $val)    Type: string
 * @method ApFormThemes    setFieldBgType(string $val)           Type: string(11), default "color"
 * @method ApFormThemes    setFieldBgColor(string $val)          Type: string(11)
 * @method ApFormThemes    setFieldBgPattern(string $val)        Type: string(50)
 * @method ApFormThemes    setFieldBgCustom(string $val)         Type: string
 * @method ApFormThemes    setFormTitleFontType(string $val)     Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setFormTitleFontWeight(int $val)      Type: integer(4), default "400"
 * @method ApFormThemes    setFormTitleFontStyle(string $val)    Type: string(25), default "normal"
 * @method ApFormThemes    setFormTitleFontSize(string $val)     Type: string(11)
 * @method ApFormThemes    setFormTitleFontColor(string $val)    Type: string(11)
 * @method ApFormThemes    setFormDescFontType(string $val)      Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setFormDescFontWeight(int $val)       Type: integer(4), default "400"
 * @method ApFormThemes    setFormDescFontStyle(string $val)     Type: string(25), default "normal"
 * @method ApFormThemes    setFormDescFontSize(string $val)      Type: string(11)
 * @method ApFormThemes    setFormDescFontColor(string $val)     Type: string(11)
 * @method ApFormThemes    setFieldTitleFontType(string $val)    Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setFieldTitleFontWeight(int $val)     Type: integer(4), default "400"
 * @method ApFormThemes    setFieldTitleFontStyle(string $val)   Type: string(25), default "normal"
 * @method ApFormThemes    setFieldTitleFontSize(string $val)    Type: string(11)
 * @method ApFormThemes    setFieldTitleFontColor(string $val)   Type: string(11)
 * @method ApFormThemes    setGuidelinesFontType(string $val)    Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setGuidelinesFontWeight(int $val)     Type: integer(4), default "400"
 * @method ApFormThemes    setGuidelinesFontStyle(string $val)   Type: string(25), default "normal"
 * @method ApFormThemes    setGuidelinesFontSize(string $val)    Type: string(11)
 * @method ApFormThemes    setGuidelinesFontColor(string $val)   Type: string(11)
 * @method ApFormThemes    setSectionTitleFontType(string $val)  Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setSectionTitleFontWeight(int $val)   Type: integer(4), default "400"
 * @method ApFormThemes    setSectionTitleFontStyle(string $val) Type: string(25), default "normal"
 * @method ApFormThemes    setSectionTitleFontSize(string $val)  Type: string(11)
 * @method ApFormThemes    setSectionTitleFontColor(string $val) Type: string(11)
 * @method ApFormThemes    setSectionDescFontType(string $val)   Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setSectionDescFontWeight(int $val)    Type: integer(4), default "400"
 * @method ApFormThemes    setSectionDescFontStyle(string $val)  Type: string(25), default "normal"
 * @method ApFormThemes    setSectionDescFontSize(string $val)   Type: string(11)
 * @method ApFormThemes    setSectionDescFontColor(string $val)  Type: string(11)
 * @method ApFormThemes    setFieldTextFontType(string $val)     Type: string(50), default "Lucida Grande"
 * @method ApFormThemes    setFieldTextFontWeight(int $val)      Type: integer(4), default "400"
 * @method ApFormThemes    setFieldTextFontStyle(string $val)    Type: string(25), default "normal"
 * @method ApFormThemes    setFieldTextFontSize(string $val)     Type: string(11)
 * @method ApFormThemes    setFieldTextFontColor(string $val)    Type: string(11)
 * @method ApFormThemes    setBorderFormWidth(int $val)          Type: integer(4), default "1"
 * @method ApFormThemes    setBorderFormStyle(string $val)       Type: string(11), default "solid"
 * @method ApFormThemes    setBorderFormColor(string $val)       Type: string(11)
 * @method ApFormThemes    setBorderGuidelinesWidth(int $val)    Type: integer(4), default "1"
 * @method ApFormThemes    setBorderGuidelinesStyle(string $val) Type: string(11), default "solid"
 * @method ApFormThemes    setBorderGuidelinesColor(string $val) Type: string(11)
 * @method ApFormThemes    setBorderSectionWidth(int $val)       Type: integer(4), default "1"
 * @method ApFormThemes    setBorderSectionStyle(string $val)    Type: string(11), default "solid"
 * @method ApFormThemes    setBorderSectionColor(string $val)    Type: string(11)
 * @method ApFormThemes    setFormShadowStyle(string $val)       Type: string(25), default "WarpShadow"
 * @method ApFormThemes    setFormShadowSize(string $val)        Type: string(11), default "large"
 * @method ApFormThemes    setFormShadowBrightness(string $val)  Type: string(11), default "normal"
 * @method ApFormThemes    setFormButtonType(string $val)        Type: string(11), default "text"
 * @method ApFormThemes    setFormButtonText(string $val)        Type: string(100), default "Submit"
 * @method ApFormThemes    setFormButtonImage(string $val)       Type: string
 * @method ApFormThemes    setAdvancedCss(string $val)           Type: string
 * @method ApFormThemes    setUserId(int $val)                   Type: integer(4), default "1"
 * @method ApFormThemes    setThemeIsPrivate(int $val)           Type: integer(4), default "1"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApFormThemes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_form_themes');
        $this->hasColumn('theme_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theme_has_css', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theme_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('theme_built_in', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('logo_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'default',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('logo_custom_image', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('logo_custom_height', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '40',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('logo_default_image', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('logo_default_repeat', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('wallpaper_bg_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'color',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('wallpaper_bg_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('wallpaper_bg_pattern', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('wallpaper_bg_custom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('header_bg_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'color',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('header_bg_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('header_bg_pattern', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('header_bg_custom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('form_bg_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'color',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_bg_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_bg_pattern', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('form_bg_custom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('highlight_bg_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'color',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('highlight_bg_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('highlight_bg_pattern', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('highlight_bg_custom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('guidelines_bg_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'color',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('guidelines_bg_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('guidelines_bg_pattern', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('guidelines_bg_custom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('field_bg_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'color',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('field_bg_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('field_bg_pattern', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('field_bg_custom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('form_title_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('form_title_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_title_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('form_title_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_title_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_desc_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('form_desc_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_desc_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('form_desc_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_desc_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('field_title_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('field_title_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('field_title_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('field_title_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('field_title_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('guidelines_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('guidelines_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('guidelines_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('guidelines_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('guidelines_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('section_title_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('section_title_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('section_title_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('section_title_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('section_title_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('section_desc_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('section_desc_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('section_desc_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('section_desc_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('section_desc_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('field_text_font_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Lucida Grande',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('field_text_font_weight', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '400',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('field_text_font_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('field_text_font_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('field_text_font_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('border_form_width', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('border_form_style', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'solid',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('border_form_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('border_guidelines_width', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('border_guidelines_style', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'solid',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('border_guidelines_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('border_section_width', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('border_section_style', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'solid',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('border_section_color', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_shadow_style', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'WarpShadow',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('form_shadow_size', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'large',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_shadow_brightness', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'normal',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_button_type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'text',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('form_button_text', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Submit',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('form_button_image', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('advanced_css', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theme_is_private', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}