<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApEntriesPreferences', 'doctrine');

/**
 * BaseApEntriesPreferences
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                   $id                               Type: integer(8), primary key
 * @property int                   $form_id                          Type: integer(4)
 * @property int                   $user_id                          Type: integer(4)
 * @property string                $entries_sort_by                  Type: string(100), default "id-desc"
 * @property int                   $entries_enable_filter            Type: integer(4), default "0"
 * @property string                $entries_filter_type              Type: string(5), default "all"
 *  
 * @method int                     getId()                           Type: integer(8), primary key
 * @method int                     getFormId()                       Type: integer(4)
 * @method int                     getUserId()                       Type: integer(4)
 * @method string                  getEntriesSortBy()                Type: string(100), default "id-desc"
 * @method int                     getEntriesEnableFilter()          Type: integer(4), default "0"
 * @method string                  getEntriesFilterType()            Type: string(5), default "all"
 *  
 * @method ApEntriesPreferences    setId(int $val)                   Type: integer(8), primary key
 * @method ApEntriesPreferences    setFormId(int $val)               Type: integer(4)
 * @method ApEntriesPreferences    setUserId(int $val)               Type: integer(4)
 * @method ApEntriesPreferences    setEntriesSortBy(string $val)     Type: string(100), default "id-desc"
 * @method ApEntriesPreferences    setEntriesEnableFilter(int $val)  Type: integer(4), default "0"
 * @method ApEntriesPreferences    setEntriesFilterType(string $val) Type: string(5), default "all"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApEntriesPreferences extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_entries_preferences');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entries_sort_by', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'id-desc',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('entries_enable_filter', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entries_filter_type', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'all',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('entries_incomplete_sort_by', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'id-desc',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('entries_incomplete_enable_filter', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'id-desc',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('entries_incomplete_filter_type', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'id-desc',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}