<?php

/**
 * BasePlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $plot_no
 * @property string $plot_type
 * @property string $plot_status
 * @property string $plot_size
 * @property string $plot_lat
 * @property string $plot_long
 * @property Doctrine_Collection $PlotActivity
 * 
 * @method integer             getPlotNo()       Returns the current record's "plot_no" value
 * @method string              getPlotType()     Returns the current record's "plot_type" value
 * @method string              getPlotStatus()   Returns the current record's "plot_status" value
 * @method string              getPlotSize()     Returns the current record's "plot_size" value
 * @method string              getPlotLat()      Returns the current record's "plot_lat" value
 * @method string              getPlotLong()     Returns the current record's "plot_long" value
 * @method Doctrine_Collection getPlotActivity() Returns the current record's "PlotActivity" collection
 * @method Plot                setPlotNo()       Sets the current record's "plot_no" value
 * @method Plot                setPlotType()     Sets the current record's "plot_type" value
 * @method Plot                setPlotStatus()   Sets the current record's "plot_status" value
 * @method Plot                setPlotSize()     Sets the current record's "plot_size" value
 * @method Plot                setPlotLat()      Sets the current record's "plot_lat" value
 * @method Plot                setPlotLong()     Sets the current record's "plot_long" value
 * @method Plot                setPlotActivity() Sets the current record's "PlotActivity" collection
 * 
 * @package    permit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlot extends sfDoctrineRecord
{
     public function setTableDefinition()
     {
          $this->setTableName('plot');
          $this->hasColumn('plot_no', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_type', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_status', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_size', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_lat', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_long', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_location', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_comments', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('owner_name', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('owner_phone', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('physical_address', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('block_number', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('property_usage', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('plot_size_ha', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));

          $this->hasColumn('upn', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('ward', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('parent_upn', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('measurements', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('po_box', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('postal_code', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('email', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));

          $this->hasColumn('amount_land_rates', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('town', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
          $this->hasColumn('customer_supplier_id', 'string', 250, array(
               'type' => 'string',
               'length' => 250,
          ));
     }

     public function setUp()
     {
          parent::setUp();
          $this->hasMany('PlotActivity', array(
               'local' => 'id',
               'foreign' => 'plot_id'
          ));
     }
}
