<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormEntry', 'doctrine');

/**
 * BaseFormEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                      $id                                            Type: integer(8), primary key
 * @property int                                      $form_id                                       Type: integer(4)
 * @property int                                      $entry_id                                      Type: integer(4)
 * @property int                                      $user_id                                       Type: integer(4)
 * @property int                                      $circulation_id                                Type: integer(4)
 * @property int                                      $approved                                      Type: integer(4), default "0"
 * @property string                                   $application_id                                Type: string(255), default "0"
 * @property int                                      $declined                                      Type: integer(4), default "0"
 * @property int                                      $deleted_status                                Type: integer(4), default "0"
 * @property int                                      $previous_submission                           Type: integer(8)
 * @property int                                      $parent_submission                             Type: integer(8)
 * @property string                                   $date_of_submission                            Type: string(250)
 * @property string                                   $date_of_response                              Type: string(250)
 * @property string                                   $date_of_issue                                 Type: string(250)
 * @property string                                   $observation                                   Type: string
 * @property int                                      $assessment_inprogress                         Type: integer(4), default "0"
 * @property string                                   $pdf_path                                      Type: string(255)
 * @property ApForms                                  $ApForms                                       
 * @property Doctrine_Collection|ApprovalCondition[]  $ApprovalCondition                             
 * @property Doctrine_Collection|EntryDecline[]       $EntryDecline                                  
 * @property Doctrine_Collection|MfInvoice[]          $MfInvoice                                     
 * @property Doctrine_Collection|Task[]               $Task                                          
 * @property Doctrine_Collection|SavedPermit[]        $SavedPermit                                   
 *  
 * @method int                                        getId()                                        Type: integer(8), primary key
 * @method int                                        getFormId()                                    Type: integer(4)
 * @method int                                        getEntryId()                                   Type: integer(4)
 * @method int                                        getUserId()                                    Type: integer(4)
 * @method int                                        getCirculationId()                             Type: integer(4)
 * @method int                                        getApproved()                                  Type: integer(4), default "0"
 * @method string                                     getApplicationId()                             Type: string(255), default "0"
 * @method int                                        getDeclined()                                  Type: integer(4), default "0"
 * @method int                                        getDeletedStatus()                             Type: integer(4), default "0"
 * @method int                                        getPreviousSubmission()                        Type: integer(8)
 * @method int                                        getParentSubmission()                          Type: integer(8)
 * @method string                                     getDateOfSubmission()                          Type: string(250)
 * @method string                                     getDateOfResponse()                            Type: string(250)
 * @method string                                     getDateOfIssue()                               Type: string(250)
 * @method string                                     getObservation()                               Type: string
 * @method int                                        getAssessmentInprogress()                      Type: integer(4), default "0"
 * @method string                                     getPdfPath()                                   Type: string(255)
 * @method ApForms                                    getApForms()                                   
 * @method Doctrine_Collection|ApprovalCondition[]    getApprovalCondition()                         
 * @method Doctrine_Collection|EntryDecline[]         getEntryDecline()                              
 * @method Doctrine_Collection|MfInvoice[]            getMfInvoice()                                 
 * @method Doctrine_Collection|Task[]                 getTask()                                      
 * @method Doctrine_Collection|SavedPermit[]          getSavedPermit()                               
 *  
 * @method FormEntry                                  setId(int $val)                                Type: integer(8), primary key
 * @method FormEntry                                  setFormId(int $val)                            Type: integer(4)
 * @method FormEntry                                  setEntryId(int $val)                           Type: integer(4)
 * @method FormEntry                                  setUserId(int $val)                            Type: integer(4)
 * @method FormEntry                                  setCirculationId(int $val)                     Type: integer(4)
 * @method FormEntry                                  setApproved(int $val)                          Type: integer(4), default "0"
 * @method FormEntry                                  setApplicationId(string $val)                  Type: string(255), default "0"
 * @method FormEntry                                  setDeclined(int $val)                          Type: integer(4), default "0"
 * @method FormEntry                                  setDeletedStatus(int $val)                     Type: integer(4), default "0"
 * @method FormEntry                                  setPreviousSubmission(int $val)                Type: integer(8)
 * @method FormEntry                                  setParentSubmission(int $val)                  Type: integer(8)
 * @method FormEntry                                  setDateOfSubmission(string $val)               Type: string(250)
 * @method FormEntry                                  setDateOfResponse(string $val)                 Type: string(250)
 * @method FormEntry                                  setDateOfIssue(string $val)                    Type: string(250)
 * @method FormEntry                                  setObservation(string $val)                    Type: string
 * @method FormEntry                                  setAssessmentInprogress(int $val)              Type: integer(4), default "0"
 * @method FormEntry                                  setPdfPath(string $val)                        Type: string(255)
 * @method FormEntry                                  setApForms(ApForms $val)                       
 * @method FormEntry                                  setApprovalCondition(Doctrine_Collection $val) 
 * @method FormEntry                                  setEntryDecline(Doctrine_Collection $val)      
 * @method FormEntry                                  setMfInvoice(Doctrine_Collection $val)         
 * @method FormEntry                                  setTask(Doctrine_Collection $val)              
 * @method FormEntry                                  setSavedPermit(Doctrine_Collection $val)       
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('form_entry');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('service_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entry_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('business_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('circulation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('approved', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('application_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('declined', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deleted_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('previous_submission', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('parent_submission', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('date_of_submission', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('date_of_response', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => '',
             'length' => 250,
             ));
        $this->hasColumn('date_of_issue', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => '',
             'length' => 250,
             ));
        $this->hasColumn('observation', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => '',
             'length' => '',
             ));
        $this->hasColumn('assessment_inprogress', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('pdf_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('form_data', 'json', null, array(
             'type' => 'json',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             ));
        $this->hasColumn('merchant_identifier', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ApForms as Form', array(
             'local' => 'form_id',
             'foreign' => 'form_id'));

        $this->hasMany('ApprovalCondition', array(
             'local' => 'id',
             'foreign' => 'entry_id'));

        $this->hasMany('EntryDecline', array(
             'local' => 'id',
             'foreign' => 'entry_id'));

        $this->hasMany('MfInvoice', array(
             'local' => 'id',
             'foreign' => 'app_id'));

        $this->hasMany('Task', array(
             'local' => 'id',
             'foreign' => 'application_id'));

        $this->hasMany('SavedPermit', array(
             'local' => 'id',
             'foreign' => 'application_id'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUserProfile', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('MfUserProfile', array(
             'local' => 'business_id',
             'foreign' => 'id'));

        $this->hasOne('SubMenus as Stage', array(
             'local' => 'approved',
             'foreign' => 'id'));

        $this->hasMany('Inspections as Inspections', array(
             'local' => 'id',
             'foreign' => 'application_id'));
    }
}