<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MfUserProfile', 'doctrine');

/**
 * BaseMfUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $user_id                  Type: integer(8), primary key
 * @property int            $form_id                  Type: integer(8)
 * @property int            $entry_id                 Type: integer(8)
 * @property string         $created_at               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string         $updated_at               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 *  
 * @method int              getUserId()               Type: integer(8), primary key
 * @method int              getFormId()               Type: integer(8)
 * @method int              getEntryId()              Type: integer(8)
 * @method string           getCreatedAt()            Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string           getUpdatedAt()            Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 *  
 * @method MfUserProfile    setUserId(int $val)       Type: integer(8), primary key
 * @method MfUserProfile    setFormId(int $val)       Type: integer(8)
 * @method MfUserProfile    setEntryId(int $val)      Type: integer(8)
 * @method MfUserProfile    setCreatedAt(string $val) Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method MfUserProfile    setUpdatedAt(string $val) Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMfUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_user_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('form_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('entry_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deleted', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('form_data', 'json', null, array(
             'type' => 'json',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
        $this->hasOne('ApForms as Form', array(
             'local' => 'form_id',
             'foreign' => 'form_id',
             'onDelete' => 'CASCADE'));
        
    }
}