<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AppChange', 'doctrine');

/**
 * BaseAppChange
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $id                             Type: integer(4), primary key
 * @property int        $stage_id                       Type: integer(4)
 * @property int        $form_id                        Type: integer(4)
 * @property int        $identifier_type                Type: integer(4)
 * @property string     $app_identifier                 Type: string
 * @property string     $identifier_start               Type: string
 *  
 * @method int          getId()                         Type: integer(4), primary key
 * @method int          getStageId()                    Type: integer(4)
 * @method int          getFormId()                     Type: integer(4)
 * @method int          getIdentifierType()             Type: integer(4)
 * @method string       getAppIdentifier()              Type: string
 * @method string       getIdentifierStart()            Type: string
 *  
 * @method AppChange    setId(int $val)                 Type: integer(4), primary key
 * @method AppChange    setStageId(int $val)            Type: integer(4)
 * @method AppChange    setFormId(int $val)             Type: integer(4)
 * @method AppChange    setIdentifierType(int $val)     Type: integer(4)
 * @method AppChange    setAppIdentifier(string $val)   Type: string
 * @method AppChange    setIdentifierStart(string $val) Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppChange extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('app_change');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('stage_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('identifier_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('app_identifier', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('identifier_start', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}