<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('News', 'doctrine');

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int     $id                       Type: integer(4), primary key
 * @property string  $title                    Type: string(100)
 * @property string  $article                  Type: string
 * @property int     $created_by               Type: integer(4)
 * @property string  $created_on               Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @property int     $published                Type: integer(4)
 * @property int     $hits                     Type: integer(4), default "0"
 * @property int     $agency_id                Type: integer(4)
 * @property int     $deleted                  Type: integer(4), default "0"
 *  
 * @method int       getId()                   Type: integer(4), primary key
 * @method string    getTitle()                Type: string(100)
 * @method string    getArticle()              Type: string
 * @method int       getCreatedBy()            Type: integer(4)
 * @method string    getCreatedOn()            Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @method int       getPublished()            Type: integer(4)
 * @method int       getHits()                 Type: integer(4), default "0"
 * @method int       getAgencyId()             Type: integer(4)
 * @method int       getDeleted()              Type: integer(4), default "0"
 *  
 * @method News      setId(int $val)           Type: integer(4), primary key
 * @method News      setTitle(string $val)     Type: string(100)
 * @method News      setArticle(string $val)   Type: string
 * @method News      setCreatedBy(int $val)    Type: integer(4)
 * @method News      setCreatedOn(string $val) Type: date(25), Date in ISO-8601 format (YYYY-MM-DD)
 * @method News      setPublished(int $val)    Type: integer(4)
 * @method News      setHits(int $val)         Type: integer(4), default "0"
 * @method News      setAgencyId(int $val)     Type: integer(4)
 * @method News      setDeleted(int $val)      Type: integer(4), default "0"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('article', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_on', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('published', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hits', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('agency_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deleted', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}