<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGuardUserGroup', 'doctrine');

/**
 * BaseSfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $user_id                           Type: integer(8), primary key
 * @property int               $group_id                          Type: integer(8), primary key
 * @property string            $created_at                        Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string            $updated_at                        Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property SfGuardGroup      $SfGuardGroup                      
 * @property SfGuardUser       $SfGuardUser                       
 *  
 * @method int                 getUserId()                        Type: integer(8), primary key
 * @method int                 getGroupId()                       Type: integer(8), primary key
 * @method string              getCreatedAt()                     Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string              getUpdatedAt()                     Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardGroup        getSfGuardGroup()                  
 * @method SfGuardUser         getSfGuardUser()                   
 *  
 * @method SfGuardUserGroup    setUserId(int $val)                Type: integer(8), primary key
 * @method SfGuardUserGroup    setGroupId(int $val)               Type: integer(8), primary key
 * @method SfGuardUserGroup    setCreatedAt(string $val)          Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUserGroup    setUpdatedAt(string $val)          Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUserGroup    setSfGuardGroup(SfGuardGroup $val) 
 * @method SfGuardUserGroup    setSfGuardUser(SfGuardUser $val)   
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGuardUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_group');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}