<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Boraqs', 'doctrine');

/**
 * BaseFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $members_no
 * @property string $full_name
 * @property string $email
 * @property integer $address
 * @property string $town
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getMembersNo()   Returns the current record's "members_no" value
 * @method string  getFullName()     Returns the current record's "full_name" value
 * @method string  getEmail()      Returns the current record's "email" value
 * @method date    getAddress()  Returns the current record's "address" value
 * @method integer getTown()    Returns the current record's "town" value
 * @method Faq     setId()         Sets the current record's "id" value
 * @method Faq     setMembersNo()   Sets the current record's "members_no" value
 * @method Faq     setFullName()     Sets the current record's "full_name" value
 * @method Faq     setEmail()  Sets the current record's "email" value
 * @method Faq     setAddress()   Sets the current record's "address" value
 * @method Faq     setTown()      Sets the current record's "town" value
 * 
 * @package    permit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBoraqs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('boraqs');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('members_no', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('full_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('address', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('town', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}