<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfFormslot', 'doctrine');

/**
 * BaseCfFormslot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nid
 * @property string $strname
 * @property integer $ntemplateid
 * @property integer $nslotnumber
 * @property integer $nsendtype
 * @property Doctrine_Collection $ConditionsOfApproval
 * 
 * @method integer             getNid()                  Returns the current record's "nid" value
 * @method string              getStrname()              Returns the current record's "strname" value
 * @method integer             getNtemplateid()          Returns the current record's "ntemplateid" value
 * @method integer             getNslotnumber()          Returns the current record's "nslotnumber" value
 * @method integer             getNsendtype()            Returns the current record's "nsendtype" value
 * @method Doctrine_Collection getConditionsOfApproval() Returns the current record's "ConditionsOfApproval" collection
 * @method CfFormslot          setNid()                  Sets the current record's "nid" value
 * @method CfFormslot          setStrname()              Sets the current record's "strname" value
 * @method CfFormslot          setNtemplateid()          Sets the current record's "ntemplateid" value
 * @method CfFormslot          setNslotnumber()          Sets the current record's "nslotnumber" value
 * @method CfFormslot          setNsendtype()            Sets the current record's "nsendtype" value
 * @method CfFormslot          setConditionsOfApproval() Sets the current record's "ConditionsOfApproval" collection
 * 
 * @package    permit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfFormslot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_formslot');
        $this->hasColumn('nid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('strname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('strdescription', 'integer', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '',
             'length' => '',
             ));
        $this->hasColumn('nslotnumber', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nsendtype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConditionsOfApproval', array(
             'local' => 'nid',
             'foreign' => 'slot_id'));
    }
}