<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApColumnPreferences', 'doctrine');

/**
 * BaseApColumnPreferences
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                  $acp_id                        Type: integer(4), primary key
 * @property int                  $form_id                       Type: integer(4)
 * @property string               $element_name                  Type: string(255)
 * @property int                  $position                      Type: integer(4), default "0"
 * @property int                  $incomplete_entries            Type: integer(1), default "0"
 * @property int                  $user_id                       Type: integer(4), default "1"
 *  
 * @method int                    getAcpId()                     Type: integer(4), primary key
 * @method int                    getFormId()                    Type: integer(4)
 * @method string                 getElementName()               Type: string(255)
 * @method int                    getPosition()                  Type: integer(4), default "0"
 * @method int                    getIncompleteEntries()         Type: integer(1), default "0"
 * @method int                    getUserId()                    Type: integer(4), default "1"
 *  
 * @method ApColumnPreferences    setAcpId(int $val)             Type: integer(4), primary key
 * @method ApColumnPreferences    setFormId(int $val)            Type: integer(4)
 * @method ApColumnPreferences    setElementName(string $val)    Type: string(255)
 * @method ApColumnPreferences    setPosition(int $val)          Type: integer(4), default "0"
 * @method ApColumnPreferences    setIncompleteEntries(int $val) Type: integer(1), default "0"
 * @method ApColumnPreferences    setUserId(int $val)            Type: integer(4), default "1"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApColumnPreferences extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_column_preferences');
        $this->hasColumn('acp_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('incomplete_entries', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}