<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApDropdownFilters', 'doctrine');

/**
 * BaseApDropdownFilters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                $id                     Type: integer(4), primary key
 * @property int                $form_id                Type: integer(4)
 * @property int                $element_id             Type: integer(4)
 * @property int                $link_id                Type: integer(4)
 * @property int                $option_id              Type: integer(4)
 * @property int                $lioption_id            Type: integer(4)
 *  
 * @method int                  getId()                 Type: integer(4), primary key
 * @method int                  getFormId()             Type: integer(4)
 * @method int                  getElementId()          Type: integer(4)
 * @method int                  getLinkId()             Type: integer(4)
 * @method int                  getOptionId()           Type: integer(4)
 * @method int                  getLioptionId()         Type: integer(4)
 *  
 * @method ApDropdownFilters    setId(int $val)         Type: integer(4), primary key
 * @method ApDropdownFilters    setFormId(int $val)     Type: integer(4)
 * @method ApDropdownFilters    setElementId(int $val)  Type: integer(4)
 * @method ApDropdownFilters    setLinkId(int $val)     Type: integer(4)
 * @method ApDropdownFilters    setOptionId(int $val)   Type: integer(4)
 * @method ApDropdownFilters    setLioptionId(int $val) Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApDropdownFilters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_dropdown_filters');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('link_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('lioption_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}