<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Communication', 'doctrine');

/**
 * BaseCommunication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $id                        Type: integer(4), primary key
 * @property int            $sender                    Type: integer(4)
 * @property int            $receiver                  Type: integer(4)
 * @property string         $message                   Type: string
 * @property int            $reply                     Type: integer(4)
 * @property int            $isread                    Type: integer(4), default "0"
 * @property string         $created_on                Type: string(50)
 * @property int            $application_id            Type: integer(4)
 *  
 * @method int              getId()                    Type: integer(4), primary key
 * @method int              getSender()                Type: integer(4)
 * @method int              getReceiver()              Type: integer(4)
 * @method string           getMessage()               Type: string
 * @method int              getReply()                 Type: integer(4)
 * @method int              getIsread()                Type: integer(4), default "0"
 * @method string           getCreatedOn()             Type: string(50)
 * @method int              getApplicationId()         Type: integer(4)
 *  
 * @method Communication    setId(int $val)            Type: integer(4), primary key
 * @method Communication    setSender(int $val)        Type: integer(4)
 * @method Communication    setReceiver(int $val)      Type: integer(4)
 * @method Communication    setMessage(string $val)    Type: string
 * @method Communication    setReply(int $val)         Type: integer(4)
 * @method Communication    setIsread(int $val)        Type: integer(4), default "0"
 * @method Communication    setCreatedOn(string $val)  Type: string(50)
 * @method Communication    setApplicationId(int $val) Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommunication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('communication');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sender', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('receiver', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('reply', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('isread', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_on', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
		$this->hasOne('CfUser', array(
			'local' => 'sender',
			'foreign' => 'nid'
		));
    }
}