<?php

/**
 * BasePlotActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $plot_id
 * @property integer $entry_id
 * @property Plot $Plot
 * @property FormEntry $Application
 * 
 * @method integer      getPlotId()      Returns the current record's "plot_id" value
 * @method integer      getEntryId()     Returns the current record's "entry_id" value
 * @method Plot         getPlot()        Returns the current record's "Plot" value
 * @method FormEntry    getApplication() Returns the current record's "Application" value
 * @method PlotActivity setPlotId()      Sets the current record's "plot_id" value
 * @method PlotActivity setEntryId()     Sets the current record's "entry_id" value
 * @method PlotActivity setPlot()        Sets the current record's "Plot" value
 * @method PlotActivity setApplication() Sets the current record's "Application" value
 * 
 * @package    permit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlotActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plot_activity');
        $this->hasColumn('plot_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('entry_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Plot', array(
             'local' => 'plot_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FormEntry as Application', array(
             'local' => 'entry_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}