<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormDependents', 'doctrine');

/**
 * BaseFormDependents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int             $id                          Type: integer(4), primary key
 * @property int             $form_id                     Type: integer(4)
 * @property int             $element_id                  Type: integer(4)
 * @property string          $element_value               Type: string
 * @property int             $dependent_form_id           Type: integer(4)
 *  
 * @method int               getId()                      Type: integer(4), primary key
 * @method int               getFormId()                  Type: integer(4)
 * @method int               getElementId()               Type: integer(4)
 * @method string            getElementValue()            Type: string
 * @method int               getDependentFormId()         Type: integer(4)
 *  
 * @method FormDependents    setId(int $val)              Type: integer(4), primary key
 * @method FormDependents    setFormId(int $val)          Type: integer(4)
 * @method FormDependents    setElementId(int $val)       Type: integer(4)
 * @method FormDependents    setElementValue(string $val) Type: string
 * @method FormDependents    setDependentFormId(int $val) Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormDependents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('form_dependents');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dependent_form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}