<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExtLocales', 'doctrine');

/**
 * BaseExtLocales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int         $id                               Type: integer(4), primary key
 * @property string      $locale_identifier                Type: string(250)
 * @property string      $local_title                      Type: string(250)
 * @property string      $locale_description               Type: string
 * @property int         $is_default                       Type: integer(4), default "0"
 * @property int         $text_align                       Type: integer(4), default "0"
 *  
 * @method int           getId()                           Type: integer(4), primary key
 * @method string        getLocaleIdentifier()             Type: string(250)
 * @method string        getLocalTitle()                   Type: string(250)
 * @method string        getLocaleDescription()            Type: string
 * @method int           getIsDefault()                    Type: integer(4), default "0"
 * @method int           getTextAlign()                    Type: integer(4), default "0"
 *  
 * @method ExtLocales    setId(int $val)                   Type: integer(4), primary key
 * @method ExtLocales    setLocaleIdentifier(string $val)  Type: string(250)
 * @method ExtLocales    setLocalTitle(string $val)        Type: string(250)
 * @method ExtLocales    setLocaleDescription(string $val) Type: string
 * @method ExtLocales    setIsDefault(int $val)            Type: integer(4), default "0"
 * @method ExtLocales    setTextAlign(int $val)            Type: integer(4), default "0"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtLocales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ext_locales');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('locale_identifier', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('local_title', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('locale_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_default', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('text_align', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}