<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApReportFilters', 'doctrine');

/**
 * BaseApReportFilters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int              $arf_id                         Type: integer(4), primary key
 * @property int              $form_id                        Type: integer(4)
 * @property int              $chart_id                       Type: integer(4)
 * @property string           $element_name                   Type: string(50)
 * @property string           $filter_condition               Type: string(15), default "is"
 * @property string           $filter_keyword                 Type: string(255)
 *  
 * @method int                getArfId()                      Type: integer(4), primary key
 * @method int                getFormId()                     Type: integer(4)
 * @method int                getChartId()                    Type: integer(4)
 * @method string             getElementName()                Type: string(50)
 * @method string             getFilterCondition()            Type: string(15), default "is"
 * @method string             getFilterKeyword()              Type: string(255)
 *  
 * @method ApReportFilters    setArfId(int $val)              Type: integer(4), primary key
 * @method ApReportFilters    setFormId(int $val)             Type: integer(4)
 * @method ApReportFilters    setChartId(int $val)            Type: integer(4)
 * @method ApReportFilters    setElementName(string $val)     Type: string(50)
 * @method ApReportFilters    setFilterCondition(string $val) Type: string(15), default "is"
 * @method ApReportFilters    setFilterKeyword(string $val)   Type: string(255)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApReportFilters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_report_filters');
        $this->hasColumn('arf_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('chart_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('filter_condition', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'is',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('filter_keyword', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}