<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Favorites', 'doctrine');

/**
 * BaseFavorites
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $id                        Type: integer(4), primary key
 * @property string     $subject                   Type: string(250)
 * @property string     $content                   Type: string(250)
 * @property int        $application_id            Type: integer(4)
 * @property int        $isread                    Type: integer(4)
 * @property int        $userid                    Type: integer(4)
 * @property string     $datesent                  Type: string(250)
 *  
 * @method int          getId()                    Type: integer(4), primary key
 * @method string       getSubject()               Type: string(250)
 * @method string       getContent()               Type: string(250)
 * @method int          getApplicationId()         Type: integer(4)
 * @method int          getIsread()                Type: integer(4)
 * @method int          getUserid()                Type: integer(4)
 * @method string       getDatesent()              Type: string(250)
 *  
 * @method Favorites    setId(int $val)            Type: integer(4), primary key
 * @method Favorites    setSubject(string $val)    Type: string(250)
 * @method Favorites    setContent(string $val)    Type: string(250)
 * @method Favorites    setApplicationId(int $val) Type: integer(4)
 * @method Favorites    setIsread(int $val)        Type: integer(4)
 * @method Favorites    setUserid(int $val)        Type: integer(4)
 * @method Favorites    setDatesent(string $val)   Type: string(250)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFavorites extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('favorites');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('subject', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('content', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('isread', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('datesent', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}