<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApFieldRelations', 'doctrine');

/**
 * BaseApFieldRelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $id                 Type: integer(4), primary key
 * @property int               $field1             Type: integer(4)
 * @property int               $field2             Type: integer(4)
 * @property int               $formid             Type: integer(4)
 * @property int               $status             Type: integer(4), default "0"
 *  
 * @method int                 getId()             Type: integer(4), primary key
 * @method int                 getField1()         Type: integer(4)
 * @method int                 getField2()         Type: integer(4)
 * @method int                 getFormid()         Type: integer(4)
 * @method int                 getStatus()         Type: integer(4), default "0"
 *  
 * @method ApFieldRelations    setId(int $val)     Type: integer(4), primary key
 * @method ApFieldRelations    setField1(int $val) Type: integer(4)
 * @method ApFieldRelations    setField2(int $val) Type: integer(4)
 * @method ApFieldRelations    setFormid(int $val) Type: integer(4)
 * @method ApFieldRelations    setStatus(int $val) Type: integer(4), default "0"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApFieldRelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_field_relations');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('field1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('field2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('formid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}