<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menus', 'doctrine');

/**
 * BaseMenus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int     $id                   Type: integer(4), primary key
 * @property string  $title                Type: string
 * @property int     $order_no             Type: integer(4)
 *  
 * @method int       getId()               Type: integer(4), primary key
 * @method string    getTitle()            Type: string
 * @method int       getOrderNo()          Type: integer(4)
 *  
 * @method Menus     setId(int $val)       Type: integer(4), primary key
 * @method Menus     setTitle(string $val) Type: string
 * @method Menus     setOrderNo(int $val)  Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menus');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('service_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('service_form', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'default' => 0,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('service_number', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 'AAA00AA1',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('service_fee_field', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'default' => 0,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('order_no', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 0,
             'autoincrement' => false,
             'length' => 4,
             ));
        //OTB patch add app queuing
         $this->hasColumn('app_queuing', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 256,
             ));
		//OTB workflow category
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
		//OTB Start - Multi Agency Implementation
        $this->hasMany('AgencyMenu', array(
             'local' => 'id',
             'foreign' => 'menu_id'));
		//OTB End - Multi Agency Implementation
		//OTB workflow category
        $this->hasOne('WorkflowCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));
		//OTB END
		//OTB Start
		$this->hasMany('SubMenus',array(
			'local' => 'id',
			'foreign' => 'menu_id'
		));
		//OTB END 
    }
}