<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExtTranslations', 'doctrine');

/**
 * BaseExtTranslations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int              $id                        Type: integer(4), primary key
 * @property string           $locale                    Type: string(50)
 * @property string           $table_class               Type: string(250)
 * @property string           $field_name                Type: string(250)
 * @property int              $field_id                  Type: integer(4)
 * @property string           $trl_content               Type: string
 * @property int              $option_id                 Type: integer(4)
 *  
 * @method int                getId()                    Type: integer(4), primary key
 * @method string             getLocale()                Type: string(50)
 * @method string             getTableClass()            Type: string(250)
 * @method string             getFieldName()             Type: string(250)
 * @method int                getFieldId()               Type: integer(4)
 * @method string             getTrlContent()            Type: string
 * @method int                getOptionId()              Type: integer(4)
 *  
 * @method ExtTranslations    setId(int $val)            Type: integer(4), primary key
 * @method ExtTranslations    setLocale(string $val)     Type: string(50)
 * @method ExtTranslations    setTableClass(string $val) Type: string(250)
 * @method ExtTranslations    setFieldName(string $val)  Type: string(250)
 * @method ExtTranslations    setFieldId(int $val)       Type: integer(4)
 * @method ExtTranslations    setTrlContent(string $val) Type: string
 * @method ExtTranslations    setOptionId(int $val)      Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtTranslations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ext_translations');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('locale', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('table_class', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('field_name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('field_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('trl_content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}