<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Task', 'doctrine');

/**
 * BaseTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $id                          Type: integer(4), primary key
 * @property int        $type                        Type: integer(4)
 * @property int        $creator_user_id             Type: integer(4)
 * @property int        $owner_user_id               Type: integer(4)
 * @property int        $sheet_id                    Type: integer(4)
 * @property int        $duration                    Type: integer(4)
 * @property string     $start_date                  Type: string
 * @property string     $end_date                    Type: string
 * @property int        $priority                    Type: integer(4)
 * @property int        $is_leader                   Type: integer(4)
 * @property int        $active                      Type: integer(4)
 * @property int        $status                      Type: integer(4)
 * @property string     $last_update                 Type: string
 * @property string     $date_created                Type: string
 * @property string     $remarks                     Type: string
 * @property int        $application_id              Type: integer(4)
 * @property int        $task_stage                  Type: integer(4)
 * @property FormEntry  $FormEntry                   
 * @property CfUser     $Owner                       
 * @property CfUser     $Creator                     
 *  
 * @method int          getId()                      Type: integer(4), primary key
 * @method int          getType()                    Type: integer(4)
 * @method int          getCreatorUserId()           Type: integer(4)
 * @method int          getOwnerUserId()             Type: integer(4)
 * @method int          getSheetId()                 Type: integer(4)
 * @method int          getDuration()                Type: integer(4)
 * @method string       getStartDate()               Type: string
 * @method string       getEndDate()                 Type: string
 * @method int          getPriority()                Type: integer(4)
 * @method int          getIsLeader()                Type: integer(4)
 * @method int          getActive()                  Type: integer(4)
 * @method int          getStatus()                  Type: integer(4)
 * @method string       getLastUpdate()              Type: string
 * @method string       getDateCreated()             Type: string
 * @method string       getRemarks()                 Type: string
 * @method int          getApplicationId()           Type: integer(4)
 * @method int          getTaskStage()               Type: integer(4)
 * @method FormEntry    getFormEntry()               
 * @method CfUser       getOwner()                   
 * @method CfUser       getCreator()                 
 *  
 * @method Task         setId(int $val)              Type: integer(4), primary key
 * @method Task         setType(int $val)            Type: integer(4)
 * @method Task         setCreatorUserId(int $val)   Type: integer(4)
 * @method Task         setOwnerUserId(int $val)     Type: integer(4)
 * @method Task         setSheetId(int $val)         Type: integer(4)
 * @method Task         setDuration(int $val)        Type: integer(4)
 * @method Task         setStartDate(string $val)    Type: string
 * @method Task         setEndDate(string $val)      Type: string
 * @method Task         setPriority(int $val)        Type: integer(4)
 * @method Task         setIsLeader(int $val)        Type: integer(4)
 * @method Task         setActive(int $val)          Type: integer(4)
 * @method Task         setStatus(int $val)          Type: integer(4)
 * @method Task         setLastUpdate(string $val)   Type: string
 * @method Task         setDateCreated(string $val)  Type: string
 * @method Task         setRemarks(string $val)      Type: string
 * @method Task         setApplicationId(int $val)   Type: integer(4)
 * @method Task         setTaskStage(int $val)       Type: integer(4)
 * @method Task         setFormEntry(FormEntry $val) 
 * @method Task         setOwner(CfUser $val)        
 * @method Task         setCreator(CfUser $val)      
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('creator_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('owner_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sheet_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('duration', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('start_date', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('end_date', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_leader', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('active', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('last_update', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('date_created', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('remarks', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('task_stage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
          $this->hasColumn('task_application_slug', 'string', null, array(
          'type' => 'string',
          'fixed' => 0,
          'unsigned' => false,
          'primary' => false,
          'notnull' => true,
          'autoincrement' => false,
          'length' => '',
          ));
          $this->hasColumn('group_id', 'integer', 4, array(
               'type' => 'integer',
               'fixed' => 0,
               'unsigned' => false,
               'primary' => false,
               'notnull' => false,
               'autoincrement' => false,
               'length' => 4,
           ));
     }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FormEntry as Application', array(
             'local' => 'application_id',
             'foreign' => 'id'));

        $this->hasOne('CfUser as Owner', array(
             'local' => 'owner_user_id',
             'foreign' => 'nid'));

        $this->hasOne('CfUser as Creator', array(
             'local' => 'creator_user_id',
             'foreign' => 'nid'));
    }
}