<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApFormPayments', 'doctrine');

/**
 * BaseApFormPayments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int             $afp_id                             Type: integer(4), primary key
 * @property int             $form_id                            Type: integer(4)
 * @property int             $record_id                          Type: integer(4)
 * @property string          $payment_id                         Type: string(255)
 * @property string          $date_created                       Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string          $payment_date                       Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string          $payment_status                     Type: string(255)
 * @property string          $payment_fullname                   Type: string(255)
 * @property float           $payment_amount                     Type: decimal(62), default "0.00"
 * @property string          $payment_currency                   Type: string(3), default "usd"
 * @property int             $payment_test_mode                  Type: integer(4), default "0"
 * @property string          $payment_merchant_type              Type: string(25)
 * @property int             $status                             Type: integer(4), default "1"
 * @property string          $billing_street                     Type: string(255)
 * @property string          $billing_city                       Type: string(255)
 * @property string          $billing_state                      Type: string(255)
 * @property string          $billing_zipcode                    Type: string(255)
 * @property string          $billing_country                    Type: string(255)
 * @property int             $same_shipping_address              Type: integer(4), default "1"
 * @property string          $shipping_street                    Type: string(255)
 * @property string          $shipping_city                      Type: string(255)
 * @property string          $shipping_state                     Type: string(255)
 * @property string          $shipping_zipcode                   Type: string(255)
 * @property string          $shipping_country                   Type: string(255)
 *  
 * @method int               getAfpId()                          Type: integer(4), primary key
 * @method int               getFormId()                         Type: integer(4)
 * @method int               getRecordId()                       Type: integer(4)
 * @method string            getPaymentId()                      Type: string(255)
 * @method string            getDateCreated()                    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string            getPaymentDate()                    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string            getPaymentStatus()                  Type: string(255)
 * @method string            getPaymentFullname()                Type: string(255)
 * @method float             getPaymentAmount()                  Type: decimal(62), default "0.00"
 * @method string            getPaymentCurrency()                Type: string(3), default "usd"
 * @method int               getPaymentTestMode()                Type: integer(4), default "0"
 * @method string            getPaymentMerchantType()            Type: string(25)
 * @method int               getStatus()                         Type: integer(4), default "1"
 * @method string            getBillingStreet()                  Type: string(255)
 * @method string            getBillingCity()                    Type: string(255)
 * @method string            getBillingState()                   Type: string(255)
 * @method string            getBillingZipcode()                 Type: string(255)
 * @method string            getBillingCountry()                 Type: string(255)
 * @method int               getSameShippingAddress()            Type: integer(4), default "1"
 * @method string            getShippingStreet()                 Type: string(255)
 * @method string            getShippingCity()                   Type: string(255)
 * @method string            getShippingState()                  Type: string(255)
 * @method string            getShippingZipcode()                Type: string(255)
 * @method string            getShippingCountry()                Type: string(255)
 *  
 * @method ApFormPayments    setAfpId(int $val)                  Type: integer(4), primary key
 * @method ApFormPayments    setFormId(int $val)                 Type: integer(4)
 * @method ApFormPayments    setRecordId(int $val)               Type: integer(4)
 * @method ApFormPayments    setPaymentId(string $val)           Type: string(255)
 * @method ApFormPayments    setDateCreated(string $val)         Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method ApFormPayments    setPaymentDate(string $val)         Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method ApFormPayments    setPaymentStatus(string $val)       Type: string(255)
 * @method ApFormPayments    setPaymentFullname(string $val)     Type: string(255)
 * @method ApFormPayments    setPaymentAmount(float $val)        Type: decimal(62), default "0.00"
 * @method ApFormPayments    setPaymentCurrency(string $val)     Type: string(3), default "usd"
 * @method ApFormPayments    setPaymentTestMode(int $val)        Type: integer(4), default "0"
 * @method ApFormPayments    setPaymentMerchantType(string $val) Type: string(25)
 * @method ApFormPayments    setStatus(int $val)                 Type: integer(4), default "1"
 * @method ApFormPayments    setBillingStreet(string $val)       Type: string(255)
 * @method ApFormPayments    setBillingCity(string $val)         Type: string(255)
 * @method ApFormPayments    setBillingState(string $val)        Type: string(255)
 * @method ApFormPayments    setBillingZipcode(string $val)      Type: string(255)
 * @method ApFormPayments    setBillingCountry(string $val)      Type: string(255)
 * @method ApFormPayments    setSameShippingAddress(int $val)    Type: integer(4), default "1"
 * @method ApFormPayments    setShippingStreet(string $val)      Type: string(255)
 * @method ApFormPayments    setShippingCity(string $val)        Type: string(255)
 * @method ApFormPayments    setShippingState(string $val)       Type: string(255)
 * @method ApFormPayments    setShippingZipcode(string $val)     Type: string(255)
 * @method ApFormPayments    setShippingCountry(string $val)     Type: string(255)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApFormPayments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_form_payments');
        $this->hasColumn('afp_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('record_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('payment_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('date_created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('payment_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('payment_status', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('payment_fullname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('payment_amount', 'decimal', 62, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 62,
             'scale' => '2',
             ));
        $this->hasColumn('payment_currency', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'usd',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('payment_test_mode', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('payment_merchant_type', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('billing_street', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('billing_city', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('billing_state', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('billing_zipcode', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('billing_country', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('same_shipping_address', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('shipping_street', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('shipping_city', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('shipping_state', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('shipping_zipcode', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('shipping_country', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));

        $this->hasColumn('narration', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('others', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('debit_MSISDN', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('invoice_id', 'integer', 4, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 4,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        
        $this->hasOne('MfInvoice', array(
             'local' => 'invoice_id',
             'foreign' => 'id'));

          $this->hasOne('ApForms', array(
          'local' => 'form_id',
          'foreign' => 'form_id'));
      }
}
