<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApReports', 'doctrine');

/**
 * BaseApReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $form_id                        Type: integer(4), primary key
 * @property string     $report_access_key              Type: string(100)
 *  
 * @method int          getFormId()                     Type: integer(4), primary key
 * @method string       getReportAccessKey()            Type: string(100)
 *  
 * @method ApReports    setFormId(int $val)             Type: integer(4), primary key
 * @method ApReports    setReportAccessKey(string $val) Type: string(100)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApReports extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_reports');
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('report_access_key', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}