<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ReportFilters', 'doctrine');

/**
 * BaseReportFilters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $id                    Type: integer(4), primary key
 * @property int            $report_id             Type: integer(4)
 * @property int            $element_id            Type: integer(4)
 * @property int            $exclusive             Type: integer(4)
 * @property string         $value                 Type: string
 *  
 * @method int              getId()                Type: integer(4), primary key
 * @method int              getReportId()          Type: integer(4)
 * @method int              getElementId()         Type: integer(4)
 * @method int              getExclusive()         Type: integer(4)
 * @method string           getValue()             Type: string
 *  
 * @method ReportFilters    setId(int $val)        Type: integer(4), primary key
 * @method ReportFilters    setReportId(int $val)  Type: integer(4)
 * @method ReportFilters    setElementId(int $val) Type: integer(4)
 * @method ReportFilters    setExclusive(int $val) Type: integer(4)
 * @method ReportFilters    setValue(string $val)  Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReportFilters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('report_filters');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('report_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('exclusive', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}