<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApElementOptions', 'doctrine');

/**
 * BaseApElementOptions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $aeo_id                      Type: integer(4), primary key
 * @property int               $form_id                     Type: integer(4), default "0"
 * @property int               $element_id                  Type: integer(4), default "0"
 * @property int               $option_id                   Type: integer(4), default "0"
 * @property int               $position                    Type: integer(4), default "0"
 * @property string            $option_text                 Type: string
 * @property int               $option_is_default           Type: integer(4), default "0"
 * @property int               $live                        Type: integer(4), default "1"
 *  
 * @method int                 getAeoId()                   Type: integer(4), primary key
 * @method int                 getFormId()                  Type: integer(4), default "0"
 * @method int                 getElementId()               Type: integer(4), default "0"
 * @method int                 getOptionId()                Type: integer(4), default "0"
 * @method int                 getPosition()                Type: integer(4), default "0"
 * @method string              getOptionText()              Type: string
 * @method int                 getOptionIsDefault()         Type: integer(4), default "0"
 * @method int                 getLive()                    Type: integer(4), default "1"
 *  
 * @method ApElementOptions    setAeoId(int $val)           Type: integer(4), primary key
 * @method ApElementOptions    setFormId(int $val)          Type: integer(4), default "0"
 * @method ApElementOptions    setElementId(int $val)       Type: integer(4), default "0"
 * @method ApElementOptions    setOptionId(int $val)        Type: integer(4), default "0"
 * @method ApElementOptions    setPosition(int $val)        Type: integer(4), default "0"
 * @method ApElementOptions    setOptionText(string $val)   Type: string
 * @method ApElementOptions    setOptionIsDefault(int $val) Type: integer(4), default "0"
 * @method ApElementOptions    setLive(int $val)            Type: integer(4), default "1"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApElementOptions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_element_options');
        $this->hasColumn('aeo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('option_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('option', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('option_is_default', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('live', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}