<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UploadAdditional', 'doctrine');

/**
 * BaseUploadAdditional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $id                        Type: integer(8), primary key
 * @property int               $application_id            Type: integer(4)
 * @property int               $form_id                   Type: integer(4)
 * @property int               $entry_id                  Type: integer(4)
 *  
 * @method int                 getId()                    Type: integer(8), primary key
 * @method int                 getApplicationId()         Type: integer(4)
 * @method int                 getFormId()                Type: integer(4)
 * @method int                 getEntryId()               Type: integer(4)
 *  
 * @method UploadAdditional    setId(int $val)            Type: integer(8), primary key
 * @method UploadAdditional    setApplicationId(int $val) Type: integer(4)
 * @method UploadAdditional    setFormId(int $val)        Type: integer(4)
 * @method UploadAdditional    setEntryId(int $val)       Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUploadAdditional extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('upload_additional');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entry_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}