<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApGridColumns', 'doctrine');

/**
 * BaseApGridColumns
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $agc_id                     Type: integer(4), primary key
 * @property string         $element_name               Type: string(255)
 * @property string         $form_id                    Type: string(255)
 * @property string         $chart_id                   Type: string(255)
 * @property string         $position                   Type: string(255)
 *  
 * @method int              getAgcId()                  Type: integer(4), primary key
 * @method string           getElementName()            Type: string(255)
 * @method string           getFormId()                 Type: string(255)
 * @method string           getChartId()                Type: string(255)
 * @method string           getPosition()               Type: string(255)
 *  
 * @method ApGridColumns    setAgcId(int $val)          Type: integer(4), primary key
 * @method ApGridColumns    setElementName(string $val) Type: string(255)
 * @method ApGridColumns    setFormId(string $val)      Type: string(255)
 * @method ApGridColumns    setChartId(string $val)     Type: string(255)
 * @method ApGridColumns    setPosition(string $val)    Type: string(255)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApGridColumns extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_grid_columns');
        $this->hasColumn('agc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('element_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('form_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('chart_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}