<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGuardUserPermission', 'doctrine');

/**
 * BaseSfGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                    $user_id                                     Type: integer(8), primary key
 * @property int                    $permission_id                               Type: integer(8), primary key
 * @property string                 $created_at                                  Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                 $updated_at                                  Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property SfGuardPermission      $SfGuardPermission                           
 * @property SfGuardUser            $SfGuardUser                                 
 *  
 * @method int                      getUserId()                                  Type: integer(8), primary key
 * @method int                      getPermissionId()                            Type: integer(8), primary key
 * @method string                   getCreatedAt()                               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                   getUpdatedAt()                               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardPermission        getSfGuardPermission()                       
 * @method SfGuardUser              getSfGuardUser()                             
 *  
 * @method SfGuardUserPermission    setUserId(int $val)                          Type: integer(8), primary key
 * @method SfGuardUserPermission    setPermissionId(int $val)                    Type: integer(8), primary key
 * @method SfGuardUserPermission    setCreatedAt(string $val)                    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUserPermission    setUpdatedAt(string $val)                    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method SfGuardUserPermission    setSfGuardPermission(SfGuardPermission $val) 
 * @method SfGuardUserPermission    setSfGuardUser(SfGuardUser $val)             
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGuardUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_permission');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('permission_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardPermission', array(
             'local' => 'permission_id',
             'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}