<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Content', 'doctrine');

/**
 * BaseContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                              Type: integer(4), primary key
 * @property int          $parent_id                       Type: integer(4), default "0"
 * @property int          $type_id                         Type: integer(4)
 * @property string       $created_on                      Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property int          $published                       Type: integer(1)
 * @property int          $menu_index                      Type: integer(1)
 * @property string       $url                             Type: string(255)
 * @property string       $top_article                     Type: string
 * @property string       $menu_title                      Type: string(255)
 * @property string       $breadcrumb_title                Type: string(255)
 * @property string       $last_modified_on                Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property int          $visibility                      Type: integer(4), default "1"
 * @property int          $deleted                         Type: integer(4), default "0"
 * @property ContentType  $ContentType                     
 *  
 * @method int            getId()                          Type: integer(4), primary key
 * @method int            getParentId()                    Type: integer(4), default "0"
 * @method int            getTypeId()                      Type: integer(4)
 * @method string         getCreatedOn()                   Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method int            getPublished()                   Type: integer(1)
 * @method int            getMenuIndex()                   Type: integer(1)
 * @method string         getUrl()                         Type: string(255)
 * @method string         getTopArticle()                  Type: string
 * @method string         getMenuTitle()                   Type: string(255)
 * @method string         getBreadcrumbTitle()             Type: string(255)
 * @method string         getLastModifiedOn()              Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method int            getVisibility()                  Type: integer(4), default "1"
 * @method int            getDeleted()                     Type: integer(4), default "0"
 * @method ContentType    getContentType()                 
 *  
 * @method Content        setId(int $val)                  Type: integer(4), primary key
 * @method Content        setParentId(int $val)            Type: integer(4), default "0"
 * @method Content        setTypeId(int $val)              Type: integer(4)
 * @method Content        setCreatedOn(string $val)        Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Content        setPublished(int $val)           Type: integer(1)
 * @method Content        setMenuIndex(int $val)           Type: integer(1)
 * @method Content        setUrl(string $val)              Type: string(255)
 * @method Content        setTopArticle(string $val)       Type: string
 * @method Content        setMenuTitle(string $val)        Type: string(255)
 * @method Content        setBreadcrumbTitle(string $val)  Type: string(255)
 * @method Content        setLastModifiedOn(string $val)   Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Content        setVisibility(int $val)          Type: integer(4), default "1"
 * @method Content        setDeleted(int $val)             Type: integer(4), default "0"
 * @method Content        setContentType(ContentType $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('published', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('menu_index', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('top_article', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('menu_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('breadcrumb_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('last_modified_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('visibility', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deleted', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContentType', array(
             'local' => 'type_id',
             'foreign' => 'id'));
    }
}