<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MultiplierFees', 'doctrine');

/**
 * BaseMenus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int     $id                   Type: integer(4), primary key
 * @property string  $title                Type: string
 * @property int     $order_no             Type: integer(4)
 *  
 * @method int       getId()               Type: integer(4), primary key
 * @method string    getTitle()            Type: string
 * @method int       getOrderNo()          Type: integer(4)
 *  
 * @method Menus     setId(int $val)       Type: integer(4), primary key
 * @method Menus     setTitle(string $val) Type: string
 * @method Menus     setOrderNo(int $val)  Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMultiplierFees extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('multiplier_fees');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('service_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('field_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('multiplier_amount', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}