<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApFormGroups', 'doctrine');

/**
 * BaseApFormGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int           $id                            Type: integer(4), primary key
 * @property int           $form_id                       Type: integer(4)
 * @property int           $group_id                      Type: integer(4)
 * @property ApForms       $ApForms                       
 * @property FormGroups    $FormGroups                    
 *  
 * @method int             getId()                        Type: integer(4), primary key
 * @method int             getFormId()                    Type: integer(4)
 * @method int             getGroupId()                   Type: integer(4)
 * @method ApForms         getApForms()                   
 * @method FormGroups      getFormGroups()                
 *  
 * @method ApFormGroups    setId(int $val)                Type: integer(4), primary key
 * @method ApFormGroups    setFormId(int $val)            Type: integer(4)
 * @method ApFormGroups    setGroupId(int $val)           Type: integer(4)
 * @method ApFormGroups    setApForms(ApForms $val)       
 * @method ApFormGroups    setFormGroups(FormGroups $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApFormGroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_form_groups');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ApForms', array(
             'local' => 'form_id',
             'foreign' => 'form_id'));

        $this->hasOne('FormGroups', array(
             'local' => 'group_id',
             'foreign' => 'group_id'));
    }
}