<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActivityReport', 'doctrine');

/**
 * BaseActivityReport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int             $id                  Type: integer(8), primary key
 * @property int             $total               Type: integer(4)
 * @property string          $code                Type: string
 * @property string          $type                Type: string
 *  
 * @method int               getId()              Type: integer(8), primary key
 * @method int               getTotal()           Type: integer(4)
 * @method string            getCode()            Type: string
 * @method string            getType()            Type: string
 *  
 * @method ActivityReport    setId(int $val)      Type: integer(8), primary key
 * @method ActivityReport    setTotal(int $val)   Type: integer(4)
 * @method ActivityReport    setCode(string $val) Type: string
 * @method ActivityReport    setType(string $val) Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityReport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_report');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('total', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}