<?php

/**
 * BasemfUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $user_id                  Type: integer, primary key
 * @property int            $form_id                  Type: integer
 * @property int            $entry_id                 Type: integer
 * @property sfGuardUser    $User                     
 *  
 * @method int              getUserId()               Type: integer, primary key
 * @method int              getFormId()               Type: integer
 * @method int              getEntryId()              Type: integer
 * @method sfGuardUser      getUser()                 
 *  
 * @method mfUserProfile    setUserId(int $val)       Type: integer, primary key
 * @method mfUserProfile    setFormId(int $val)       Type: integer
 * @method mfUserProfile    setEntryId(int $val)      Type: integer
 * @method mfUserProfile    setUser(sfGuardUser $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemfUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_user_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('form_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('entry_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deleted', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('form_data', 'json', null, array(
             'type' => 'json',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}