<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                 $id                       Type: integer(4), primary key
 * @property int                 $user_id                  Type: integer(4)
 * @property string              $email                    Type: string(80)
 * @property string              $fullname                 Type: string(80)
 * @property string              $mobile                   Type: string(80)
 * @property string              $validate                 Type: string(17)
 * @property int                 $registeras               Type: integer(4)
 * @property sfGuardUser         $User                     
 *  
 * @method int                   getId()                   Type: integer(4), primary key
 * @method int                   getUserId()               Type: integer(4)
 * @method string                getEmail()                Type: string(80)
 * @method string                getFullname()             Type: string(80)
 * @method string                getMobile()               Type: string(80)
 * @method string                getValidate()             Type: string(17)
 * @method int                   getRegisteras()           Type: integer(4)
 * @method sfGuardUser           getUser()                 
 *  
 * @method sfGuardUserProfile    setId(int $val)           Type: integer(4), primary key
 * @method sfGuardUserProfile    setUserId(int $val)       Type: integer(4)
 * @method sfGuardUserProfile    setEmail(string $val)     Type: string(80)
 * @method sfGuardUserProfile    setFullname(string $val)  Type: string(80)
 * @method sfGuardUserProfile    setMobile(string $val)    Type: string(80)
 * @method sfGuardUserProfile    setValidate(string $val)  Type: string(17)
 * @method sfGuardUserProfile    setRegisteras(int $val)   Type: integer(4)
 * @method sfGuardUserProfile    setUser(sfGuardUser $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('fullname', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('mobile', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('validate', 'string', 17, array(
             'type' => 'string',
             'length' => 17,
             ));
        $this->hasColumn('registeras', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('profile_pic', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}