<?php

/**
 * ApForms form base class.
 *
 * @method ApForms getObject() Returns the current form's model object
 *
 * @package    permitflow
 * @subpackage form
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseApFormsForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'form_id'                               => new sfWidgetFormInputHidden(),
      'logic_permission_enable'               => new sfWidgetFormInputText(),
      'logic_workflow_enable'                 => new sfWidgetFormInputText(),
      'form_name'                             => new sfWidgetFormTextarea(),
      'form_description'                      => new sfWidgetFormTextarea(),
      'form_name_hide'                        => new sfWidgetFormInputText(),
      'form_email'                            => new sfWidgetFormInputText(),
      'form_redirect'                         => new sfWidgetFormTextarea(),
      'form_success_message'                  => new sfWidgetFormTextarea(),
      'form_password'                         => new sfWidgetFormInputText(),
      'form_unique_ip'                        => new sfWidgetFormInputText(),
      'form_frame_height'                     => new sfWidgetFormInputText(),
      'form_has_css'                          => new sfWidgetFormInputText(),
      'form_captcha'                          => new sfWidgetFormInputText(),
      'form_active'                           => new sfWidgetFormInputText(),
      'form_review'                           => new sfWidgetFormInputText(),
      'form_default_application'              => new sfWidgetFormInputText(),
      'esl_from_name'                         => new sfWidgetFormTextarea(),
      'esl_from_email_address'                => new sfWidgetFormInputText(),
      'esl_subject'                           => new sfWidgetFormTextarea(),
      'esl_content'                           => new sfWidgetFormTextarea(),
      'esl_plain_text'                        => new sfWidgetFormInputText(),
      'esr_email_address'                     => new sfWidgetFormInputText(),
      'esr_from_name'                         => new sfWidgetFormTextarea(),
      'esr_from_email_address'                => new sfWidgetFormInputText(),
      'esr_subject'                           => new sfWidgetFormTextarea(),
      'esr_content'                           => new sfWidgetFormTextarea(),
      'esr_plain_text'                        => new sfWidgetFormInputText(),
      'form_tags'                             => new sfWidgetFormInputText(),
      'form_redirect_enable'                  => new sfWidgetFormInputText(),
      'form_unique_ip_maxcount'               => new sfWidgetFormInputText(),
      'form_unique_ip_period'                 => new sfWidgetFormInputText(),
      'form_captcha_type'                     => new sfWidgetFormInputText(),
      'form_theme_id'                         => new sfWidgetFormInputText(),
      'form_resume_enable'                    => new sfWidgetFormInputText(),
      'form_resume_subject'                   => new sfWidgetFormInputText(),
      'form_resume_content'                   => new sfWidgetFormTextarea(),
      'form_resume_from_name'                 => new sfWidgetFormTextarea(),
      'form_resume_from_email_address'        => new sfWidgetFormInputText(),
      'form_custom_script_enable'             => new sfWidgetFormInputText(),
      'form_custom_script_url'                => new sfWidgetFormInputText(),
      'form_limit_enable'                     => new sfWidgetFormInputText(),
      'form_limit'                            => new sfWidgetFormInputText(),
      'form_label_alignment'                  => new sfWidgetFormInputText(),
      'form_language'                         => new sfWidgetFormInputText(),
      'form_page_total'                       => new sfWidgetFormInputText(),
      'form_lastpage_title'                   => new sfWidgetFormInputText(),
      'form_submit_primary_text'              => new sfWidgetFormInputText(),
      'form_submit_secondary_text'            => new sfWidgetFormInputText(),
      'form_submit_primary_img'               => new sfWidgetFormInputText(),
      'form_submit_secondary_img'             => new sfWidgetFormInputText(),
      'form_submit_use_image'                 => new sfWidgetFormInputText(),
      'form_review_primary_text'              => new sfWidgetFormInputText(),
      'form_review_secondary_text'            => new sfWidgetFormInputText(),
      'form_review_primary_img'               => new sfWidgetFormInputText(),
      'form_review_secondary_img'             => new sfWidgetFormInputText(),
      'form_review_use_image'                 => new sfWidgetFormInputText(),
      'form_review_title'                     => new sfWidgetFormTextarea(),
      'form_review_description'               => new sfWidgetFormTextarea(),
      'form_pagination_type'                  => new sfWidgetFormInputText(),
      'form_schedule_enable'                  => new sfWidgetFormInputText(),
      'form_schedule_start_date'              => new sfWidgetFormDate(),
      'form_schedule_end_date'                => new sfWidgetFormDate(),
      'form_schedule_start_hour'              => new sfWidgetFormTime(),
      'form_schedule_end_hour'                => new sfWidgetFormTime(),
      'esl_enable'                            => new sfWidgetFormInputText(),
      'esr_enable'                            => new sfWidgetFormInputText(),
      'payment_enable_merchant'               => new sfWidgetFormInputText(),
      'payment_merchant_type'                 => new sfWidgetFormInputText(),
      'payment_paypal_email'                  => new sfWidgetFormInputText(),
      'payment_paypal_language'               => new sfWidgetFormInputText(),
      'payment_currency'                      => new sfWidgetFormInputText(),
      'payment_show_total'                    => new sfWidgetFormInputText(),
      'payment_total_location'                => new sfWidgetFormInputText(),
      'payment_enable_recurring'              => new sfWidgetFormInputText(),
      'payment_recurring_cycle'               => new sfWidgetFormInputText(),
      'payment_recurring_unit'                => new sfWidgetFormInputText(),
      'payment_price_type'                    => new sfWidgetFormInputText(),
      'payment_price_amount'                  => new sfWidgetFormInputText(),
      'payment_price_name'                    => new sfWidgetFormInputText(),
      'payment_enable_discount'               => new sfWidgetFormInputText(),
      'logic_field_enable'                    => new sfWidgetFormInputText(),
      'logic_page_enable'                     => new sfWidgetFormInputText(),
      'payment_enable_trial'                  => new sfWidgetFormInputText(),
      'payment_trial_period'                  => new sfWidgetFormInputText(),
      'payment_trial_unit'                    => new sfWidgetFormInputText(),
      'payment_trial_amount'                  => new sfWidgetFormInputText(),
      'payment_pesapal_live_secret_key'       => new sfWidgetFormInputText(),
      'payment_pesapal_live_public_key'       => new sfWidgetFormInputText(),
      'payment_pesapal_test_secret_key'       => new sfWidgetFormInputText(),
      'payment_pesapal_test_public_key'       => new sfWidgetFormInputText(),
      'payment_pesapal_enable_test_mode'      => new sfWidgetFormInputText(),
      'payment_paypal_enable_test_mode'       => new sfWidgetFormInputText(),
      'payment_enable_invoice'                => new sfWidgetFormInputText(),
      'payment_invoice_email'                 => new sfWidgetFormInputText(),
      'payment_delay_notifications'           => new sfWidgetFormInputText(),
      'payment_ask_billing'                   => new sfWidgetFormInputText(),
      'payment_ask_shipping'                  => new sfWidgetFormInputText(),
      'payment_discount_element_id'           => new sfWidgetFormInputText(),
      'form_disabled_message'                 => new sfWidgetFormTextarea(),
      'payment_enable_tax'                    => new sfWidgetFormInputText(),
      'payment_tax_rate'                      => new sfWidgetFormInputText(),
      'payment_tax_amount'                    => new sfWidgetFormInputText(),
      'payment_discount_code'                 => new sfWidgetFormInputText(),
      'webhook_enable'                        => new sfWidgetFormInputText(),
      'payment_discount_type'                 => new sfWidgetFormInputText(),
      'payment_discount_amount'               => new sfWidgetFormInputText(),
      'logic_email_enable'                    => new sfWidgetFormInputText(),
      'form_stage'                            => new sfWidgetFormInputText(),
      'form_group'                            => new sfWidgetFormInputText(),
      'form_department'                       => new sfWidgetFormInputText(),
      'form_department_stage'                 => new sfWidgetFormInputText(),
      'form_idn'                              => new sfWidgetFormInputText(),
      'form_type'                             => new sfWidgetFormInputText(),
      'form_code'                             => new sfWidgetFormInputText(),
      'payment_cellulant_checkout_url'        => new sfWidgetFormInputText(),
      'payment_cellulant_merchant_username'   => new sfWidgetFormInputText(),
      'payment_cellulant_merchant_password'   => new sfWidgetFormInputText(),
      'payment_cellulant_service_id'          => new sfWidgetFormInputText(),
      'payment_jambopay_business'             => new sfWidgetFormInputText(),
      'payment_jambopay_shared_key'           => new sfWidgetFormInputText(),
      'logic_webhook_enable'                  => new sfWidgetFormInputText(),
      'logic_success_enable'                  => new sfWidgetFormInputText(),
      'esl_bcc_email_address'                 => new sfWidgetFormTextarea(),
      'esl_replyto_email_address'             => new sfWidgetFormTextarea(),
      'esl_pdf_enable'                        => new sfWidgetFormInputText(),
      'esl_pdf_content'                       => new sfWidgetFormTextarea(),
      'esr_bcc_email_address'                 => new sfWidgetFormTextarea(),
      'esr_replyto_email_address'             => new sfWidgetFormInputText(),
      'esr_pdf_enable'                        => new sfWidgetFormInputText(),
      'esr_pdf_content'                       => new sfWidgetFormTextarea(),
      'payment_enable_setupfee'               => new sfWidgetFormInputText(),
      'payment_setupfee_amount'               => new sfWidgetFormInputText(),
      'payment_stripe_live_secret_key'        => new sfWidgetFormInputText(),
      'payment_stripe_live_public_key'        => new sfWidgetFormInputText(),
      'payment_stripe_test_secret_key'        => new sfWidgetFormInputText(),
      'payment_stripe_test_public_key'        => new sfWidgetFormInputText(),
      'payment_stripe_enable_test_mode'       => new sfWidgetFormInputText(),
      'payment_stripe_enable_receipt'         => new sfWidgetFormInputText(),
      'payment_stripe_receipt_element_id'     => new sfWidgetFormInputText(),
      'payment_authorizenet_live_apiloginid'  => new sfWidgetFormInputText(),
      'payment_authorizenet_live_transkey'    => new sfWidgetFormInputText(),
      'payment_authorizenet_test_apiloginid'  => new sfWidgetFormInputText(),
      'payment_authorizenet_test_transkey'    => new sfWidgetFormInputText(),
      'payment_authorizenet_enable_test_mode' => new sfWidgetFormInputText(),
      'payment_authorizenet_save_cc_data'     => new sfWidgetFormInputText(),
      'payment_braintree_live_merchant_id'    => new sfWidgetFormInputText(),
      'payment_braintree_live_public_key'     => new sfWidgetFormInputText(),
      'payment_braintree_live_private_key'    => new sfWidgetFormInputText(),
      'payment_braintree_live_encryption_key' => new sfWidgetFormTextarea(),
      'payment_braintree_test_merchant_id'    => new sfWidgetFormInputText(),
      'payment_braintree_test_public_key'     => new sfWidgetFormInputText(),
      'payment_braintree_test_private_key'    => new sfWidgetFormInputText(),
      'payment_braintree_test_encryption_key' => new sfWidgetFormTextarea(),
      'payment_braintree_enable_test_mode'    => new sfWidgetFormInputText(),
      'payment_paypal_rest_live_clientid'     => new sfWidgetFormInputText(),
      'payment_paypal_rest_live_secret_key'   => new sfWidgetFormInputText(),
      'payment_paypal_rest_test_clientid'     => new sfWidgetFormInputText(),
      'payment_paypal_rest_test_secret_key'   => new sfWidgetFormInputText(),
      'payment_paypal_rest_enable_test_mode'  => new sfWidgetFormInputText(),
      'payment_discount_max_usage'            => new sfWidgetFormInputText(),
      'payment_discount_expiry_date'          => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'form_id'                               => new sfValidatorChoice(array('choices' => array($this->getObject()->get('form_id')), 'empty_value' => $this->getObject()->get('form_id'), 'required' => false)),
      'logic_permission_enable'               => new sfValidatorInteger(array('required' => false)),
      'logic_workflow_enable'                 => new sfValidatorInteger(array('required' => false)),
      'form_name'                             => new sfValidatorString(array('required' => false)),
      'form_description'                      => new sfValidatorString(array('required' => false)),
      'form_name_hide'                        => new sfValidatorInteger(array('required' => false)),
      'form_email'                            => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_redirect'                         => new sfValidatorString(array('required' => false)),
      'form_success_message'                  => new sfValidatorString(array('required' => false)),
      'form_password'                         => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'form_unique_ip'                        => new sfValidatorInteger(array('required' => false)),
      'form_frame_height'                     => new sfValidatorInteger(array('required' => false)),
      'form_has_css'                          => new sfValidatorInteger(array('required' => false)),
      'form_captcha'                          => new sfValidatorInteger(array('required' => false)),
      'form_active'                           => new sfValidatorInteger(array('required' => false)),
      'form_review'                           => new sfValidatorInteger(array('required' => false)),
      'form_default_application'              => new sfValidatorInteger(array('required' => false)),
      'esl_from_name'                         => new sfValidatorString(array('required' => false)),
      'esl_from_email_address'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'esl_subject'                           => new sfValidatorString(array('required' => false)),
      'esl_content'                           => new sfValidatorString(array('required' => false)),
      'esl_plain_text'                        => new sfValidatorInteger(array('required' => false)),
      'esr_email_address'                     => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'esr_from_name'                         => new sfValidatorString(array('required' => false)),
      'esr_from_email_address'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'esr_subject'                           => new sfValidatorString(array('required' => false)),
      'esr_content'                           => new sfValidatorString(array('required' => false)),
      'esr_plain_text'                        => new sfValidatorInteger(array('required' => false)),
      'form_tags'                             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_redirect_enable'                  => new sfValidatorInteger(array('required' => false)),
      'form_unique_ip_maxcount'               => new sfValidatorInteger(array('required' => false)),
      'form_unique_ip_period'                 => new sfValidatorInteger(array('required' => false)),
      'form_captcha_type'                     => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'form_theme_id'                         => new sfValidatorInteger(array('required' => false)),
      'form_resume_enable'                    => new sfValidatorInteger(array('required' => false)),
      'form_resume_subject'                   => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_resume_content'                   => new sfValidatorString(array('required' => false)),
      'form_resume_from_name'                 => new sfValidatorString(array('required' => false)),
      'form_resume_from_email_address'        => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_custom_script_enable'             => new sfValidatorInteger(array('required' => false)),
      'form_custom_script_url'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_limit_enable'                     => new sfValidatorInteger(array('required' => false)),
      'form_limit'                            => new sfValidatorInteger(array('required' => false)),
      'form_label_alignment'                  => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_language'                         => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'form_page_total'                       => new sfValidatorInteger(array('required' => false)),
      'form_lastpage_title'                   => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_submit_primary_text'              => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_submit_secondary_text'            => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_submit_primary_img'               => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_submit_secondary_img'             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_submit_use_image'                 => new sfValidatorInteger(array('required' => false)),
      'form_review_primary_text'              => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_review_secondary_text'            => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_review_primary_img'               => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_review_secondary_img'             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_review_use_image'                 => new sfValidatorInteger(array('required' => false)),
      'form_review_title'                     => new sfValidatorString(array('required' => false)),
      'form_review_description'               => new sfValidatorString(array('required' => false)),
      'form_pagination_type'                  => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_schedule_enable'                  => new sfValidatorInteger(array('required' => false)),
      'form_schedule_start_date'              => new sfValidatorDate(array('required' => false)),
      'form_schedule_end_date'                => new sfValidatorDate(array('required' => false)),
      'form_schedule_start_hour'              => new sfValidatorTime(array('required' => false)),
      'form_schedule_end_hour'                => new sfValidatorTime(array('required' => false)),
      'esl_enable'                            => new sfValidatorInteger(array('required' => false)),
      'esr_enable'                            => new sfValidatorInteger(array('required' => false)),
      'payment_enable_merchant'               => new sfValidatorInteger(array('required' => false)),
      'payment_merchant_type'                 => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'payment_paypal_email'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'payment_paypal_language'               => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'payment_currency'                      => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'payment_show_total'                    => new sfValidatorInteger(array('required' => false)),
      'payment_total_location'                => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'payment_enable_recurring'              => new sfValidatorInteger(array('required' => false)),
      'payment_recurring_cycle'               => new sfValidatorInteger(array('required' => false)),
      'payment_recurring_unit'                => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'payment_price_type'                    => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'payment_price_amount'                  => new sfValidatorNumber(array('required' => false)),
      'payment_price_name'                    => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'payment_enable_discount'               => new sfValidatorInteger(array('required' => false)),
      'logic_field_enable'                    => new sfValidatorInteger(array('required' => false)),
      'logic_page_enable'                     => new sfValidatorInteger(array('required' => false)),
      'payment_enable_trial'                  => new sfValidatorInteger(array('required' => false)),
      'payment_trial_period'                  => new sfValidatorInteger(array('required' => false)),
      'payment_trial_unit'                    => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'payment_trial_amount'                  => new sfValidatorNumber(array('required' => false)),
      'payment_pesapal_live_secret_key'       => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_pesapal_live_public_key'       => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_pesapal_test_secret_key'       => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_pesapal_test_public_key'       => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_pesapal_enable_test_mode'      => new sfValidatorInteger(array('required' => false)),
      'payment_paypal_enable_test_mode'       => new sfValidatorInteger(array('required' => false)),
      'payment_enable_invoice'                => new sfValidatorInteger(array('required' => false)),
      'payment_invoice_email'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'payment_delay_notifications'           => new sfValidatorInteger(array('required' => false)),
      'payment_ask_billing'                   => new sfValidatorInteger(array('required' => false)),
      'payment_ask_shipping'                  => new sfValidatorInteger(array('required' => false)),
      'payment_discount_element_id'           => new sfValidatorInteger(array('required' => false)),
      'form_disabled_message'                 => new sfValidatorString(array('required' => false)),
      'payment_enable_tax'                    => new sfValidatorInteger(array('required' => false)),
      'payment_tax_rate'                      => new sfValidatorNumber(array('required' => false)),
      'payment_tax_amount'                    => new sfValidatorNumber(array('required' => false)),
      'payment_discount_code'                 => new sfValidatorInteger(array('required' => false)),
      'webhook_enable'                        => new sfValidatorInteger(array('required' => false)),
      'payment_discount_type'                 => new sfValidatorInteger(array('required' => false)),
      'payment_discount_amount'               => new sfValidatorInteger(array('required' => false)),
      'logic_email_enable'                    => new sfValidatorInteger(array('required' => false)),
      'form_stage'                            => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_group'                            => new sfValidatorInteger(array('required' => false)),
      'form_department'                       => new sfValidatorInteger(array('required' => false)),
      'form_department_stage'                 => new sfValidatorInteger(array('required' => false)),
      'form_idn'                              => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'form_type'                             => new sfValidatorInteger(array('required' => false)),
      'form_code'                             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'payment_cellulant_checkout_url'        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_cellulant_merchant_username'   => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_cellulant_merchant_password'   => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_cellulant_service_id'          => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_jambopay_business'             => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_jambopay_shared_key'           => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'logic_webhook_enable'                  => new sfValidatorInteger(array('required' => false)),
      'logic_success_enable'                  => new sfValidatorInteger(array('required' => false)),
      'esl_bcc_email_address'                 => new sfValidatorString(array('required' => false)),
      'esl_replyto_email_address'             => new sfValidatorString(array('required' => false)),
      'esl_pdf_enable'                        => new sfValidatorInteger(array('required' => false)),
      'esl_pdf_content'                       => new sfValidatorString(array('required' => false)),
      'esr_bcc_email_address'                 => new sfValidatorString(array('required' => false)),
      'esr_replyto_email_address'             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'esr_pdf_enable'                        => new sfValidatorInteger(array('required' => false)),
      'esr_pdf_content'                       => new sfValidatorString(array('required' => false)),
      'payment_enable_setupfee'               => new sfValidatorInteger(array('required' => false)),
      'payment_setupfee_amount'               => new sfValidatorNumber(array('required' => false)),
      'payment_stripe_live_secret_key'        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_stripe_live_public_key'        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_stripe_test_secret_key'        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_stripe_test_public_key'        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_stripe_enable_test_mode'       => new sfValidatorInteger(array('required' => false)),
      'payment_stripe_enable_receipt'         => new sfValidatorInteger(array('required' => false)),
      'payment_stripe_receipt_element_id'     => new sfValidatorInteger(array('required' => false)),
      'payment_authorizenet_live_apiloginid'  => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_authorizenet_live_transkey'    => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_authorizenet_test_apiloginid'  => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_authorizenet_test_transkey'    => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_authorizenet_enable_test_mode' => new sfValidatorInteger(array('required' => false)),
      'payment_authorizenet_save_cc_data'     => new sfValidatorInteger(array('required' => false)),
      'payment_braintree_live_merchant_id'    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_braintree_live_public_key'     => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_braintree_live_private_key'    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_braintree_live_encryption_key' => new sfValidatorString(array('required' => false)),
      'payment_braintree_test_merchant_id'    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_braintree_test_public_key'     => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_braintree_test_private_key'    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'payment_braintree_test_encryption_key' => new sfValidatorString(array('required' => false)),
      'payment_braintree_enable_test_mode'    => new sfValidatorInteger(array('required' => false)),
      'payment_paypal_rest_live_clientid'     => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_paypal_rest_live_secret_key'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_paypal_rest_test_clientid'     => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_paypal_rest_test_secret_key'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'payment_paypal_rest_enable_test_mode'  => new sfValidatorInteger(array('required' => false)),
      'payment_discount_max_usage'            => new sfValidatorInteger(array('required' => false)),
      'payment_discount_expiry_date'          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ap_forms[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ApForms';
  }

}
