<?php

/**
 * ApFormElements form base class.
 *
 * @method ApFormElements getObject() Returns the current form's model object
 *
 * @package    permitflow
 * @subpackage form
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseApFormElementsForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'form_id'                             => new sfWidgetFormInputHidden(),
      'element_id'                          => new sfWidgetFormInputHidden(),
      'element_title'                       => new sfWidgetFormTextarea(),
      'element_guidelines'                  => new sfWidgetFormTextarea(),
      'element_size'                        => new sfWidgetFormInputText(),
      'element_is_required'                 => new sfWidgetFormInputText(),
      'element_is_unique'                   => new sfWidgetFormInputText(),
      'element_is_readonly'                 => new sfWidgetFormInputText(),
      'element_is_private'                  => new sfWidgetFormInputText(),
      'element_enable_placeholder'          => new sfWidgetFormInputText(),
      'element_text_default_type'           => new sfWidgetFormInputText(),
      'element_text_default_length'         => new sfWidgetFormInputText(),
      'element_text_default_random_type'    => new sfWidgetFormInputText(),
      'element_text_default_prefix'         => new sfWidgetFormInputText(),
      'element_text_default_case'           => new sfWidgetFormInputText(),
      'element_type'                        => new sfWidgetFormInputText(),
      'element_position'                    => new sfWidgetFormInputText(),
      'element_default_value'               => new sfWidgetFormTextarea(),
      'element_constraint'                  => new sfWidgetFormInputText(),
      'element_total_child'                 => new sfWidgetFormInputText(),
      'element_css_class'                   => new sfWidgetFormInputText(),
      'element_range_min'                   => new sfWidgetFormInputText(),
      'element_range_max'                   => new sfWidgetFormInputText(),
      'element_range_limit_by'              => new sfWidgetFormInputText(),
      'element_status'                      => new sfWidgetFormInputText(),
      'element_choice_columns'              => new sfWidgetFormInputText(),
      'element_choice_has_other'            => new sfWidgetFormInputText(),
      'element_choice_other_label'          => new sfWidgetFormTextarea(),
      'element_choice_limit_rule'           => new sfWidgetFormInputText(),
      'element_choice_limit_qty'            => new sfWidgetFormInputText(),
      'element_choice_limit_range_min'      => new sfWidgetFormInputText(),
      'element_choice_limit_range_max'      => new sfWidgetFormInputText(),
      'element_choice_max_entry'            => new sfWidgetFormInputText(),
      'element_time_showsecond'             => new sfWidgetFormInputText(),
      'element_time_24hour'                 => new sfWidgetFormInputText(),
      'element_address_hideline2'           => new sfWidgetFormInputText(),
      'element_address_us_only'             => new sfWidgetFormInputText(),
      'element_date_enable_range'           => new sfWidgetFormInputText(),
      'element_date_range_min'              => new sfWidgetFormDate(),
      'element_date_range_max'              => new sfWidgetFormDate(),
      'element_date_enable_selection_limit' => new sfWidgetFormInputText(),
      'element_date_selection_max'          => new sfWidgetFormInputText(),
      'element_date_past_future'            => new sfWidgetFormInputText(),
      'element_date_disable_past_future'    => new sfWidgetFormInputText(),
      'element_date_disable_weekend'        => new sfWidgetFormInputText(),
      'element_date_disable_specific'       => new sfWidgetFormInputText(),
      'element_date_disabled_list'          => new sfWidgetFormTextarea(),
      'element_file_enable_type_limit'      => new sfWidgetFormInputText(),
      'element_file_block_or_allow'         => new sfWidgetFormInputText(),
      'element_file_type_list'              => new sfWidgetFormInputText(),
      'element_file_as_attachment'          => new sfWidgetFormInputText(),
      'element_file_enable_advance'         => new sfWidgetFormInputText(),
      'element_file_auto_upload'            => new sfWidgetFormInputText(),
      'element_file_enable_multi_upload'    => new sfWidgetFormInputText(),
      'element_file_max_selection'          => new sfWidgetFormInputText(),
      'element_file_enable_size_limit'      => new sfWidgetFormInputText(),
      'element_file_size_max'               => new sfWidgetFormInputText(),
      'element_matrix_allow_multiselect'    => new sfWidgetFormInputText(),
      'element_matrix_parent_id'            => new sfWidgetFormInputText(),
      'element_submit_use_image'            => new sfWidgetFormInputText(),
      'element_submit_primary_text'         => new sfWidgetFormInputText(),
      'element_submit_secondary_text'       => new sfWidgetFormInputText(),
      'element_submit_primary_img'          => new sfWidgetFormInputText(),
      'element_submit_secondary_img'        => new sfWidgetFormInputText(),
      'element_page_title'                  => new sfWidgetFormInputText(),
      'element_page_number'                 => new sfWidgetFormInputText(),
      'element_section_display_in_email'    => new sfWidgetFormInputText(),
      'element_section_enable_scroll'       => new sfWidgetFormInputText(),
      'element_number_enable_quantity'      => new sfWidgetFormInputText(),
      'element_number_quantity_link'        => new sfWidgetFormInputText(),
      'element_table_name'                  => new sfWidgetFormInputText(),
      'element_field_value'                 => new sfWidgetFormTextarea(),
      'element_field_name'                  => new sfWidgetFormInputText(),
      'element_option_query'                => new sfWidgetFormTextarea(),
      'element_existing_form'               => new sfWidgetFormInputText(),
      'element_existing_stage'              => new sfWidgetFormInputText(),
      'element_remote_username'             => new sfWidgetFormInputText(),
      'element_remote_password'             => new sfWidgetFormInputText(),
      'element_remote_value'                => new sfWidgetFormTextarea(),
      'element_price_class'                 => new sfWidgetFormTextarea(),
      'element_remote_server_field'         => new sfWidgetFormTextarea(),
      'element_jsondef'                     => new sfWidgetFormTextarea(),
      'element_remote_post'                 => new sfWidgetFormTextarea(),
      'element_validator_class'             => new sfWidgetFormTextarea(),
      'element_field_error_message'         => new sfWidgetFormTextarea(),
    ));

    $this->setValidators(array(
      'form_id'                             => new sfValidatorChoice(array('choices' => array($this->getObject()->get('form_id')), 'empty_value' => $this->getObject()->get('form_id'), 'required' => false)),
      'element_id'                          => new sfValidatorChoice(array('choices' => array($this->getObject()->get('element_id')), 'empty_value' => $this->getObject()->get('element_id'), 'required' => false)),
      'element_title'                       => new sfValidatorString(array('required' => false)),
      'element_guidelines'                  => new sfValidatorString(array('required' => false)),
      'element_size'                        => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'element_is_required'                 => new sfValidatorInteger(array('required' => false)),
      'element_is_unique'                   => new sfValidatorInteger(array('required' => false)),
      'element_is_readonly'                 => new sfValidatorInteger(array('required' => false)),
      'element_is_private'                  => new sfValidatorInteger(array('required' => false)),
      'element_enable_placeholder'          => new sfValidatorInteger(array('required' => false)),
      'element_text_default_type'           => new sfValidatorString(array('max_length' => 6, 'required' => false)),
      'element_text_default_length'         => new sfValidatorInteger(array('required' => false)),
      'element_text_default_random_type'    => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'element_text_default_prefix'         => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'element_text_default_case'           => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'element_type'                        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'element_position'                    => new sfValidatorInteger(array('required' => false)),
      'element_default_value'               => new sfValidatorString(array('required' => false)),
      'element_constraint'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_total_child'                 => new sfValidatorInteger(array('required' => false)),
      'element_css_class'                   => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_range_min'                   => new sfValidatorInteger(array('required' => false)),
      'element_range_max'                   => new sfValidatorInteger(array('required' => false)),
      'element_range_limit_by'              => new sfValidatorString(array('max_length' => 1)),
      'element_status'                      => new sfValidatorInteger(array('required' => false)),
      'element_choice_columns'              => new sfValidatorInteger(array('required' => false)),
      'element_choice_has_other'            => new sfValidatorInteger(array('required' => false)),
      'element_choice_other_label'          => new sfValidatorString(array('required' => false)),
      'element_choice_limit_rule'           => new sfValidatorString(array('max_length' => 12, 'required' => false)),
      'element_choice_limit_qty'            => new sfValidatorInteger(array('required' => false)),
      'element_choice_limit_range_min'      => new sfValidatorInteger(array('required' => false)),
      'element_choice_limit_range_max'      => new sfValidatorInteger(array('required' => false)),
      'element_choice_max_entry'            => new sfValidatorInteger(array('required' => false)),
      'element_time_showsecond'             => new sfValidatorInteger(array('required' => false)),
      'element_time_24hour'                 => new sfValidatorInteger(array('required' => false)),
      'element_address_hideline2'           => new sfValidatorInteger(array('required' => false)),
      'element_address_us_only'             => new sfValidatorInteger(array('required' => false)),
      'element_date_enable_range'           => new sfValidatorInteger(array('required' => false)),
      'element_date_range_min'              => new sfValidatorDate(array('required' => false)),
      'element_date_range_max'              => new sfValidatorDate(array('required' => false)),
      'element_date_enable_selection_limit' => new sfValidatorInteger(array('required' => false)),
      'element_date_selection_max'          => new sfValidatorInteger(array('required' => false)),
      'element_date_past_future'            => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'element_date_disable_past_future'    => new sfValidatorInteger(array('required' => false)),
      'element_date_disable_weekend'        => new sfValidatorInteger(array('required' => false)),
      'element_date_disable_specific'       => new sfValidatorInteger(array('required' => false)),
      'element_date_disabled_list'          => new sfValidatorString(array('required' => false)),
      'element_file_enable_type_limit'      => new sfValidatorInteger(array('required' => false)),
      'element_file_block_or_allow'         => new sfValidatorString(array('max_length' => 1, 'required' => false)),
      'element_file_type_list'              => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_file_as_attachment'          => new sfValidatorInteger(array('required' => false)),
      'element_file_enable_advance'         => new sfValidatorInteger(array('required' => false)),
      'element_file_auto_upload'            => new sfValidatorInteger(array('required' => false)),
      'element_file_enable_multi_upload'    => new sfValidatorInteger(array('required' => false)),
      'element_file_max_selection'          => new sfValidatorInteger(array('required' => false)),
      'element_file_enable_size_limit'      => new sfValidatorInteger(array('required' => false)),
      'element_file_size_max'               => new sfValidatorInteger(array('required' => false)),
      'element_matrix_allow_multiselect'    => new sfValidatorInteger(array('required' => false)),
      'element_matrix_parent_id'            => new sfValidatorInteger(array('required' => false)),
      'element_submit_use_image'            => new sfValidatorInteger(array('required' => false)),
      'element_submit_primary_text'         => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_submit_secondary_text'       => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_submit_primary_img'          => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_submit_secondary_img'        => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_page_title'                  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'element_page_number'                 => new sfValidatorInteger(array('required' => false)),
      'element_section_display_in_email'    => new sfValidatorInteger(array('required' => false)),
      'element_section_enable_scroll'       => new sfValidatorInteger(array('required' => false)),
      'element_number_enable_quantity'      => new sfValidatorInteger(array('required' => false)),
      'element_number_quantity_link'        => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'element_table_name'                  => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'element_field_value'                 => new sfValidatorString(array('required' => false)),
      'element_field_name'                  => new sfValidatorString(array('max_length' => 200, 'required' => false)),
      'element_option_query'                => new sfValidatorString(array('required' => false)),
      'element_existing_form'               => new sfValidatorInteger(array('required' => false)),
      'element_existing_stage'              => new sfValidatorInteger(array('required' => false)),
      'element_remote_username'             => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'element_remote_password'             => new sfValidatorString(array('max_length' => 250, 'required' => false)),
      'element_remote_value'                => new sfValidatorString(array('required' => false)),
      'element_price_class'                 => new sfValidatorString(array('required' => false)),
      'element_remote_server_field'         => new sfValidatorString(array('required' => false)),
      'element_jsondef'                     => new sfValidatorString(array('required' => false)),
      'element_remote_post'                 => new sfValidatorString(array('required' => false)),
      'element_validator_class'             => new sfValidatorString(array('required' => false)),
      'element_field_error_message'         => new sfValidatorString(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ap_form_elements[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ApFormElements';
  }

}
