<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TaskComments', 'doctrine');

/**
 * BaseTaskComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int           $id                            Type: integer(4), primary key
 * @property string        $commentcontent                Type: string
 * @property string        $date_created                  Type: string
 * @property int           $reviewer_id                   Type: integer(4)
 * @property int           $task_id                       Type: integer(4)
 *  
 * @method int             getId()                        Type: integer(4), primary key
 * @method string          getCommentcontent()            Type: string
 * @method string          getDateCreated()               Type: string
 * @method int             getReviewerId()                Type: integer(4)
 * @method int             getTaskId()                    Type: integer(4)
 *  
 * @method TaskComments    setId(int $val)                Type: integer(4), primary key
 * @method TaskComments    setCommentcontent(string $val) Type: string
 * @method TaskComments    setDateCreated(string $val)    Type: string
 * @method TaskComments    setReviewerId(int $val)        Type: integer(4)
 * @method TaskComments    setTaskId(int $val)            Type: integer(4)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_comments');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('commentcontent', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('date_created', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('reviewer_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('task_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}