<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfUser', 'doctrine');

/**
 * BaseCfUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                     $nid                                          Type: integer(4), primary key
 * @property string                                  $strlastname                                  Type: string
 * @property string                                  $strfirstname                                 Type: string
 * @property string                                  $stremail                                     Type: string
 * @property int                                     $naccesslevel                                 Type: integer(4), default "0"
 * @property string                                  $struserid                                    Type: string
 * @property string                                  $strpassword                                  Type: string
 * @property string                                  $stremail_format                              Type: string(8), default "HTML"
 * @property string                                  $stremail_values                              Type: string(8), default "IFRAME"
 * @property int                                     $nsubstitudeid                                Type: integer(4), default "0"
 * @property int                                     $tslastaction                                 Type: integer(4)
 * @property int                                     $bdeleted                                     Type: integer(4)
 * @property string                                  $strstreet                                    Type: string
 * @property string                                  $strcountry                                   Type: string
 * @property string                                  $strzipcode                                   Type: string
 * @property string                                  $strcity                                      Type: string
 * @property string                                  $strphone_main1                               Type: string
 * @property string                                  $strphone_main2                               Type: string
 * @property string                                  $strphone_mobile                              Type: string
 * @property string                                  $strfax                                       Type: string
 * @property string                                  $strorganisation                              Type: string
 * @property string                                  $strdepartment                                Type: string
 * @property string                                  $strcostcenter                                Type: string
 * @property string                                  $userdefined1_value                           Type: string
 * @property string                                  $userdefined2_value                           Type: string
 * @property int                                     $nsubstitutetimevalue                         Type: integer(4)
 * @property string                                  $strsubstitutetimeunit                        Type: string
 * @property int                                     $busegeneralsubstituteconfig                  Type: integer(4)
 * @property int                                     $busegeneralemailconfig                       Type: integer(4)
 * @property int                                     $enable_email                                 Type: integer(4), default "1"
 * @property int                                     $enable_chat                                  Type: integer(4), default "1"
 * @property string                                  $about_me                                     Type: string
 * @property string                                  $profile_pic                                  Type: string(250)
 * @property string                                  $address                                      Type: string
 * @property string                                  $twitter                                      Type: string(250)
 * @property string                                  $facebook                                     Type: string(250)
 * @property string                                  $youtube                                      Type: string(250)
 * @property string                                  $linkedin                                     Type: string(250)
 * @property string                                  $pinterest                                    Type: string(250)
 * @property string                                  $instagram                                    Type: string(250)
 * @property string                                  $strtoken                                     Type: string(100)
 * @property string                                  $strtemppassword                              Type: string(250)
 * @property Doctrine_Collection|MfGuardGroup[]      $Groups                                       
 * @property Doctrine_Collection|MfGuardGroup[]      $User                                         
 * @property Doctrine_Collection|MfGuardUserGroup[]  $MfGuardUserGroup                             
 * @property Doctrine_Collection|Task[]              $Task                                         
 *  
 * @method int                                       getNid()                                      Type: integer(4), primary key
 * @method string                                    getStrlastname()                              Type: string
 * @method string                                    getStrfirstname()                             Type: string
 * @method string                                    getStremail()                                 Type: string
 * @method int                                       getNaccesslevel()                             Type: integer(4), default "0"
 * @method string                                    getStruserid()                                Type: string
 * @method string                                    getStrpassword()                              Type: string
 * @method string                                    getStremailFormat()                           Type: string(8), default "HTML"
 * @method string                                    getStremailValues()                           Type: string(8), default "IFRAME"
 * @method int                                       getNsubstitudeid()                            Type: integer(4), default "0"
 * @method int                                       getTslastaction()                             Type: integer(4)
 * @method int                                       getBdeleted()                                 Type: integer(4)
 * @method string                                    getStrstreet()                                Type: string
 * @method string                                    getStrcountry()                               Type: string
 * @method string                                    getStrzipcode()                               Type: string
 * @method string                                    getStrcity()                                  Type: string
 * @method string                                    getStrphoneMain1()                            Type: string
 * @method string                                    getStrphoneMain2()                            Type: string
 * @method string                                    getStrphoneMobile()                           Type: string
 * @method string                                    getStrfax()                                   Type: string
 * @method string                                    getStrorganisation()                          Type: string
 * @method string                                    getStrdepartment()                            Type: string
 * @method string                                    getStrcostcenter()                            Type: string
 * @method string                                    getUserdefined1Value()                        Type: string
 * @method string                                    getUserdefined2Value()                        Type: string
 * @method int                                       getNsubstitutetimevalue()                     Type: integer(4)
 * @method string                                    getStrsubstitutetimeunit()                    Type: string
 * @method int                                       getBusegeneralsubstituteconfig()              Type: integer(4)
 * @method int                                       getBusegeneralemailconfig()                   Type: integer(4)
 * @method int                                       getEnableEmail()                              Type: integer(4), default "1"
 * @method int                                       getEnableChat()                               Type: integer(4), default "1"
 * @method string                                    getAboutMe()                                  Type: string
 * @method string                                    getProfilePic()                               Type: string(250)
 * @method string                                    getAddress()                                  Type: string
 * @method string                                    getTwitter()                                  Type: string(250)
 * @method string                                    getFacebook()                                 Type: string(250)
 * @method string                                    getYoutube()                                  Type: string(250)
 * @method string                                    getLinkedin()                                 Type: string(250)
 * @method string                                    getPinterest()                                Type: string(250)
 * @method string                                    getInstagram()                                Type: string(250)
 * @method string                                    getStrtoken()                                 Type: string(100)
 * @method string                                    getStrtemppassword()                          Type: string(250)
 * @method Doctrine_Collection|MfGuardGroup[]        getGroups()                                   
 * @method Doctrine_Collection|MfGuardGroup[]        getUser()                                     
 * @method Doctrine_Collection|MfGuardUserGroup[]    getMfGuardUserGroup()                         
 * @method Doctrine_Collection|Task[]                getTask()                                     
 *  
 * @method CfUser                                    setNid(int $val)                              Type: integer(4), primary key
 * @method CfUser                                    setStrlastname(string $val)                   Type: string
 * @method CfUser                                    setStrfirstname(string $val)                  Type: string
 * @method CfUser                                    setStremail(string $val)                      Type: string
 * @method CfUser                                    setNaccesslevel(int $val)                     Type: integer(4), default "0"
 * @method CfUser                                    setStruserid(string $val)                     Type: string
 * @method CfUser                                    setStrpassword(string $val)                   Type: string
 * @method CfUser                                    setStremailFormat(string $val)                Type: string(8), default "HTML"
 * @method CfUser                                    setStremailValues(string $val)                Type: string(8), default "IFRAME"
 * @method CfUser                                    setNsubstitudeid(int $val)                    Type: integer(4), default "0"
 * @method CfUser                                    setTslastaction(int $val)                     Type: integer(4)
 * @method CfUser                                    setBdeleted(int $val)                         Type: integer(4)
 * @method CfUser                                    setStrstreet(string $val)                     Type: string
 * @method CfUser                                    setStrcountry(string $val)                    Type: string
 * @method CfUser                                    setStrzipcode(string $val)                    Type: string
 * @method CfUser                                    setStrcity(string $val)                       Type: string
 * @method CfUser                                    setStrphoneMain1(string $val)                 Type: string
 * @method CfUser                                    setStrphoneMain2(string $val)                 Type: string
 * @method CfUser                                    setStrphoneMobile(string $val)                Type: string
 * @method CfUser                                    setStrfax(string $val)                        Type: string
 * @method CfUser                                    setStrorganisation(string $val)               Type: string
 * @method CfUser                                    setStrdepartment(string $val)                 Type: string
 * @method CfUser                                    setStrcostcenter(string $val)                 Type: string
 * @method CfUser                                    setUserdefined1Value(string $val)             Type: string
 * @method CfUser                                    setUserdefined2Value(string $val)             Type: string
 * @method CfUser                                    setNsubstitutetimevalue(int $val)             Type: integer(4)
 * @method CfUser                                    setStrsubstitutetimeunit(string $val)         Type: string
 * @method CfUser                                    setBusegeneralsubstituteconfig(int $val)      Type: integer(4)
 * @method CfUser                                    setBusegeneralemailconfig(int $val)           Type: integer(4)
 * @method CfUser                                    setEnableEmail(int $val)                      Type: integer(4), default "1"
 * @method CfUser                                    setEnableChat(int $val)                       Type: integer(4), default "1"
 * @method CfUser                                    setAboutMe(string $val)                       Type: string
 * @method CfUser                                    setProfilePic(string $val)                    Type: string(250)
 * @method CfUser                                    setAddress(string $val)                       Type: string
 * @method CfUser                                    setTwitter(string $val)                       Type: string(250)
 * @method CfUser                                    setFacebook(string $val)                      Type: string(250)
 * @method CfUser                                    setYoutube(string $val)                       Type: string(250)
 * @method CfUser                                    setLinkedin(string $val)                      Type: string(250)
 * @method CfUser                                    setPinterest(string $val)                     Type: string(250)
 * @method CfUser                                    setInstagram(string $val)                     Type: string(250)
 * @method CfUser                                    setStrtoken(string $val)                      Type: string(100)
 * @method CfUser                                    setStrtemppassword(string $val)               Type: string(250)
 * @method CfUser                                    setGroups(Doctrine_Collection $val)           
 * @method CfUser                                    setUser(Doctrine_Collection $val)             
 * @method CfUser                                    setMfGuardUserGroup(Doctrine_Collection $val) 
 * @method CfUser                                    setTask(Doctrine_Collection $val)             
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_user');
        $this->hasColumn('nid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('strlastname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('strfirstname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('stremail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('naccesslevel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('struserid', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('strpassword', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('stremail_format', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'HTML',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             'default' => ''
             ));
        $this->hasColumn('stremail_values', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'IFRAME',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             'default' => ''
             ));
        $this->hasColumn('nsubstitudeid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('tslastaction', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('bdeleted', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('strstreet', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strcountry', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strzipcode', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strcity', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strphone_main1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strphone_main2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strphone_mobile', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strfax', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strorganisation', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strdepartment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('strcostcenter', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('userdefined1_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('userdefined2_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('nsubstitutetimevalue', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('strsubstitutetimeunit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => 0
             ));
        $this->hasColumn('busegeneralsubstituteconfig', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 0
             ));
        $this->hasColumn('busegeneralemailconfig', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 1
             ));
        $this->hasColumn('enable_email', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 1
             ));
        $this->hasColumn('enable_chat', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'default' => 1
             ));
        $this->hasColumn('about_me', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('profile_pic', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('twitter', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('facebook', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('youtube', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('linkedin', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('pinterest', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('instagram', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
        $this->hasColumn('strtoken', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             'default' => ''
             ));
        $this->hasColumn('strtemppassword', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             'default' => ''
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MfGuardGroup as Groups', array(
             'refClass' => 'mfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('MfGuardGroup as User', array(
             'refClass' => 'mfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('MfGuardUserGroup', array(
             'local' => 'nid',
             'foreign' => 'user_id'));

        $this->hasMany('Task', array(
             'local' => 'nid',
             'foreign' => 'owner_user_id'));
		//OTB Start - Multi Agency Implementation
        $this->hasMany('AgencyUser', array(
             'local' => 'nid',
             'foreign' => 'user_id'));
		//OTB End - Multi Agency Implementation
        $this->hasMany('Communications', array(
             'local' => 'nid',
             'foreign' => 'reviewer_id'));
        $this->hasMany('Communication', array(
             'local' => 'nid',
             'foreign' => 'sender'));
        $this->hasOne('Department', array(
             'local' => 'strdepartment',
             'foreign' => 'id'));
    }
}