<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApFormSorts', 'doctrine');

/**
 * BaseApFormSorts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $user_id               Type: integer(4), primary key
 * @property string       $sort_by               Type: string(25)
 *  
 * @method int            getUserId()            Type: integer(4), primary key
 * @method string         getSortBy()            Type: string(25)
 *  
 * @method ApFormSorts    setUserId(int $val)    Type: integer(4), primary key
 * @method ApFormSorts    setSortBy(string $val) Type: string(25)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApFormSorts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_form_sorts');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sort_by', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}