<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EntryDecline', 'doctrine');

/**
 * BaseEntryDecline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int           $id                          Type: integer(8), primary key
 * @property int           $entry_id                    Type: integer(8)
 * @property string        $description                 Type: string
 * @property string        $created_at                  Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string        $updated_at                  Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property int           $resolved                    Type: integer(4), default "0"
 * @property string        $edit_fields                 Type: string
 * @property int           $declined_by                 Type: integer(8)
 * @property FormEntry     $FormEntry                   
 *  
 * @method int             getId()                      Type: integer(8), primary key
 * @method int             getEntryId()                 Type: integer(8)
 * @method string          getDescription()             Type: string
 * @method string          getCreatedAt()               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string          getUpdatedAt()               Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method int             getResolved()                Type: integer(4), default "0"
 * @method string          getEditFields()              Type: string
 * @method int             getDeclinedBy()              Type: integer(8)
 * @method FormEntry       getFormEntry()               
 *  
 * @method EntryDecline    setId(int $val)              Type: integer(8), primary key
 * @method EntryDecline    setEntryId(int $val)         Type: integer(8)
 * @method EntryDecline    setDescription(string $val)  Type: string
 * @method EntryDecline    setCreatedAt(string $val)    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method EntryDecline    setUpdatedAt(string $val)    Type: timestamp(25), Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method EntryDecline    setResolved(int $val)        Type: integer(4), default "0"
 * @method EntryDecline    setEditFields(string $val)   Type: string
 * @method EntryDecline    setDeclinedBy(int $val)      Type: integer(8)
 * @method EntryDecline    setFormEntry(FormEntry $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntryDecline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entry_decline');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('entry_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('resolved', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edit_fields', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('declined_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FormEntry', array(
             'local' => 'entry_id',
             'foreign' => 'id'));
    }
}