<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGuardUserCategoriesForms', 'doctrine');

/**
 * BaseSfGuardUserCategoriesForms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                         $id                           Type: integer(4), primary key
 * @property int                         $categoryid                   Type: integer(4)
 * @property int                         $formid                       Type: integer(4)
 * @property int                         $islinkedto                   Type: integer(4), default "0"
 * @property string                      $islinkedtitle                Type: string(250)
 *  
 * @method int                           getId()                       Type: integer(4), primary key
 * @method int                           getCategoryid()               Type: integer(4)
 * @method int                           getFormid()                   Type: integer(4)
 * @method int                           getIslinkedto()               Type: integer(4), default "0"
 * @method string                        getIslinkedtitle()            Type: string(250)
 *  
 * @method SfGuardUserCategoriesForms    setId(int $val)               Type: integer(4), primary key
 * @method SfGuardUserCategoriesForms    setCategoryid(int $val)       Type: integer(4)
 * @method SfGuardUserCategoriesForms    setFormid(int $val)           Type: integer(4)
 * @method SfGuardUserCategoriesForms    setIslinkedto(int $val)       Type: integer(4), default "0"
 * @method SfGuardUserCategoriesForms    setIslinkedtitle(string $val) Type: string(250)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGuardUserCategoriesForms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_categories_forms');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('categoryid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('formid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('islinkedto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('islinkedtitle', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}