<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MfGuardUserPermission', 'doctrine');

/**
 * BaseMfGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                    $user_id                                     Type: integer(8), primary key
 * @property int                    $permission_id                               Type: integer(8), primary key
 * @property MfGuardPermission      $MfGuardPermission                           
 *  
 * @method int                      getUserId()                                  Type: integer(8), primary key
 * @method int                      getPermissionId()                            Type: integer(8), primary key
 * @method MfGuardPermission        getMfGuardPermission()                       
 *  
 * @method MfGuardUserPermission    setUserId(int $val)                          Type: integer(8), primary key
 * @method MfGuardUserPermission    setPermissionId(int $val)                    Type: integer(8), primary key
 * @method MfGuardUserPermission    setMfGuardPermission(MfGuardPermission $val) 
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMfGuardUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_guard_user_permission');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('permission_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MfGuardPermission', array(
             'local' => 'permission_id',
             'foreign' => 'id'));
    }
}