<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RestCrud', 'doctrine');

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $form_entry_id
 * @property string $action
 * @property string $action_timestamp
 * 
 * @method integer  getId()               Returns the current record's "id" value
 * @method integer  getUserId()           Returns the current record's "user_id" value
 * @method integer  getFormEntryId()      Returns the current record's "form_entry_id" value
 * @method string   getAction()           Returns the current record's "action" value
 * @method string   getActionTimestamp()  Returns the current record's "action_timestamp" value
 * @method Activity setId()               Sets the current record's "id" value
 * @method Activity setUserId()           Sets the current record's "user_id" value
 * @method Activity setFormEntryId()      Sets the current record's "form_entry_id" value
 * @method Activity setAction()           Sets the current record's "action" value
 * @method Activity setActionTimestamp()  Sets the current record's "action_timestamp" value
 * 
 * @package    permit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRestCrud extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rest_crud');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rest_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('rest_table', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}