<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfUserIndex', 'doctrine');

/**
 * BaseCfUserIndex
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $user_id               Type: integer(4), primary key
 * @property string       $indexe                Type: string
 *  
 * @method int            getUserId()            Type: integer(4), primary key
 * @method string         getIndexe()            Type: string
 *  
 * @method CfUserIndex    setUserId(int $val)    Type: integer(4), primary key
 * @method CfUserIndex    setIndexe(string $val) Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfUserIndex extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cf_user_index');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('indexe', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}