<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Announcement', 'doctrine');

/**
 * BaseAnnouncement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int           $id                       Type: integer(4), primary key
 * @property string        $content                  Type: string
 * @property string        $start_date               Type: string(250)
 * @property string        $end_date                 Type: string(250)
 * @property int           $frontend                 Type: integer(4), default "1"
 *  
 * @method int             getId()                   Type: integer(4), primary key
 * @method string          getContent()              Type: string
 * @method string          getStartDate()            Type: string(250)
 * @method string          getEndDate()              Type: string(250)
 * @method int             getFrontend()             Type: integer(4), default "1"
 *  
 * @method Announcement    setId(int $val)           Type: integer(4), primary key
 * @method Announcement    setContent(string $val)   Type: string
 * @method Announcement    setStartDate(string $val) Type: string(250)
 * @method Announcement    setEndDate(string $val)   Type: string(250)
 * @method Announcement    setFrontend(int $val)     Type: integer(4), default "1"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnouncement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('announcement');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('start_date', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('end_date', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('frontend', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}