<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApPageLogic', 'doctrine');

/**
 * BaseApPageLogic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $form_id                   Type: integer(4), primary key
 * @property string       $page_id                   Type: string(15), primary key
 * @property string       $rule_all_any              Type: string(3), default "all"
 *  
 * @method int            getFormId()                Type: integer(4), primary key
 * @method string         getPageId()                Type: string(15), primary key
 * @method string         getRuleAllAny()            Type: string(3), default "all"
 *  
 * @method ApPageLogic    setFormId(int $val)        Type: integer(4), primary key
 * @method ApPageLogic    setPageId(string $val)     Type: string(15), primary key
 * @method ApPageLogic    setRuleAllAny(string $val) Type: string(3), default "all"
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApPageLogic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_page_logic');
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('page_id', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('rule_all_any', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'all',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}