<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Reports', 'doctrine');

/**
 * BaseReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int      $id                     Type: integer(4), primary key
 * @property int      $type                   Type: integer(4)
 * @property int      $form_id                Type: integer(4)
 * @property string   $title                  Type: string
 * @property string   $content                Type: string
 *  
 * @method int        getId()                 Type: integer(4), primary key
 * @method int        getType()               Type: integer(4)
 * @method int        getFormId()             Type: integer(4)
 * @method string     getTitle()              Type: string
 * @method string     getContent()            Type: string
 *  
 * @method Reports    setId(int $val)         Type: integer(4), primary key
 * @method Reports    setType(int $val)       Type: integer(4)
 * @method Reports    setFormId(int $val)     Type: integer(4)
 * @method Reports    setTitle(string $val)   Type: string
 * @method Reports    setContent(string $val) Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReports extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reports');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}