<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Buttons', 'doctrine');

/**
 * BaseButtons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int      $id                     Type: integer(4), primary key
 * @property string   $img                    Type: string
 * @property string   $title                  Type: string
 * @property string   $tooltip                Type: string
 * @property string   $link                   Type: string
 *  
 * @method int        getId()                 Type: integer(4), primary key
 * @method string     getImg()                Type: string
 * @method string     getTitle()              Type: string
 * @method string     getTooltip()            Type: string
 * @method string     getLink()               Type: string
 *  
 * @method Buttons    setId(int $val)         Type: integer(4), primary key
 * @method Buttons    setImg(string $val)     Type: string
 * @method Buttons    setTitle(string $val)   Type: string
 * @method Buttons    setTooltip(string $val) Type: string
 * @method Buttons    setLink(string $val)    Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseButtons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('buttons');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('img', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('tooltip', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
        $this->hasColumn('link', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             'default' => ''
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
        $this->hasMany('SubMenus as Submenus', array(
             'refClass' => 'SubMenuButtons',
             'local' => 'button_id',
             'foreign' => 'sub_menu_id'));

        $this->hasMany('SubMenuButtons as Submenubuttons', array(
             'local' => 'id',
             'foreign' => 'button_id'));
        
    }
}