<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormEntryLinks', 'doctrine');

/**
 * BaseFormEntryLinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int             $id                              Type: integer(4), primary key
 * @property int             $formentryid                     Type: integer(4)
 * @property int             $form_id                         Type: integer(4)
 * @property int             $entry_id                        Type: integer(4)
 * @property int             $user_id                         Type: integer(4)
 * @property string          $date_of_submission              Type: string(200)
 *  
 * @method int               getId()                          Type: integer(4), primary key
 * @method int               getFormentryid()                 Type: integer(4)
 * @method int               getFormId()                      Type: integer(4)
 * @method int               getEntryId()                     Type: integer(4)
 * @method int               getUserId()                      Type: integer(4)
 * @method string            getDateOfSubmission()            Type: string(200)
 *  
 * @method FormEntryLinks    setId(int $val)                  Type: integer(4), primary key
 * @method FormEntryLinks    setFormentryid(int $val)         Type: integer(4)
 * @method FormEntryLinks    setFormId(int $val)              Type: integer(4)
 * @method FormEntryLinks    setEntryId(int $val)             Type: integer(4)
 * @method FormEntryLinks    setUserId(int $val)              Type: integer(4)
 * @method FormEntryLinks    setDateOfSubmission(string $val) Type: string(200)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormEntryLinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('form_entry_links');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('formentryid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entry_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_of_submission', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}