<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApplicationReference', 'doctrine');

/**
 * BaseApplicationReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                   $id                        Type: integer(4), primary key
 * @property int                   $stage_id                  Type: integer(4)
 * @property int                   $application_id            Type: integer(4)
 * @property int                   $approved_by               Type: integer(4)
 * @property string                $start_date                Type: string
 * @property string                $end_date                  Type: string
 *  
 * @method int                     getId()                    Type: integer(4), primary key
 * @method int                     getStageId()               Type: integer(4)
 * @method int                     getApplicationId()         Type: integer(4)
 * @method int                     getApprovedBy()            Type: integer(4)
 * @method string                  getStartDate()             Type: string
 * @method string                  getEndDate()               Type: string
 *  
 * @method ApplicationReference    setId(int $val)            Type: integer(4), primary key
 * @method ApplicationReference    setStageId(int $val)       Type: integer(4)
 * @method ApplicationReference    setApplicationId(int $val) Type: integer(4)
 * @method ApplicationReference    setApprovedBy(int $val)    Type: integer(4)
 * @method ApplicationReference    setStartDate(string $val)  Type: string
 * @method ApplicationReference    setEndDate(string $val)    Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApplicationReference extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('application_reference');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('stage_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('application_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('approved_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('start_date', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('end_date', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();

        $this->hasOne('FormEntry', array(
             'local' => 'application_id',
             'foreign' => 'id'));
        
    }
}