<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApEmailLogicConditions', 'doctrine');

/**
 * BaseApEmailLogicConditions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                     $aec_id                       Type: integer(4), primary key
 * @property int                     $form_id                      Type: integer(4)
 * @property int                     $target_rule_id               Type: integer(4)
 * @property string                  $element_name                 Type: string(50)
 * @property string                  $rule_condition               Type: string(15), default "is"
 * @property string                  $rule_keyword                 Type: string(255)
 *  
 * @method int                       getAecId()                    Type: integer(4), primary key
 * @method int                       getFormId()                   Type: integer(4)
 * @method int                       getTargetRuleId()             Type: integer(4)
 * @method string                    getElementName()              Type: string(50)
 * @method string                    getRuleCondition()            Type: string(15), default "is"
 * @method string                    getRuleKeyword()              Type: string(255)
 *  
 * @method ApEmailLogicConditions    setAecId(int $val)            Type: integer(4), primary key
 * @method ApEmailLogicConditions    setFormId(int $val)           Type: integer(4)
 * @method ApEmailLogicConditions    setTargetRuleId(int $val)     Type: integer(4)
 * @method ApEmailLogicConditions    setElementName(string $val)   Type: string(50)
 * @method ApEmailLogicConditions    setRuleCondition(string $val) Type: string(15), default "is"
 * @method ApEmailLogicConditions    setRuleKeyword(string $val)   Type: string(255)
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApEmailLogicConditions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_email_logic_conditions');
        $this->hasColumn('aec_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('target_rule_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('element_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('rule_condition', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'is',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('rule_keyword', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}