<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Conditions', 'doctrine');

/**
 * BaseConditions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int         $id                           Type: integer(4), primary key
 * @property int         $circulation_id               Type: integer(4)
 * @property int         $slot_id                      Type: integer(4)
 * @property int         $form_id                      Type: integer(4)
 * @property int         $field_id                     Type: integer(4)
 * @property string      $condition_text               Type: string
 *  
 * @method int           getId()                       Type: integer(4), primary key
 * @method int           getCirculationId()            Type: integer(4)
 * @method int           getSlotId()                   Type: integer(4)
 * @method int           getFormId()                   Type: integer(4)
 * @method int           getFieldId()                  Type: integer(4)
 * @method string        getConditionText()            Type: string
 *  
 * @method Conditions    setId(int $val)               Type: integer(4), primary key
 * @method Conditions    setCirculationId(int $val)    Type: integer(4)
 * @method Conditions    setSlotId(int $val)           Type: integer(4)
 * @method Conditions    setFormId(int $val)           Type: integer(4)
 * @method Conditions    setFieldId(int $val)          Type: integer(4)
 * @method Conditions    setConditionText(string $val) Type: string
 *  
 * @package    permitflow
 * @subpackage model
 * @author     Webmasters Africa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConditions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conditions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('circulation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('slot_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('field_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('condition_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}