<?php

/**
 * ApFormThemes form base class.
 *
 * @method ApFormThemes getObject() Returns the current form's model object
 *
 * @package    permitflow
 * @subpackage form
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseApFormThemesForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'theme_id'                  => new sfWidgetFormInputHidden(),
      'status'                    => new sfWidgetFormInputText(),
      'theme_has_css'             => new sfWidgetFormInputText(),
      'theme_name'                => new sfWidgetFormInputText(),
      'theme_built_in'            => new sfWidgetFormInputText(),
      'logo_type'                 => new sfWidgetFormInputText(),
      'logo_custom_image'         => new sfWidgetFormTextarea(),
      'logo_custom_height'        => new sfWidgetFormInputText(),
      'logo_default_image'        => new sfWidgetFormInputText(),
      'logo_default_repeat'       => new sfWidgetFormInputText(),
      'wallpaper_bg_type'         => new sfWidgetFormInputText(),
      'wallpaper_bg_color'        => new sfWidgetFormInputText(),
      'wallpaper_bg_pattern'      => new sfWidgetFormInputText(),
      'wallpaper_bg_custom'       => new sfWidgetFormTextarea(),
      'header_bg_type'            => new sfWidgetFormInputText(),
      'header_bg_color'           => new sfWidgetFormInputText(),
      'header_bg_pattern'         => new sfWidgetFormInputText(),
      'header_bg_custom'          => new sfWidgetFormTextarea(),
      'form_bg_type'              => new sfWidgetFormInputText(),
      'form_bg_color'             => new sfWidgetFormInputText(),
      'form_bg_pattern'           => new sfWidgetFormInputText(),
      'form_bg_custom'            => new sfWidgetFormTextarea(),
      'highlight_bg_type'         => new sfWidgetFormInputText(),
      'highlight_bg_color'        => new sfWidgetFormInputText(),
      'highlight_bg_pattern'      => new sfWidgetFormInputText(),
      'highlight_bg_custom'       => new sfWidgetFormTextarea(),
      'guidelines_bg_type'        => new sfWidgetFormInputText(),
      'guidelines_bg_color'       => new sfWidgetFormInputText(),
      'guidelines_bg_pattern'     => new sfWidgetFormInputText(),
      'guidelines_bg_custom'      => new sfWidgetFormTextarea(),
      'field_bg_type'             => new sfWidgetFormInputText(),
      'field_bg_color'            => new sfWidgetFormInputText(),
      'field_bg_pattern'          => new sfWidgetFormInputText(),
      'field_bg_custom'           => new sfWidgetFormTextarea(),
      'form_title_font_type'      => new sfWidgetFormInputText(),
      'form_title_font_weight'    => new sfWidgetFormInputText(),
      'form_title_font_style'     => new sfWidgetFormInputText(),
      'form_title_font_size'      => new sfWidgetFormInputText(),
      'form_title_font_color'     => new sfWidgetFormInputText(),
      'form_desc_font_type'       => new sfWidgetFormInputText(),
      'form_desc_font_weight'     => new sfWidgetFormInputText(),
      'form_desc_font_style'      => new sfWidgetFormInputText(),
      'form_desc_font_size'       => new sfWidgetFormInputText(),
      'form_desc_font_color'      => new sfWidgetFormInputText(),
      'field_title_font_type'     => new sfWidgetFormInputText(),
      'field_title_font_weight'   => new sfWidgetFormInputText(),
      'field_title_font_style'    => new sfWidgetFormInputText(),
      'field_title_font_size'     => new sfWidgetFormInputText(),
      'field_title_font_color'    => new sfWidgetFormInputText(),
      'guidelines_font_type'      => new sfWidgetFormInputText(),
      'guidelines_font_weight'    => new sfWidgetFormInputText(),
      'guidelines_font_style'     => new sfWidgetFormInputText(),
      'guidelines_font_size'      => new sfWidgetFormInputText(),
      'guidelines_font_color'     => new sfWidgetFormInputText(),
      'section_title_font_type'   => new sfWidgetFormInputText(),
      'section_title_font_weight' => new sfWidgetFormInputText(),
      'section_title_font_style'  => new sfWidgetFormInputText(),
      'section_title_font_size'   => new sfWidgetFormInputText(),
      'section_title_font_color'  => new sfWidgetFormInputText(),
      'section_desc_font_type'    => new sfWidgetFormInputText(),
      'section_desc_font_weight'  => new sfWidgetFormInputText(),
      'section_desc_font_style'   => new sfWidgetFormInputText(),
      'section_desc_font_size'    => new sfWidgetFormInputText(),
      'section_desc_font_color'   => new sfWidgetFormInputText(),
      'field_text_font_type'      => new sfWidgetFormInputText(),
      'field_text_font_weight'    => new sfWidgetFormInputText(),
      'field_text_font_style'     => new sfWidgetFormInputText(),
      'field_text_font_size'      => new sfWidgetFormInputText(),
      'field_text_font_color'     => new sfWidgetFormInputText(),
      'border_form_width'         => new sfWidgetFormInputText(),
      'border_form_style'         => new sfWidgetFormInputText(),
      'border_form_color'         => new sfWidgetFormInputText(),
      'border_guidelines_width'   => new sfWidgetFormInputText(),
      'border_guidelines_style'   => new sfWidgetFormInputText(),
      'border_guidelines_color'   => new sfWidgetFormInputText(),
      'border_section_width'      => new sfWidgetFormInputText(),
      'border_section_style'      => new sfWidgetFormInputText(),
      'border_section_color'      => new sfWidgetFormInputText(),
      'form_shadow_style'         => new sfWidgetFormInputText(),
      'form_shadow_size'          => new sfWidgetFormInputText(),
      'form_shadow_brightness'    => new sfWidgetFormInputText(),
      'form_button_type'          => new sfWidgetFormInputText(),
      'form_button_text'          => new sfWidgetFormInputText(),
      'form_button_image'         => new sfWidgetFormTextarea(),
      'advanced_css'              => new sfWidgetFormTextarea(),
      'user_id'                   => new sfWidgetFormInputText(),
      'theme_is_private'          => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'theme_id'                  => new sfValidatorChoice(array('choices' => array($this->getObject()->get('theme_id')), 'empty_value' => $this->getObject()->get('theme_id'), 'required' => false)),
      'status'                    => new sfValidatorInteger(array('required' => false)),
      'theme_has_css'             => new sfValidatorInteger(array('required' => false)),
      'theme_name'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'theme_built_in'            => new sfValidatorInteger(array('required' => false)),
      'logo_type'                 => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'logo_custom_image'         => new sfValidatorString(array('required' => false)),
      'logo_custom_height'        => new sfValidatorInteger(array('required' => false)),
      'logo_default_image'        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'logo_default_repeat'       => new sfValidatorInteger(array('required' => false)),
      'wallpaper_bg_type'         => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'wallpaper_bg_color'        => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'wallpaper_bg_pattern'      => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'wallpaper_bg_custom'       => new sfValidatorString(array('required' => false)),
      'header_bg_type'            => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'header_bg_color'           => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'header_bg_pattern'         => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'header_bg_custom'          => new sfValidatorString(array('required' => false)),
      'form_bg_type'              => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_bg_color'             => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_bg_pattern'           => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'form_bg_custom'            => new sfValidatorString(array('required' => false)),
      'highlight_bg_type'         => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'highlight_bg_color'        => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'highlight_bg_pattern'      => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'highlight_bg_custom'       => new sfValidatorString(array('required' => false)),
      'guidelines_bg_type'        => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'guidelines_bg_color'       => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'guidelines_bg_pattern'     => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'guidelines_bg_custom'      => new sfValidatorString(array('required' => false)),
      'field_bg_type'             => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'field_bg_color'            => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'field_bg_pattern'          => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'field_bg_custom'           => new sfValidatorString(array('required' => false)),
      'form_title_font_type'      => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'form_title_font_weight'    => new sfValidatorInteger(array('required' => false)),
      'form_title_font_style'     => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'form_title_font_size'      => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_title_font_color'     => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_desc_font_type'       => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'form_desc_font_weight'     => new sfValidatorInteger(array('required' => false)),
      'form_desc_font_style'      => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'form_desc_font_size'       => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_desc_font_color'      => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'field_title_font_type'     => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'field_title_font_weight'   => new sfValidatorInteger(array('required' => false)),
      'field_title_font_style'    => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'field_title_font_size'     => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'field_title_font_color'    => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'guidelines_font_type'      => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'guidelines_font_weight'    => new sfValidatorInteger(array('required' => false)),
      'guidelines_font_style'     => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'guidelines_font_size'      => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'guidelines_font_color'     => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'section_title_font_type'   => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'section_title_font_weight' => new sfValidatorInteger(array('required' => false)),
      'section_title_font_style'  => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'section_title_font_size'   => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'section_title_font_color'  => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'section_desc_font_type'    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'section_desc_font_weight'  => new sfValidatorInteger(array('required' => false)),
      'section_desc_font_style'   => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'section_desc_font_size'    => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'section_desc_font_color'   => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'field_text_font_type'      => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'field_text_font_weight'    => new sfValidatorInteger(array('required' => false)),
      'field_text_font_style'     => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'field_text_font_size'      => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'field_text_font_color'     => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'border_form_width'         => new sfValidatorInteger(array('required' => false)),
      'border_form_style'         => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'border_form_color'         => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'border_guidelines_width'   => new sfValidatorInteger(array('required' => false)),
      'border_guidelines_style'   => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'border_guidelines_color'   => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'border_section_width'      => new sfValidatorInteger(array('required' => false)),
      'border_section_style'      => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'border_section_color'      => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_shadow_style'         => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'form_shadow_size'          => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_shadow_brightness'    => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_button_type'          => new sfValidatorString(array('max_length' => 11, 'required' => false)),
      'form_button_text'          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'form_button_image'         => new sfValidatorString(array('required' => false)),
      'advanced_css'              => new sfValidatorString(array('required' => false)),
      'user_id'                   => new sfValidatorInteger(array('required' => false)),
      'theme_is_private'          => new sfValidatorInteger(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('ap_form_themes[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ApFormThemes';
  }

}
