<?php

/**
 * SubMenus form base class.
 *
 * @method SubMenus getObject() Returns the current form's model object
 *
 * @package    permitflow
 * @subpackage form
 * @author     Webmasters Africa
 * @version    SVN: $Id$
 */
abstract class BaseSubMenusForm extends BaseFormDoctrine
{
	public function setup()
	{
		$this->setWidgets(array(
			'id'                       => new sfWidgetFormInputHidden(),
			'title'                    => new sfWidgetFormTextarea(),
			'order_no'                 => new sfWidgetFormInputText(),
			'max_duration'             => new sfWidgetFormInputText(),
			'deleted'                  => new sfWidgetFormInputText(),
			'change_identifier'        => new sfWidgetFormChoice(array('choices' => array('No', 'Yes'))),
			'new_identifier'           => new sfWidgetFormInputText(),
			'new_identifier_start'     => new sfWidgetFormInputText(),
			'menu_id'                  => new sfWidgetFormDoctrineChoice(array('model' => 'Menus')),
			'hide_comments'            => new sfWidgetFormInputText(),
			'allow_edit'               => new sfWidgetFormChoice(array('choices' => array('No', 'Yes'))),
			'stage_type'               => new sfWidgetFormInputText(),
			'stage_property'           => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getStageProperties())),
			'stage_expired_movement'   => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getStages())),
			'stage_type_movement'      => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getStages())),
			'stage_type_notification'  => new sfWidgetFormTextarea(),
			'stage_type_movement_fail' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getStages())),
			'app_queuing'       => new sfWidgetFormChoice(array('choices' => array('default' => 'Default', 'ASC' => 'Ascending', 'DESC' => 'Descending'))),
			'change_identifier_condition' => new sfWidgetFormChoice(array('choices' => array('No', 'Yes'))),
			'change_field_form' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1))),
			'change_field_element' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field'))),
			'change_field_element_value' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'conditional_identifier'           => new sfWidgetFormInputText(),
			'conditional_identifier_1'           => new sfWidgetFormInputText(),
			'conditional_identifier_2'           => new sfWidgetFormInputText(),
			'conditional_identifier_3'           => new sfWidgetFormInputText(),
			'conditional_identifier_4'           => new sfWidgetFormInputText(),
			'change_field_form_1' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1))),
			'change_field_element_form_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field'))),
			'change_field_element_value_form_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_1_form_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_2_form_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_3_form_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_4_form_1' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'conditional_identifier_form_1'           => new sfWidgetFormInputText(),
			'conditional_identifier_1_form_1'           => new sfWidgetFormInputText(),
			'conditional_identifier_2_form_1'           => new sfWidgetFormInputText(),
			'conditional_identifier_3_form_1'           => new sfWidgetFormInputText(),
			'conditional_identifier_4_form_1'           => new sfWidgetFormInputText(),
			'change_field_form_2' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1))),
			'change_field_element_form_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field'))),
			'change_field_element_value_form_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_1_form_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_2_form_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_3_form_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_4_form_2' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'conditional_identifier_form_2'           => new sfWidgetFormInputText(),
			'conditional_identifier_1_form_2'           => new sfWidgetFormInputText(),
			'conditional_identifier_2_form_2'           => new sfWidgetFormInputText(),
			'conditional_identifier_3_form_2'           => new sfWidgetFormInputText(),
			'conditional_identifier_4_form_2'           => new sfWidgetFormInputText(),
			'change_field_form_3' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1))),
			'change_field_element_form_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field'))),
			'change_field_element_value_form_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_1_form_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_2_form_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_3_form_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_4_form_3' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'conditional_identifier_form_3'           => new sfWidgetFormInputText(),
			'conditional_identifier_1_form_3'           => new sfWidgetFormInputText(),
			'conditional_identifier_2_form_3'           => new sfWidgetFormInputText(),
			'conditional_identifier_3_form_3'           => new sfWidgetFormInputText(),
			'conditional_identifier_4_form_3'           => new sfWidgetFormInputText(),
			'change_field_form_4' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1))),
			'change_field_element_form_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field'))),
			'change_field_element_value_form_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_1_form_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_2_form_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_3_form_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_4_form_4' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'conditional_identifier_form_4'           => new sfWidgetFormInputText(),
			'conditional_identifier_1_form_4'           => new sfWidgetFormInputText(),
			'conditional_identifier_2_form_4'           => new sfWidgetFormInputText(),
			'conditional_identifier_3_form_4'           => new sfWidgetFormInputText(),
			'conditional_identifier_4_form_4'           => new sfWidgetFormInputText(),
			'change_field_form_5' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1))),
			'change_field_element_form_5' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field'))),
			'change_field_element_value_form_5' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_1_form_5' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_2_form_5' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_3_form_5' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'change_field_element_value_4_form_5' => new sfWidgetFormChoice(array('choices' => array(0 => 'Select field value'))),
			'conditional_identifier_form_5'           => new sfWidgetFormInputText(),
			'conditional_identifier_1_form_5'           => new sfWidgetFormInputText(),
			'conditional_identifier_2_form_5'           => new sfWidgetFormInputText(),
			'conditional_identifier_3_form_5'           => new sfWidgetFormInputText(),
			'conditional_identifier_4_form_5'           => new sfWidgetFormInputText(),
			'shared_stage_move'           => new sfWidgetFormChoice(array('choices' => array('No', 'Yes'))),
			'shared_stage'           => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getStages())),
			'stage_payment_confirmation'           => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getStages())),
			'stage_expired_invoice_action' => new sfWidgetFormChoice(array('choices' => Doctrine_Core::getTable('SubMenus')->getExpiredInvoiceAction())),
			'stage_expired_movement_decline'           => new sfWidgetFormChoice(array('choices' => array('No', 'Yes'))),
			'distribute_equally'           => new sfWidgetFormChoice(array('choices' => array('No', 'Yes'))),
		));

		$this->setValidators(array(
			'id'                       => new sfValidatorChoice(array('choices' => array($this->getObject()->get('id')), 'empty_value' => $this->getObject()->get('id'), 'required' => false)),
			'title'                    => new sfValidatorString(),
			'order_no'                 => new sfValidatorInteger(array('required' => false)),
			'max_duration'             => new sfValidatorInteger(array('required' => false)),
			'deleted'                  => new sfValidatorInteger(array('required' => false)),
			'change_identifier'        => new sfValidatorChoice(array('choices' => array_keys(array('No', 'Yes')))),
			'new_identifier'           => new sfValidatorString(array('required' => false)),
			'new_identifier_start'     => new sfValidatorString(array('max_length' => 250, 'required' => false)),
			'menu_id'                  => new sfValidatorDoctrineChoice(array('model' => 'Menus', 'required' => true)),
			'hide_comments'            => new sfValidatorInteger(array('required' => false)),
			'allow_edit'               => new sfValidatorChoice(array('choices' => array_keys(array('No', 'Yes')))),
			'stage_type'               => new sfValidatorInteger(array('required' => false)),
			'stage_property'           => new sfValidatorInteger(array('required' => false)),
			'stage_expired_movement'   => new sfValidatorInteger(array('required' => false)),
			'stage_type_movement'      => new sfValidatorInteger(array('required' => false)),
			'stage_type_notification'  => new sfValidatorString(array('required' => false)),
			'stage_type_movement_fail' => new sfValidatorInteger(array('required' => false)),
			'app_queuing'    => new sfValidatorString(), //OTB patch add app queuing   
			'change_identifier_condition' => new sfValidatorChoice(array('choices' => array_keys(array('No', 'Yes')))),
			'change_field_form' => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1)), 'required' => false)),
			'change_field_element' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_1'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_2'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_3'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_4'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_form_1' => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1)), 'required' => false)),
			'change_field_element_form_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_form_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_1_form_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_2_form_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_3_form_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_4_form_1' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_form_1'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_1_form_1'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_2_form_1'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_3_form_1'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_4_form_1'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_form_2' => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1)), 'required' => false)),
			'change_field_element_form_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_form_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_1_form_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_2_form_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_3_form_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_4_form_2' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_form_2'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_1_form_2'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_2_form_2'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_3_form_2'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_4_form_2'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_form_3' => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1)), 'required' => false)),
			'change_field_element_form_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_form_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_1_form_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_2_form_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_3_form_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_4_form_3' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_form_3'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_1_form_3'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_2_form_3'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_3_form_3'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_4_form_3'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_form_4' => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1)), 'required' => false)),
			'change_field_element_form_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_form_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_1_form_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_2_form_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_3_form_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_4_form_4' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_form_4'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_1_form_4'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_2_form_4'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_3_form_4'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_4_form_4'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_form_5' => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('ApForms')->getAllApplicationForms(1)), 'required' => false)),
			'change_field_element_form_5' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_form_5' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_1_form_5' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_2_form_5' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_3_form_5' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'change_field_element_value_4_form_5' => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_form_5'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_1_form_5'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_2_form_5'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_3_form_5'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'conditional_identifier_4_form_5'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
			'shared_stage_move'           => new sfValidatorChoice(array('choices' => array_keys(array('No', 'Yes')))),
			'stage_expired_invoice_action'           => new sfValidatorChoice(array('choices' => array_keys(Doctrine_Core::getTable('SubMenus')->getExpiredInvoiceAction()))),
			'shared_stage'           => new sfValidatorInteger(array('required' => false)),
			'stage_payment_confirmation'           => new sfValidatorInteger(array('required' => false)),
			'stage_expired_movement_decline' => new sfValidatorChoice(array('choices' => array_keys(array('No', 'Yes')))),
			'distribute_equally' => new sfValidatorChoice(array('choices' => array_keys(array('No', 'Yes')))),
		));

		$this->widgetSchema->setNameFormat('sub_menus[%s]');

		$this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

		$this->setupInheritance();

		parent::setup();
	}

	public function getModelName()
	{
		return 'SubMenus';
	}
}
